### ISSUE TITLE
"Search failed" when trying to load org-trello-mode

### ISSUE THREAD

**Issue by inuse** [org-trello/org-trello#179]
Up front I'll say this is under cygwin, so I understand if you say it's not possible

I've installed latest org-trello from http://melpa-stable.milkbox.net/packages

I've gotten the key and auth to work, but when I try to load the mode, I get

"contacting host: localhost:9867", 

followed by:

Search failed: "\=[]*HTTP/\([0-9\.]+\) +\([0-9]+\)"

**Comment by SamHasler** [comment]
I'm still getting this with the latest version:

```
System information:
- system-type: windows-nt
- locale-coding-system: cp1252
- emacs-version: GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)
 of 2015-09-07
- org version: 8.2.10
- org-trello version: 0.7.5
- org-trello path: c:/Users/haslers/.emacs.d/elpa/org-trello-20151213.736/org-trello.el
```

Would the network requests use the `url-proxy-services` setting?

**Comment by ardumont** [comment]
Hello,

> Would the network requests use the url-proxy-services setting?

I have no idea.

[But this sounds like a possibility](https://github.com/tkf/emacs-request/blob/master/request.el#L65-L67).

If it won't detect curl it uses the url lib (same group as the variable you just mentioned).

**Comment by SamHasler** [comment]
It probably is finding curl. Is there any way to force it to use the url lib?

**Comment by ardumont** [comment]
Hello,

> It probably is finding curl. 

You just have to evaluate the `request-backend` to show its value (curl or url-retrieve) and we will know what your system uses.

For this, write in a scratch buffer (default mode is an emacs-lisp one), `request-backend`.
Then evaluate the expression (place your caret at the end of it and the <kbd>M-x eval-last-sexp</kbd>).

Mine displays `curl` in the mini-buffer (lower left corner in emacs).

> Is there any way to force it to use the url lib?

As this is a `defcustom` variable (user overridable variable), this is possible:

```lisp
(custom-set-variables '(request-backend 'url-retrieve))
```

To make it permanent (persist after an emacs restart), you can add this snippet to your ~/.emacs or ~/.emacs.d/init.el (ymmv).

Cheers,

**Comment by SamHasler** [comment]
request-backend was curl, switching to url-retrieve fixed my network/proxy problems.

(I use a cntlm proxy to add ntlm authentication to outgoing requests and cntlm also then forwards to our corporate proxy.)

**Comment by ardumont** [comment]
@SamHasler Great news! Thanks for detailing this and the solution.

Cheers,
