### ISSUE TITLE
create-board-and-install-metadata gives error 60

### ISSUE THREAD

**Issue by kaushalmodi** [org-trello/org-trello#231]
Hi,

I finished the org-trello and trello.com authorization process which finishes with entering the token.

Then I created a new empty .org file and added the below to it
<pre>
#+TODO: TODO DOING | DONE FAIL
</pre>

Then I did the following:
1. `M-x org-trello-mode`
2. `C-c o b`

and get this error:
<pre>
org-trello - Create board and lists...
Loading /home/kmodi/.trello/config.el (source)...done
org-trello - client - Problem during request - error-thrown: (error . exited abnormally with code 60
)
</pre>

`C-c o I` also gives the same error:
<pre>
org-trello - client - Problem during request - error-thrown: (error . exited abnormally with code 60
)
</pre>

**Comment by ardumont** [comment]
Hello,

I'm not near my computer right now (some time off ;).

In the mean time, could you please provide the [following information](http://org-trello.github.io/contributions.html#issues)?

Thanks.

**Comment by kaushalmodi** [comment]
emacs version: latest stable 24.4
org-trello version: latest on `melpa`  0.6.8

**Comment by ardumont** [comment]
> emacs version: latest stable 24.4
> org-trello version: latest on melpa 0.6.8

Thanks.

--

Can you show me a sample of your anonymised org buffer please?

Can you try executing this code in a scratch buffer please?

Just copy/paste this in an empty buffer:

```lisp
(setq *orgtrello-log/level* *OT/TRACE*)
```

Then M-x eval-buffer.

This will increase the log level.

Then you can for example redo the exact same steps you did but this time, you should see more information on the *Message* buffer.
If you could do that and copy/paste the content of the message buffer here, this would help.

Thanks

**Comment by kaushalmodi** [comment]
To be honest, I have no idea what an *anonymized org buffer* is. The test.org file I used simply has this line

<pre>
#+TODO: TODO DOING | DONE FAIL
</pre>

I then did,

1. `M-x org-trello-mode`
2. `M-x org-trello/install-board-metadata`

and got the below error:

<pre>
org-trello - org-trello/ot is on! To begin with, hit C-c o h or M-x 'org-trello/help-describing-bindings
org-trello - Install boards and lists...
Loading /home/kmodi/.trello/config.el (source)...done
org-trello - client - Problem during request - error-thrown: (error . exited abnormally with code 60
)
org-trello - Detailed response: [cl-struct-request-response nil nil nil (error . "exited abnormally with code 60
") error "https://api.trello.com/1/members/me?key=MY_KEY&token=MY_TOKEN" nil (:sync t :type "GET" :params ((key . "MY_KEY") (token . "MY_TOKEN")) :parser orgtrello-query/--http-parse :success orgtrello-query/--standard-success-callback ...) #<killed buffer> ...]
org-trello - client - Problem during request - error-thrown: (error . exited abnormally with code 60
)
org-trello - Detailed response: [cl-struct-request-response nil nil nil (error . "exited abnormally with code 60
") error "https://api.trello.com/1/members/me/boards?key=MY_KEY&token=MY_TOKEN&filter=open&lists=open" nil (:sync t :type "GET" :params ((key . "MY_KEY") (token . "MY_TOKEN") ("filter" . "open") ("lists" . "open")) :parser orgtrello-query/--http-parse :success orgtrello-query/--standard-success-callback ...) #<killed buffer> ...]
</pre>

*As I am ignorant about how the key and token can compromise my trello account, I have replaced the actual values above with `MY_KEY` and `MY_TOKEN`*.

**Comment by ardumont** [comment]
Yes, you understood alright.
But install board metadata suppose you have open boards on trello.

I'm trying to ascertain that I understood your pb right too.

Do you have an already existing open board in trello?

What does the last http request tells you (in the web browser)?

(I'm on my phone right now with a really really poor connection)

Cheers.

**Comment by kaushalmodi** [comment]
In a webbrowser, this URL works fine:

<pre>
https://api.trello.com/1/members/me/boards?key=MY_KEY&token=MY_TOKEN&filter=open&lists=open
</pre>

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/5620319/ce10229a-94f8-11e4-9a01-446431f64985.png)

**Comment by ardumont** [comment]
Thanks

Will definitely investigate further when I'll be able to...

**Comment by ardumont** [comment]
Hello,

I am not able to reproduce this behavior.

I:
- installed from a clean emacs with the bare org-trello dependencies (cf. https://github.com/org-trello/org-trello/blob/master/Makefile#L67 + https://github.com/ardumont/sh/blob/master/emacs/emacs-install-clean.sh).

- Created a new org buffer.

- and either those commands work as expected:
  - `M-x org-trello/create-board-and-install-metadata` (asks you for the board name + optional description, then goes on creating a board and install the data needed for the communication between the trello board and the org buffer to work -> this is what I called metadata).
  - `M-x org-trello/install-board-metadata` (asks you for the board to attach to and then writes the needed metadata in the buffer).

Please, can you provide the following information:
- For `M-x org-trello/create-board-and-install-metadata`:
  - What's the board name you input when you try to create a board?
- For `M-x org-trello/install-board-metadata`:
  - Do you have open boards on trello (it seems so but I am unable to understand the screenshot you provided)?
- What's your o.s? (I'm running under various GNU/Linux distributions but I'm unable to test all platforms).

- Can you please provide anonymised text sample from the following requests?
  1- https://api.trello.com/1/members/me?key=MY_KEY&token=MY_TOKEN
  2- https://api.trello.com/1/members/me/boards?key=MY_KEY&token=MY_TOKEN&filter=open&lists=open

Here is mine for comparison's sake:

1- Some relative information about the connected user (you).
``` json
{"id":"abc","avatarHash":"def","bio":"polyglot & functional developer\ndevops","bioData":{"emoji":{}},"confirmed":true,"fullName":"Antoine R. Dumont","idPremOrgsAdmin":[],"initials":"AD","memberType":"normal","products":[],"status":"idle","url":"https://trello.com/ardumont","username":"ardumont","avatarSource":"gravatar","email":null,"gravatarHash":"ijk","idBoards":["mnl","opq"],"idOrganizations":[],"loginTypes":null,"oneTimeMessagesDismissed":["newtrelloIntro"],"prefs":{"sendSummaries":true,"minutesBetweenSummaries":60,"minutesBeforeDeadlineToNotify":1440,"colorBlind":false,"timezoneInfo":{"timezoneNext":"CEST","dateNext":"2015-03-29T01:00:00.000Z","offsetNext":-120,"timezoneCurrent":"CET","offsetCurrent":-60}},"trophies":[],"uploadedAvatarHash":null,"premiumFeatures":[],"idBoardsPinned":null}
```

2- Here, we can see 2 open boards:
```json
[{"id":"abc","name":"Welcome Board","desc":"","descData":null,"closed":false,"idOrganization":null,"invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/def/welcome-board","prefs":{"permissionLevel":"private","voting":"members","comments":"members","invitations":"members","selfJoin":false,"cardCovers":true,"background":"blue","backgroundColor":"#0079BF","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"abc","idMember":"def","memberType":"normal","unconfirmed":false,"deactivated":false},{"id":"ijk","idMember":"klf","memberType":"admin","unconfirmed":false,"deactivated":false}],"shortLink":"WlQaiBni","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":["voting"],"dateLastActivity":"2014-09-01T19:43:15.355Z","dateLastView":"2014-09-08T21:07:14.915Z","shortUrl":"https://trello.com/b/abc","lists":[{"id":"abc","name":"Basics","closed":false,"idBoard":"def","pos":16384,"subscribed":false},{"id":"abc","name":"Intermediate","closed":false,"idBoard":"def","pos":32768,"subscribed":false},{"id":"abc","name":"Advanced","closed":false,"idBoard":"def","pos":49152,"subscribed":false}]}
  ,{"id":"def","name":"api test board","desc":"","descData":null,"closed":false,"idOrganization":null,"invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/ijk/api-test-board","prefs":{"permissionLevel":"private","voting":"disabled","comments":"members","invitations":"members","selfJoin":true,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"blue","backgroundColor":"#0079BF","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"abc","idMember":"def","memberType":"admin","unconfirmed":false,"deactivated":false},{"id":"abc","idMember":"def","memberType":"normal","unconfirmed":false,"deactivated":false}],"shortLink":"RIlJAK05","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":[],"dateLastActivity":"2015-01-11T08:22:13.128Z","dateLastView":"2015-01-11T08:22:13.180Z","shortUrl":"https://trello.com/b/abc","lists":[{"id":"abc","name":"TODO","closed":false,"idBoard":"def","pos":128,"subscribed":false},{"id":"abc","name":"IN-PROGRESS","closed":false,"idBoard":"def","pos":256,"subscribed":false},{"id":"abc","name":"DONE","closed":false,"idBoard":"def","pos":512,"subscribed":false},{"id":"abc","name":"PENDING","closed":false,"idBoard":"def","pos":1024,"subscribed":false},{"id":"abc","name":"DELEGATED","closed":false,"idBoard":"def","pos":2048,"subscribed":false},{"id":"abc","name":"FAILED","closed":false,"idBoard":"def","pos":4096,"subscribed":false},{"id":"abc","name":"CANCELLED","closed":false,"idBoard":"def","pos":8192,"subscribed":false}]}]
```

Cheers,

**Comment by kaushalmodi** [comment]
Hi,

Here is the requested information:

* On doing `M-x org-trello/create-board-and-install-metadata`, I get this error 60. I get the prompt `Input the number of the board desired:`. But regardless of what I enter in it, nothing happens. The only way I can quit that prompt is by hitting `C-g`.

* On doing `M-x org-trello/install-board-metadata`, I get this error 60 and nothing happens.

* On doing `lsb_release -irc` to get the OS information, I get:
</pre>
Distributor ID: RedHatEnterpriseClient
Release:        5.10
Codename:       Tikanga
</pre>

* Text sample from https://api.trello.com/1/members/me?key=MY_KEY&token=MY_TOKEN
<pre>
{"id":"MY_ID","avatarHash":"MY_AVATARHASH","bio":"","bioData":null,"confirmed":true,"fullName":"Kaushal Modi","idPremOrgsAdmin":[],"initials":"KM","memberType":"normal","products":[],"status":"active","url":"https://trello.com/kaushalmodi","username":"kaushalmodi","avatarSource":"upload","email":null,"gravatarHash":"6dbe470c7ef3817bb1da85dc5883acbe","idBoards":["IDBOARDS_0","IDBOARDS_1","IDBOARDS_2","IDBOARDS_3","IDBOARDS_4","IDBOARDS_5","IDBOARDS_6","IDBOARDS_7","IDBOARDS_8","IDBOARDS_9"],"idOrganizations":["IDORGANIZATIONS_0"],"loginTypes":null,"oneTimeMessagesDismissed":["GoldEarned"],"prefs":{"sendSummaries":true,"minutesBetweenSummaries":60,"minutesBeforeDeadlineToNotify":1440,"colorBlind":false,"timezoneInfo":{"timezoneNext":"EDT","dateNext":"2015-03-08T07:00:00.000Z","offsetNext":240,"timezoneCurrent":"EST","offsetCurrent":300}},"trophies":[],"uploadedAvatarHash":"MY_AVATARHASH","premiumFeatures":[],"idBoardsPinned":null}
</pre>

* Text sample from https://api.trello.com/1/members/me/boards?key=MY_KEY&token=MY_TOKEN&filter=open&lists=open
<pre>
[{"id":"IDBOARDS_1","name":"Cars","desc":"","descData":null,"closed":false,"idOrganization":"IDORGANIZATIONS_0","invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/URL_STRING_7/cars","prefs":{"permissionLevel":"private","voting":"disabled","comments":"members","invitations":"members","selfJoin":false,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"green","backgroundColor":"#1E9F49","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"SOME_ID","idMember":"MY_ID","memberType":"admin","unconfirmed":false,"deactivated":false},{"id":"SOME_ID","idMember":"SOME_ID","memberType":"normal","unconfirmed":false,"deactivated":false}],"shortLink":"Z0m3D1us","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":[],"dateLastActivity":"2015-01-06T05:19:19.051Z","dateLastView":"2015-01-10T23:24:05.352Z","shortUrl":"https://trello.com/b/URL_STRING_6","lists":[{"id":"SOME_ID","name":"To Do","closed":false,"idBoard":"IDBOARDS_1","pos":16384,"subscribed":false},{"id":"SOME_ID","name":"Done","closed":false,"idBoard":"IDBOARDS_1","pos":49152,"subscribed":false}]},{"id":"IDBOARDS_8","name":"Emacs","desc":"","descData":null,"closed":false,"idOrganization":null,"invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/URL_STRING_5/emacs","prefs":{"permissionLevel":"private","voting":"disabled","comments":"members","invitations":"members","selfJoin":false,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"grey","backgroundColor":"#808080","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"SOME_ID","idMember":"MY_ID","memberType":"admin","unconfirmed":false,"deactivated":false}],"shortLink":"ZOUnjY9C","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":[],"dateLastActivity":"2015-01-05T19:34:30.312Z","dateLastView":"2015-01-07T19:29:14.046Z","shortUrl":"https://trello.com/b/URL_STRING_0","lists":[{"id":"SOME_ID","name":"To try/verify","closed":false,"idBoard":"IDBOARDS_8","pos":65535,"subscribed":false}]},{"id":"IDBOARDS_5","name":"Home","desc":"","descData":null,"closed":false,"idOrganization":"IDORGANIZATIONS_0","invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/URL_STRING_4/home","prefs":{"permissionLevel":"org","voting":"disabled","comments":"members","invitations":"members","selfJoin":true,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"purple","backgroundColor":"#8B5798","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"SOME_ID","idMember":"MY_ID","memberType":"admin","unconfirmed":false,"deactivated":false},{"id":"SOME_ID","idMember":"SOME_ID","memberType":"normal","unconfirmed":false,"deactivated":false}],"shortLink":"x7Vrd03J","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":[],"dateLastActivity":"2015-01-04T21:46:44.670Z","dateLastView":"2015-01-04T21:46:44.692Z","shortUrl":"https://trello.com/b/URL_STRING_3","lists":[{"id":"SOME_ID","name":"To Fix","closed":false,"idBoard":"IDBOARDS_5","pos":65535,"subscribed":false},{"id":"SOME_ID","name":"Home Theater","closed":false,"idBoard":"IDBOARDS_5","pos":131071,"subscribed":false}]},{"id":"IDBOARDS_2","name":"Kush","desc":"","descData":null,"closed":false,"idOrganization":"IDORGANIZATIONS_0","invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/URL_STRING_2/kush","prefs":{"permissionLevel":"private","voting":"disabled","comments":"members","invitations":"members","selfJoin":false,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"blue","backgroundColor":"#0079BF","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"SOME_ID","idMember":"MY_ID","memberType":"admin","unconfirmed":false,"deactivated":false},{"id":"SOME_ID","idMember":"SOME_ID","memberType":"normal","unconfirmed":false,"deactivated":false}],"shortLink":"ViXQkuHi","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":[],"dateLastActivity":"2015-01-03T22:57:11.432Z","dateLastView":"2015-01-03T23:27:06.366Z","shortUrl":"https://trello.com/b/URL_STRING_1","lists":[{"id":"SOME_ID","name":"To Do","closed":false,"idBoard":"IDBOARDS_2","pos":16384,"subscribed":false},{"id":"SOME_ID","name":"Done","closed":false,"idBoard":"IDBOARDS_2","pos":49152,"subscribed":false}]},{"id":"IDBOARDS_9","name":"Money","desc":"","descData":null,"closed":false,"idOrganization":"IDORGANIZATIONS_0","invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/URL_STRING_8/money","prefs":{"permissionLevel":"org","voting":"disabled","comments":"members","invitations":"members","selfJoin":true,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"red","backgroundColor":"#C24034","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"SOME_ID","idMember":"MY_ID","memberType":"admin","unconfirmed":false,"deactivated":false},{"id":"SOME_ID","idMember":"SOME_ID","memberType":"normal","unconfirmed":false,"deactivated":false}],"shortLink":"BP0vwsBT","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":[],"dateLastActivity":"2015-01-10T04:07:21.695Z","dateLastView":"2015-01-10T04:07:21.718Z","shortUrl":"https://trello.com/b/URL_STRING_9","lists":[{"id":"SOME_ID","name":"Gift Cards","closed":false,"idBoard":"IDBOARDS_9","pos":65535,"subscribed":false},{"id":"SOME_ID","name":"Investment & Savings","closed":false,"idBoard":"IDBOARDS_9","pos":163839,"subscribed":false},{"id":"SOME_ID","name":"Other","closed":false,"idBoard":"IDBOARDS_9","pos":229375,"subscribed":false},{"id":"SOME_ID","name":"Done","closed":false,"idBoard":"IDBOARDS_9","pos":294911,"subscribed":false}]},{"id":"IDBOARDS_7","name":"Stuff","desc":"","descData":null,"closed":false,"idOrganization":null,"invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/URL_STRING_10/stuff","prefs":{"permissionLevel":"private","voting":"disabled","comments":"members","invitations":"members","selfJoin":false,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"blue","backgroundColor":"#0079BF","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"SOME_ID","idMember":"MY_ID","memberType":"admin","unconfirmed":false,"deactivated":false}],"shortLink":"ydN6Yl1i","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":[],"dateLastActivity":"2015-01-07T19:29:46.628Z","dateLastView":"2015-01-07T19:29:50.894Z","shortUrl":"https://trello.com/b/URL_STRING_11","lists":[{"id":"SOME_ID","name":"Money","closed":false,"idBoard":"IDBOARDS_7","pos":65535,"subscribed":false},{"id":"SOME_ID","name":"Android","closed":false,"idBoard":"IDBOARDS_7","pos":81919,"subscribed":false},{"id":"SOME_ID","name":"Done","closed":false,"idBoard":"IDBOARDS_7","pos":147455,"subscribed":false}]},{"id":"IDBOARDS_6","name":"Us","desc":"","descData":null,"closed":false,"idOrganization":"IDORGANIZATIONS_0","invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/URL_STRING_12/us","prefs":{"permissionLevel":"org","voting":"disabled","comments":"members","invitations":"members","selfJoin":true,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"grey","backgroundColor":"#808080","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"SOME_ID","idMember":"MY_ID","memberType":"admin","unconfirmed":false,"deactivated":false},{"id":"SOME_ID","idMember":"SOME_ID","memberType":"normal","unconfirmed":false,"deactivated":false}],"shortLink":"Redd8Q4l","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":[],"dateLastActivity":"2015-01-02T22:51:36.616Z","dateLastView":"2015-01-03T22:57:17.392Z","shortUrl":"https://trello.com/b/URL_STRING_13","lists":[{"id":"SOME_ID","name":"Misc","closed":false,"idBoard":"IDBOARDS_6","pos":65535,"subscribed":false},{"id":"SOME_ID","name":"Raji-Rupal's Wedding Trip","closed":false,"idBoard":"IDBOARDS_6","pos":131071,"subscribed":false},{"id":"SOME_ID","name":"India Trip","closed":false,"idBoard":"IDBOARDS_6","pos":196607,"subscribed":false}]},{"id":"IDBOARDS_3","name":"Work","desc":"","descData":null,"closed":false,"idOrganization":null,"invited":false,"pinned":false,"starred":false,"url":"https://trello.com/b/URL_STRING_14/work","prefs":{"permissionLevel":"private","voting":"disabled","comments":"members","invitations":"members","selfJoin":false,"cardCovers":true,"cardAging":"regular","calendarFeedEnabled":false,"background":"red","backgroundColor":"#C24034","backgroundImage":null,"backgroundImageScaled":null,"backgroundTile":false,"backgroundBrightness":"unknown","canBePublic":true,"canBeOrg":true,"canBePrivate":true,"canInvite":true},"invitations":[],"memberships":[{"id":"SOME_ID","idMember":"MY_ID","memberType":"admin","unconfirmed":false,"deactivated":false}],"shortLink":"xcrlpNO1","subscribed":false,"labelNames":{"green":"","yellow":"","orange":"","red":"","purple":"","blue":"","sky":"","lime":"","pink":"","black":""},"powerUps":["calendar"],"dateLastActivity":"2015-01-08T20:25:28.400Z","dateLastView":"2015-01-08T21:04:10.324Z","shortUrl":"https://trello.com/b/URL_STRING_15","lists":[{"id":"SOME_ID","name":"UVM Development, Papers","closed":false,"idBoard":"IDBOARDS_3","pos":8192,"subscribed":false},{"id":"SOME_ID","name":"Self Development","closed":false,"idBoard":"IDBOARDS_3","pos":12288,"subscribed":false},{"id":"SOME_ID","name":"Prj Tal Lite","closed":false,"idBoard":"IDBOARDS_3","pos":16384,"subscribed":false},{"id":"SOME_ID","name":"Improvements","closed":false,"idBoard":"IDBOARDS_3","pos":49152,"subscribed":false}]}]
</pre>

**Comment by kaushalmodi** [comment]
A thought.. can you provide a means to use plain old `curl` to grab this info if I can access it by entering the URL in the browser?

**Comment by ardumont** [comment]
>  ...

Thanks for the answers and the formatting, it's way clearer that way :D

> A thought.. can you provide a means to use plain old curl to grab this info if I can access it by entering the URL in the browser?

This should do the trick...
```sh
curl https://api.trello.com/1/members/me/boards?key=MY_KEY&token=MY_TOKEN&filter=open&lists=open
```

will give you the same output as the browser.
I do not think that was what you meant though.

If you want the CLI equivalent of the lisp code which parses the trello's json response that would be complicated...

When I started org-trello, I did the setup manually though...
As it was tedious, I finally developed commands to automate this (the very thing which do not work for you here)...

Basically, what you want to do is something along those lines, here is a template that you want to add at the beginning of the org-buffer:
```org
:PROPERTIES:
#+property: board-name your-board-name
#+property: board-id your-board-id
#+PROPERTY: CANCELLED your-list-id-for-the-one-called-CANCELLED
#+PROPERTY: FAILED your-list-id-for-the-one-called-CANardumontCELLED
#+PROPERTY: DELEGATED your-list-id-for-the-one-called-DELEGATED
#+PROPERTY: PENDING your-list-id-for-the-one-called-PENDING
#+PROPERTY: DONE your-list-id-for-the-one-called-DONE
#+PROPERTY: TODO your-list-id-for-the-one-called-TODO
#+TODO: TODO | DONE PENDING DELEGATED FAILED CANCELLED
#+PROPERTY: orgtrello-user-your-collab-on-board your-collab-on-board-user-id
#+PROPERTY: orgtrello-user-your-user-name your-user-name-id
#+PROPERTY: :yellow this-can-stay-empty-but-refers-to-trello-label-title
#+PROPERTY: :red red
#+PROPERTY: :purple violet
#+PROPERTY: :orange range
#+PROPERTY: :green green label with & char
#+PROPERTY: :blue blue
#+PROPERTY: orgtrello-user-me your-user-name
:END:
```

Now, you need to replace the entries `your-something` with real values that you can find by parsing the json response... 

The information relative to you are in the first request's response.
The information relative to your board (board id, board-name, list ids...) are in the second request's response.

**Comment by kaushalmodi** [comment]
Probably this could be the source of the problem:

When I tried `curl "https://api.trello.com/1/members/me/boards?key=MY_KEY&token=MY_TOKEN&filter=open&lists=open"`, I got

<pre>
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). The default
 bundle is named curl-ca-bundle.crt; you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
</pre>

Then when I added the `-k` flag, I got:
<pre>
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=17&xinfo=9-7794853-0 0NNN RT(1421075495752 414) q(-1 -1 -1 -1) r(0 -1) b1&incident_id=0-68347523995271897&edet=3&cinfo=ffffffff" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 0-68347523995271897</iframe></body></html>
</pre>

So looks like I can't access the trello info from command line?

**Comment by ardumont** [comment]
> Probably this could be the source of the problem...

Indeed, this seems so.
(The curl command returns the same data as the browser on my side.)

(This reminds me of https://github.com/org-trello/org-trello/issues/228 and https://github.com/org-trello/org-trello/issues/180#issuecomment-51139237...).

However, I'm not sure what to look at next...

Here is my curl version for starters:
```sh
# tony at lenovo in ~/repo/perso/dot-files on git:master o [15:23:42]
$ curl --version
curl 7.39.0 (x86_64-unknown-linux-gnu) libcurl/7.39.0 OpenSSL/1.0.1j zlib/1.2.8 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

> The same error code: curl: (60) SSL certificate problem

Ok, [emacs-request](https://github.com/tkf/emacs-request) is the library used by org-trello to deal with http requests does use curl so that's the issues.
That was not clear to me.

So thanks, because now I know where to look for error codes (which seems to be simply the [error codes returned by curl](http://curl.haxx.se/libcurl/c/libcurl-errors.html)).

Cheers,

**Comment by kaushalmodi** [comment]
Aha! And here my curl version, a very antiquated one, it seems; it ships with the OS I use at work. I can try building the latest curl but I know I will have issues then building the zillion dependencies too :(

<pre>
curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.8 libidn/0.6.5
Protocols: tftp ftp telnet dict ldap http file https ftps
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
</pre>

**Comment by ardumont** [comment]
error 60 is 
```txt
CURLE_SSL_CACERT (60)

Peer certificate cannot be authenticated with known CA certificates. 
```

So an upgrade of the openssl bundle may help (I do not know how to update the ca-bundle.crt file).

Looking at the header of the file /etc/ssl/certs/ca-bundle.crt, this seems to be the file that need to be adapted for curl...

```txt
##
## ca-bundle.crt -- Bundle of CA Root Certificates
##
## Certificate data from Mozilla as of: Tue Jul 15 08:33:20 2014
##
## This is a bundle of X.509 certificates of public Certificate Authorities
## (CA). These were automatically extracted from Mozilla's root certificates
## file (certdata.txt).  This file can be found in the mozilla source tree:
## http://mxr.mozilla.org/mozilla-release/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1
##
## It contains the certificates in PEM format and therefore
## can be directly used with curl / libcurl / php_curl, or with
## an Apache+mod_ssl webserver for SSL client authentication.
## Just configure this file as the SSLCACertificateFile.
##
```

**Comment by ardumont** [comment]
> Aha! And here my curl version, a very antiquated one, it seems; it ships with the OS I use at work. I can try building the latest curl but I know I will have issues then building the zillion dependencies too :(
> 
> curl 7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.8 libidn/0.6.5
> Protocols: tftp ftp telnet dict ldap http file https ftps
> Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

Yes, I feel for you!

--

Try nix maybe... 
http://nixos.org/nix/manual/#chap-installation

It won't mess with your RH install (and this is any-gnu-linux compatible and reproducible)
Once nix is installed:

``` sh
nix-env -i curl
```
(this will fetch the dependencies as yum/apt-get/emerge/... does but the nix way)

Sure, now you have a new problem... but I think this is worth the investment...
It's a possibility... only you can decide :D 

Cheers,

**Comment by kaushalmodi** [comment]
Yes! Finally got it working by upgrading the libraries; fortunately it wasn't too bad.

**Solution**: Upgraded to `curl 7.40.0` and `OpenSSL 1.0.1k`.

**Comment by ardumont** [comment]
Great news!

Thx for the feedback.

Cheers
