### ISSUE TITLE
org-trello 0.6.8 does not synchronize either way

### ISSUE THREAD

**Issue by gracjan** [org-trello/org-trello#234]
org-trello/version = 0.6.8

What works:
1. Install existing board
2. Create a new board

What does not work:
1. C-u C-c o s - update
2. C-c o d - check

Both end with not very useful:

```txt
org-trello - List of errors:
 - Setup problem.
Either you did not connect your org-mode buffer with a trello board, to correct this:
  * attach to a board through C-c o I or M-x org-trello/install-board-metadata
  * or create a board from scratch with C-c o b or M-x org-trello/create-board-and-install-metadata).
Either your org-mode's todo keyword list and your trello board lists are not named the same way (which they must).
For this, connect to trello and rename your board's list according to your org-mode's todo list.
Also, you can specify on your org-mode buffer the todo list you want to work with, for example: #+TODO: TODO DOING | DONE FAIL (hit C-c C-c to refresh the setup)
```

The Messages buffer does not seem to contain anything useful, even though my org-trello/trace is at level 5.

How to debug this?

**Comment by gracjan** [comment]
Debugged a little:

After C-c o I I get:

    :PROPERTIES:
    #+property: board-name test
    #+property: board-id 123441297449afd0ed24b27f
    #+PROPERTY: DONE 1234412bbc8922d34689f6c5
    #+PROPERTY: TODO 1234412b5871f56f3c648094
    ...

after that is changed to:

    :PROPERTIES:
    #+PROPERTY: board-name test
    #+PROPERTY: board-id 123441297449afd0ed24b27f
    #+PROPERTY: DONE 1234412bbc8922d34689f6c5
    #+PROPERTY: TODO 1234412b5871f56f3c648094
    ...

then C-c o d says everything is ok (and other commands work also).

So... use UPPERCASE!
org-version = 8.2.10

**Comment by ardumont** [comment]
Hello,

> So... use UPPERCASE!

This is new!
Thanks for raising this up.

Cheers,

**Comment by gracjan** [comment]
thx

2015-01-24 21:17 GMT+01:00 Antoine R. Dumont <notifications@github.com>:
