### ISSUE TITLE
bad *ORGTRELLO/CONFIG-FILE* on Windows

### ISSUE THREAD

**Issue by VladimirAlexiev** [org-trello/org-trello#237]
I'm on Windows7, cygwin, and use https://sourceforge.net/projects/emacsbinw64 (25.0.50.1, mingw build).
After installing the keys, when I try org-trello/install-board-metadata, I get this error:
~~~~
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "/.trello/config.el")
  load("c:\\my\\/.trello/config.el")
  orgtrello-controller/load-keys!(nil)
~~~~
I have `~/.trello/config.el` which is also accessible as `c:/my/.trello/config.el` and `c:\my\.trello\config.el` , but not by the name written above. The two slashes `\\/` remove everything before them, so load loogs for `/.trello/config.el` and doesn't find it

The problem is in org-trello-setup.el:
```
(defconst *ORGTRELLO/CONFIG-DIR*
  (concat (getenv "HOME") "/" ".trello"))
```
Why not just use `~/.trello` for this?

PS: excuse me, but the `*STARRED-UPPERCASE*` constant names go against Emacs doctrine.

**Comment by ardumont** [comment]
Hello,

```lisp
(defconst *ORGTRELLO/CONFIG-DIR*
  (concat (getenv "HOME") "/" ".trello"))
```

I believe you can override this with:

```lisp
(defconst *ORGTRELLO/CONFIG-DIR* "~/.trello.el")
```
Then <kbd>M-x eval-buffer</kbd>

`defconst` won't argue with you.
This can be fixed.

> PS: excuse me,

Of course.

>  but the STARRED-UPPERCASE constant names go against Emacs doctrine.

More conventions than doctrine.
Still, unfortunately, I do not know all emacs' yet.

After all, I'm younger than emacs :D so I keep learning by making mistakes...

This is still here because nobody raised any issue before.

So thanks for the heads up!

Cheers,

**Comment by VladimirAlexiev** [comment]
Sure, I worked around it by `(*ORGTRELLO/CONFIG-DIR* "~/.trello.el")`. But you should also fix it.
There are functions for platform-independent messing with directories. But I think it's enough to use "~", you don't need to use `(getenv "HOME")`.

And thanks, I got a bunch of tasks from Trello, but havne't yet tried to sync back.

As for doctrine/convention: sure that's a matter of taste, just that tons of elisp packages don't use the STARRED-UPPERCASE convention.

Cheers!

**Comment by ardumont** [comment]
> Sure, I worked around it by (*ORGTRELLO/CONFIG-DIR* "~/.trello.el"). But you should also fix it.
There are functions for platform-independent messing with directories. But I think it's enough to use "~", you don't need to use (getenv "HOME").

Yes, that's good to know.
I'll fix it.

> And thanks, I got a bunch of tasks from Trello, but havne't yet tried to sync back. A bunch of headings are much easier to read than the Trello UI gimmicks ;-)

That was the all point indeed :D 

> As for doctrine/convention: sure that's a matter of taste, just that tons of elisp packages don't use the STARRED-UPPERCASE convention.

Yes, I've got work to do on conventions, especially this one.

I kept this for `defconst` only though. The `defcustom`, `defvar`, `defun` are not like this.
I think I used it to avoid the auto-complete (or company now) clutter at first... Then I forgot about it.

About conventions, @purcell (see Steve I listen and I'm still thinking about it :) also warned me at least one time about the `/` (not for org-trello) in the function name...
(Trying to compensate the missing namespaces in emacs... at least visually...)

I'll see what I can do about this.

But right now, I still try to understand and squash the other bug I have about comments malformed...
(when I have time...)

Anyway, thanks for raising this up.

Cheers,

**Comment by purcell** [comment]
`(expand-file-name ...)` will generally expand `~` sensibly on all platforms, so `~/.trello.el` may be a good choice.

But the standard place to put these files is in `user-emacs-directory`, since Emacs in general is moving away from packages storing their config files in the home directory. Here's an example, in `desktop.el`:

```el
(defcustom desktop-base-file-name
  (convert-standard-filename ".emacs.desktop")
  "Name of file for Emacs desktop, excluding the directory part."
  :type 'file
  :group 'desktop)

(defcustom desktop-base-lock-name
  (convert-standard-filename ".emacs.desktop.lock")
  "Name of lock file for Emacs desktop, excluding the directory part."
  :type 'file
  :group 'desktop
  :version "22.2")

(defcustom desktop-path (list user-emacs-directory "~")
  "List of directories to search for the desktop file.
The base name of the file is specified in `desktop-base-file-name'."
  :type '(repeat directory)
  :group 'desktop
  :version "23.2")
```

So you might consider a similar scheme.

And yes, the standard [elisp coding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html) are the ones to follow for naming. :-)

**Comment by ardumont** [comment]
> (expand-file-name ...) will generally expand ~ sensibly on all platforms, so ~/.trello.el may be a good choice.

Thanks!

> But the standard place to put these files is in user-emacs-directory, since Emacs in general is moving away from packages storing their config files in the home directory. Here's an example, in desktop.el:

I read something about this somewhere. Thanks for the refresher.

> So you might consider a similar scheme.

Yes, I will.
I just need to think on how to communicate this change to the users (or automate transparently something for the next release which introduce the change...).

> And yes, the standard elisp coding conventions are the ones to follow for naming. :-)

I will create a `make org-trello respect the elisp coding conventions` issue.

As a side node, I refrained from creating https://github.com/ardumont/org2jekyll's melpa recipe as 'oops! I did it again' (regarding the '/' in function names).
Thus avoiding the @purcell's wrath (if it ever existed :)
(I will need to take some time to adapt this and force me to stop using / in names!)

Thanks again for the exchange

Cheers,
