### ISSUE TITLE
Display only tasks when user is assigned?

### ISSUE THREAD

**Issue by Distopico** [org-trello/org-trello#244]
It is possible display tasks by specific user, showing only tasks when user is assigned?

Thanks.

**Comment by ardumont** [comment]
Hello,

sorry for the delay.

> It is possible display tasks by specific user, showing only tasks when user is assigned?

No, it's not.
org-mode does make it possible to create some kind of query to view the buffer differently.
So maybe looking in that direction is worth it.

Cheers,

**Comment by ardumont** [comment]
A hint? http://orgmode.org/worg/org-tutorials/advanced-searching.html
(did not read it fully yet)

**Comment by Distopico** [comment]
Thanks ;)
