### ISSUE TITLE
Trying to sync a card: orgtrello-buffer/compute-marker: Wrong type argument: numberp, nil

### ISSUE THREAD

**Issue by graham-m-dunn** [org-trello/org-trello#245]
I've created a new trello board from my .org file, but when I try to sync a card (exists in the org buffer, but not on trello):

```sh
org-trello - Request 'sync entity with structure to trello...
Loading /Users/gdunn/.trello/config.el (source)...done
Property "orgtrello-local-checksum" deleted
org-trello - Synchronizing card on board 'IT-Test'...
Property "orgtrello-local-checksum" deleted [4 times]
orgtrello-buffer/compute-marker: Wrong type argument: numberp, nil
```
org-trello - version: 0.6.9.3
emacs 25.0.50(9.0) OS X
Org-mode version 8.2.10 (8.2.10-37-gc000e8-elpa @ /Users/gdunn/.emacs.d/elpa/org-20150413/

**Comment by ardumont** [comment]
Hello,

Can you please try and eval this snippet of code on your machine?

```lisp
(orgtrello-buffer/compute-marker "buffername" "some-name" 1234)
```

<kbd>M-x eval-buffer</kbd>

On my side, the result is:
```lisp
"orgtrello-marker-2a0b98e652ce6349a0659a7a8eeb3783ffe9a11a"
```

**Comment by graham-m-dunn** [comment]
Hi,




I eval’d that in scratch after loading org-trello-mode for that buffer. There’s no output (either in scratch or Messages).

**Comment by ardumont** [comment]
Hello,

I have no mac hardware to run this on so I need your help to understand the issue.
Thanks for answering.

Opening the implementation of the function:

```lisp
(defun orgtrello-buffer/compute-marker (buffer-name name position)
  "Compute the orgtrello marker which is composed of BUFFER-NAME, NAME and POSITION."
  (->> (list *ORGTRELLO/MARKER* buffer-name name (if (stringp position) position (int-to-string position)))
    (-interpose "-")
    (apply 'concat)
    sha1
    (concat *ORGTRELLO/MARKER* "-")))
```

As the initial message is in regards of a `numberp` I'd like you to try and evaluate this:

```lisp
(let ((position 1))
  (if (stringp position) position (int-to-string position)))
;; "1"

(let ((position "20"))
  (if (stringp position) position (int-to-string position)))
;; "20"
```

In comments (after ;;), the results on my side.

...
This should be ok. Even on your side.
...

Ok.
I reproduced your initial error with `position` form to nil: 

```lisp
(int-to-string nil)
```
Does trigger the error about `numberp`.

Can you show me the content of your buffer please?

Thanks

Cheers,

**Comment by graham-m-dunn** [comment]
Hi,

I don't get any output from your example:

(pasted into a new file -- test.el, then M-x eval-buffer)

(let ((position 1))
   (if (stringp position) position (int-to-string position)))
 ;; "1"

 (let ((position "20"))
   (if (stringp position) position (int-to-string position)))
 ;; "20"

I tested (message "hi"), and can see "hi" in Messages)

M-x eval-buffer on 

(int-to-string nil)

results in 

eval-buffer: Wrong type argument: numberp, nil

**Comment by ardumont** [comment]
> I don't get any output from your example:

That is strange.
Can you eval this in another way, please?

Place your caret just after the last parenthesis and <kbd>M-x eval-last-sexp</kbd>.
The result should appear in the minibuffer (bottom left corner of emacs by default).

Thanks.

> Can you show me the content of your buffer please?

Also, I'm still interested by a basic and anonymous extract of your org-trello buffer.

Cheers,

**Comment by graham-m-dunn** [comment]
That’s working better (M-x eval-last-sexp)




It returns “1” for the first expression, but enters the lisp debugger for the second:





Debugger entered--Lisp error: (void-variable “20”)

  (let ((position “20”)) (if (stringp position) position (int-to-string position)))

  eval((let ((position “20”)) (if (stringp position) position (int-to-string position))) nil)

  elisp--eval-last-sexp(nil)

  eval-last-sexp(nil)

  funcall-interactively(eval-last-sexp nil)

  call-interactively(eval-last-sexp nil nil)

  command-execute(eval-last-sexp)




My current org buffer is very messy, I may just start with a trello->org sync and add in items to org, and try and sync them back up.




Thanks,

Graham

**Comment by GeorgeGo** [comment]
I'm using the same software versions as graham and I have this issue when I try to perform my first sync between org and trello. I also really appreciate your work on this project ardumont.

**Comment by ardumont** [comment]
Hello,

> I'm using the same software versions as graham and I have this issue when I try to perform my first sync between org and trello. 

I unfortunately do not know how to help without a buffer extract for one :D 
I asked a couple of times for that but got no response (thus the tag `need-feedback`)

Also, as I'm alone I cannot deal with multiple versions... (0.6.9.3 is old...)
So I'm releasing `quite often` (not lately because life gets in the way :)

To sum up, it would be a good idea to take the latest version (0.6.9.6).
I cannot guarantee it will work (since i do not get the error in the first place).
But at least, I can try rapidly from the current version.

> I also really appreciate your work on this project ardumont.

Thanks!
I'm happy people find this useful :D

Cheers,

**Comment by graham-m-dunn** [comment]
I found that starting with a blank org file and sync'd from trello worked.

**Comment by GeorgeGo** [comment]
So I updated to the most recent version of org-trello on melpa. Then I used a blank org file to sync from a fresh trello page. It worked when I used a 1st tier task (ex: * TODO Write task), but threw a "Wrong type argument: integer-or-marker-p, nil" error when I made a 2nd tier task (ex: ** TODO Use Arial)

**Comment by ardumont** [comment]
Hello all,

> I found that starting with a blank org file and sync'd from trello worked.

Thanks for the feedback!

> So I updated to the most recent version of org-trello on melpa. Then I used a blank org file to sync from a fresh trello page. It worked when I used a 1st tier task (ex: * TODO Write task), 

Ok.

> but threw a "Wrong type argument: integer-or-marker-p, nil" error when I made a 2nd tier task (ex: ** TODO Use Arial)

Aha! The culprit `**` shows its face!

Ok, don't use `**`. 
org-trello no longer supports heading superior to one - #254, #258.

The `**` is used for card comment.

My video demos needs to be refreshed #136.
(I will add a disclaimer on the main site at least to demo the actual format)

The org-trello format can be spotted http://org-trello.github.io/usage.html...

Sorry for the deprecated information.

Cheers,
