### ISSUE TITLE
Not listed on Melpa?

### ISSUE THREAD

**Issue by fullofcaffeine** [org-trello/org-trello#247]
I was using an old version from Marmelade, but looks like org-trello is not listed on Melpa nor Melpa-stable, here's the list fetched by ```package-list-packages``` for Melpa:

http://pastie.org/10090647

Why?

**Comment by fullofcaffeine** [comment]
Nevermind, looks like I was pointing to an old endpoint.

**Comment by ardumont** [comment]
Hello,

for future references:

- unstable - http://melpa.org/#/org-trello
- stable - http://stable.melpa.org/#/org-trello

Cheers,
