### ISSUE TITLE
Installing from melpa (unstable) works, but then it errs on an undefined variable "error-messages"

### ISSUE THREAD

**Issue by fullofcaffeine** [org-trello/org-trello#248]
You can see the warnings when installing below:

```
Compiling file /Users/fullofcaffeine/.emacs.d/elpa/find-file-in-project-20141214.1952/find-file-in-project-pkg.el at Mon Apr 13 17:04:37 2015
Entering directory `/Users/fullofcaffeine/.emacs.d/elpa/find-file-in-project-20141214.1952/'

Compiling file /Users/fullofcaffeine/.emacs.d/elpa/find-file-in-project-20141214.1952/find-file-in-project.el at Mon Apr 13 17:04:37 2015
find-file-in-project.el:64:1:Warning: cl package required at runtime
find-file-in-project.el:1:1:Error: End of file during parsing

Compiling no file at Mon Apr 13 17:04:47 2015
Leaving directory `/Users/fullofcaffeine/.emacs.d/elpa/cl-generic-0.2'

Compiling file /Users/fullofcaffeine/.emacs.d/elpa/cl-generic-0.2/cl-generic-pkg.el at Mon Apr 13 17:04:48 2015
Entering directory `/Users/fullofcaffeine/.emacs.d/elpa/cl-generic-0.2/'

Compiling file /Users/fullofcaffeine/.emacs.d/elpa/cl-generic-0.2/cl-generic.el at Mon Apr 13 17:04:48 2015
```

And the error when trying to ```org-trello/install-board-metadata```:
```
orgtrello-action/controls-or-actions-then-do: Symbol's function definition is void: error-messages
evil-move-beginning: Beginning of buffer
Mark set
```

I tried using the stable branch of Melpa, but  the version of ```request-deferred```required by org-trello is not present, so it doesn't install.

Any help appreciated!

**Comment by ardumont** [comment]
> I tried using the stable branch of Melpa, but the version of request-deferredrequired by org-trello is not present, so it doesn't install.

You cannot indeed, sorry about that.
I upgraded back this `request-deferred` dependency (knowning the tag was not put on that repository thus no stable version).
The difference between the stable and the other is simply the dependencies.

**Comment by ardumont** [comment]
I did not have time to finish answering...

**Comment by ardumont** [comment]
Hello,

> You can see the warnings when installing below:
> 
>     Compiling file /Users/fullofcaffeine/.emacs.d/elpa/find-file-in-project-20141214.1952/find-file-in-project-pkg.el at Mon Apr 13 17:04:37 2015
>     Entering directory `/Users/fullofcaffeine/.emacs.d/elpa/find-file-in-project-20141214.1952/'
> 
>     Compiling file /Users/fullofcaffeine/.emacs.d/elpa/find-file-in-project-20141214.1952/find-file-in-project.el at Mon Apr 13 17:04:37 2015
>     find-file-in-project.el:64:1:Warning: cl package required at runtime
>     find-file-in-project.el:1:1:Error: End of file during parsing
>     
>     Compiling no file at Mon Apr 13 17:04:47 2015
>     Leaving directory `/Users/fullofcaffeine/.emacs.d/elpa/cl-generic-0.2'
>     
>     Compiling file /Users/fullofcaffeine/.emacs.d/elpa/cl-generic-0.2/cl-generic-pkg.el at Mon Apr 13 17:04:48 2015
>     Entering directory `/Users/fullofcaffeine/.emacs.d/elpa/cl-generic-0.2/'
>     
>     Compiling file /Users/fullofcaffeine/.emacs.d/elpa/cl-generic-0.2/cl-generic.el at Mon Apr 13 17:04:48 2015
> 
> And the error when trying to org-trello/install-board-metadata:
> 
>     orgtrello-action/controls-or-actions-then-do: Symbol's function definition is void: error-messages
>     evil-move-beginning: Beginning of buffer
>     Mark set

Looks like there is an issue with the `dash` dependencies installation.
The symbol `error-message` is a form used in an `-if-let` (which is a dash macro).

```sh
./org-trello-action.el:32:      (-if-let (error-messages (-> control-or-action-fns orgtrello-action/--execute-controls orgtrello-action/--filter-error-messages))
./org-trello-action.el:35:            (orgtrello-log/msg *OT/ERROR* "List of errors:\n %s" (orgtrello-action/--compute-error-message error-messages)))
./org-trello-action.el:46:      (-if-let (error-messages (-> control-fns (orgtrello-action/--execute-controls entity) orgtrello-action/--filter-error-messages))
```

Please, try to ensure dash is installed on your machine and retry.
Drop this in your scratch buffer and eval it:
```lisp
(require 'dash)
```
<kbd>M-x eval-buffer</kbd>

Cheers,

**Comment by ardumont** [comment]
I should mention that `dash` should be installed by the package as dash is a defined dependencies of org-trello.
