### ISSUE TITLE
Automatically enable org-trello for .trello files

### ISSUE THREAD

**Issue by wesleyhall** [org-trello/org-trello#249]
Hey folks, 

Wondering if the above is possible. It might just be some elisp but maybe somebody can help me with it. 

I have seen the variable for setting a list of fixed filenames, but it seems to me to make more sense to configure a file extension to use for trello board files.

**Comment by ardumont** [comment]
Hello,

It's a good idea.

I tried and failed multiple times (at least twice :).

The implementation I tried was to use the `auto-mode-alist` variable.
But as org-trello is a minor-mode and not a major-mode, I failed.

(unfortunately, I do not seem to find my old tryouts...)

Here is an example of value for such form:
```lisp
(("\\.html" . web-mode)
 ("\\.stumpwmrc$" . stumpwm-mode)
 (".todo$" . org-mode)
 (".org$" . org-mode))
```

`auto-mode-alist` docstring extract:
```lisp
auto-mode-alist is a variable defined in `files.el'.
Its value is shown below.

  This variable may be risky if used as a file-local variable.

Documentation:
Alist of filename patterns vs corresponding major mode functions.
Each element looks like (REGEXP . FUNCTION) or (REGEXP FUNCTION NON-NIL).
(NON-NIL stands for anything that is not nil; the value does not matter.)
Visiting a file whose name matches REGEXP specifies FUNCTION as the
mode function to use.  FUNCTION will be called, unless it is nil.

If the element has the form (REGEXP FUNCTION NON-NIL), then after
calling FUNCTION (if it's not nil), we delete the suffix that matched
REGEXP and search the list again for another match.

The extensions whose FUNCTION is `archive-mode' should also
appear in `auto-coding-alist' with `no-conversion' coding system.

See also `interpreter-mode-alist', which detects executable script modes
based on the interpreters they specify to run,
and `magic-mode-alist', which determines modes based on file contents.
...
```

Still I wonder if using this + an org-mode-hook function (which checks again the extension of the current file for ".trello") wouldn't do the trick.

...
trying something
...

Something along those lines:

```lisp
;; org-trello major mode for all .trello files
(add-to-list 'auto-mode-alist '("\\.trello$" . org-mode))

;; add a hook function to check if this is trello file, then activate the org-trello minor mode. 
(add-hook 'org-mode-hook
          (lambda ()
            (when (string= "trello" (file-name-extension (buffer-file-name (current-buffer))))
              (org-trello-mode)))) 
```

should do it (I tried and it went ok for me).

To test it, dump this in a *scratch* buffer and <kbd>M-x eval-buffer</kbd>.
Now create a `.trello` file and open it.
Now org-mode and org-trello-mode should be activated.

To make this persistent, you could add this to your ~/.emacs/init.el`.

If someone has a better/simpler idea, I'm all for it :D

Cheers,

**Comment by wesleyhall** [comment]
Thanks for this. I really need to start studying emacs lisp. 

This does set the mode correctly but I get some errors when trying to do certain things (like syncing down from the trello board). 

org-trello - Sync buffer from trello - Catch error: (wrong-type-argument stringp nil)

I am not sure exactly how the mode-hooks works but buffer-file-name will return nil when the buffer isn't associated with a file. 

Changing buffer-file-name to buffer-name seems to work, but being almost totally unfamiliar with elisp I am not sure if this is sensible or not.

**Comment by ardumont** [comment]
> Thanks for this.

No problem.

> I really need to start studying emacs lisp.

It's definitely a good idea.
A nice introduction in the land of lisps :D 

> This does set the mode correctly but I get some errors when trying to do certain things (like syncing down from the trello board).

> org-trello - Sync buffer from trello - Catch error: (wrong-type-argument stringp nil)

You need to have the buffer/file configured to work with a trello board first.
If you try to sync without this first step, this won't work :D 

> I am not sure exactly how the mode-hooks works

It simply ran at org-mode's startup time.
You can add yours (as we did) to the major mode (here org-mode)'s hooks list.
Every mode (even minor ones) defines those.
Emacs's convention is `mode-name`-hook

> but buffer-file-name will return nil when the buffer isn't associated with a file.

Indeed, your need only mentioned file so I provided code that do manipulate file.
If you don't associate the buffer with a filename, this snippet won't work.

> Changing buffer-file-name to buffer-name seems to work, but being almost totally unfamiliar with elisp I am not sure if this is sensible or not. 

Sure, I provided you with some bootstrap code.
Feel free to improve or change it as you will :D 

`buffer-name` is the buffer's name.
A buffer is not necessarily a file on disk.

`buffer-file-name` does indeed returns nil if the buffer is not associated with any file on disk.

An improvment on the first proposed code is:

```lisp
(add-hook 'org-mode-hook
          (lambda ()
            (let ((filename (buffer-file-name (current-buffer))))
              (when (and filename (string= "trello" (file-name-extension filename)))
                (org-trello-mode)))))
``` 

This way, you make sure the buffer is associated with a file before checking its extension.
If not, this does not trigger the org-trello-mode activation (nor any other error).

Cheers,

**Comment by wesleyhall** [comment]
Thanks Antoine.

I actually do most of my development in clojure these days so some degree of familiarity with lisps, just not elisp (which doesn't appear to be substantially different), and of course there is the emacs api, which seems fairly weighty :). 

The problem I am describing (which also seems to be a problem with the new revision you provide), actually occurs when working with actual persistent files. 

Effectively, I paste the code into my emacs config and restart, I then open a file called TODO.trello in my documents directory and issue the command C-u C-c o s, in order to sync from trello (the file has been previously configured with a board). I then get the error described. Changing from buffer-file-name to buffer-name in both instances appears to fix the problem. 

When I put "(message (buffer-name (current-buffer)))" in the lambda, I get repeated outputs of "*temp*" to the *messages* buffer, so presumably what is happening somewhere the synchronisation process is creating temporary buffers in org mode which is triggering the hook and because these buffers have no filename, is causing the error.

**Comment by wesleyhall** [comment]
Apologises, the new one does work, I must have 'mis-tested' ;).

**Comment by ardumont** [comment]
> I actually do most of my development in clojure 

Yeah! This was my introduction to the land of lisp actually :D 

Then in emacs-lisp, what you'll first miss is the namespaces... (none) and then the destructuring.

For the rest, you can add `dash` and `dash-functional` and you'll have mostly the feel of clojure within emacs-lisp.

> Apologies, the new one does work, 

Great news!

> I must have 'mis-tested' ;). 

No worries!
Entropy happens! :D 

Cheers,

**Comment by ardumont** [comment]
Thanks for raising this up.

[I referenced this possibility on the main site](http://org-trello.github.io/usage.html#automatic-org-trello-files-in-emacs).

Cheers,

**Comment by grokful** [comment]
In case that's useful to anyone, here's what I have:

```lisp
    (defun my/org-mode-hook-org-trello-mode ()
      (when (and (buffer-file-name)
                 (string-match "\\.trello.org$" (buffer-file-name)))
          (message "Turning on org-trello in %s" (buffer-file-name))
          (org-trello-mode)))
    (add-hook 'org-mode-hook #'my/org-mode-hook-org-trello-mode)
```

I then use ".trello.org" as the full extension for trello boards, and simply ".org" for everything else.

**Comment by ardumont** [comment]
@grokful Thanks!
