### ISSUE TITLE
Doesn't work well with Evil

### ISSUE THREAD

**Issue by erahhal** [org-trello/org-trello#251]
Example:

With standard emacs keybindings, ctrl-e takes you to the end of the visible line, but not past the metadata, so you can insert text without corrupting anything.

In Evil mode, if you type "A" to add to the end of the line, it will add past the metadata, breaking the structure of the file.

**Comment by ardumont** [comment]
Hello,

If memory serves, `evil-mode` is a mode for vi(m) binding. Feel free to correct me :D 

To avoid the behavior you describe, `org-trello` indeed remaps the standard `C-e` binding (bound to `org-end-of-line` in `org-mode` and rebound to `orgtrello-buffer/end-of-line!` in `org-trello` minor mode) 

`evil-mode` in `org-mode` buffer might not redefine the 'A' to `org-end-of-line`.
Thus having this behavior you describe.

You may have to add something like that in your org-mode setup:

```lisp
(define-key org-mode-map (kbd "A") 'org-end-of-line)
```

Note: I do not know if `evil-mode` requires some specific setup regarding binding... 
So please try to adapt this for `evil-mode`.

The goal is to make the equivalent of org-mode's default setup (so make `A` work the same as `C-e`). [Then org-trello should take it from there](https://github.com/org-trello/org-trello/blob/master/org-trello.el#L354).

Cheers,

**Comment by skrat** [comment]
Likewise, `C-u` is take by evil mode and so the pull versions don't work. I tried to eval `(org-trello/sync-buffer t)` from minibufer, but it raises some error.

**Comment by ardumont** [comment]
> Likewise, C-u is taken by evil mode and so the pull versions don't work. I tried to eval (org-trello/sync-buffer t) from minibufer, but it raises some error.

I'm not sure this way will work.
The org-trello interactive command are contextual.

For C-u, I'm not sure how to avoid this.
Also, I'm not sure this is the right thing for a minor-mode to override such an elementary binding (C-u)...

To make sure you do have only the problem with org-trello, can you deactivate evil and the <kbd>C-u M-x sync-buffer</kbd>.

After this, if you still have the problem.
A small and anonymised buffer extract would be nice.

Cheers,

**Comment by erahhal** [comment]
Hi ardumont, I ended up solving this with the following:

```
  (evil-define-key 'normal org-mode-map "A" (lambda ()                                                               
                                              (interactive)                                                          
                                              (orgtrello-buffer/end-of-line!)                                        
                                              (evil-insert-state)))
```

I just starting learning Emacs/Lisp, so please excuse me if this code is poorly written.  I tried using org-end-of-line and it didn't work, instead going past the metadata.

Skrat, I'm using Spacemacs, which maps Spc-U to the universal argument (C-u), which you can use in place of C-u.  If you aren't using Spacemacs, just map something to the universal argument if it isn't already mapped to something else by vanilla Evil.

**Comment by ardumont** [comment]
@erahhal Thanks for sharing your insight. It's all the more appreciated because I do not know those modes at all and was a loss for answers!

@skrat Does this or my previous answer to you solve your problem?

Cheers,

**Comment by skrat** [comment]
@ardumont  Yes it seems so, `Spc-U` seems to be doing the right thing. I can see a message saying ...borad XY is being synchronized to org-mode file.... but once that messages disappears, the file is the same as before, holding just the board metadata.

**Comment by ardumont** [comment]
For me, we can close this issue as the encountered behaviour is something else which needs its own discussion thread.

@skrat Can you please open another issue detailing the behaviour you encounter?

Thanks.

Cheers,
