### ISSUE TITLE
Initial sync-buffer fails, "Wrong type argument: integer-or-marker-p, nil"

### ISSUE THREAD

**Issue by cjp** [org-trello/org-trello#258]
I'm getting a "Wrong type argument: integer-or-marker-p, nil" when doing the initial org-trello/sync-buffer.

*Messages* shows:

```
org-trello - Request 'sync org buffer from trello board'...
Loading /Users/cjp/.trello/config.el (source)...done
org-trello - Synchronizing the trello board 'Testorg' to the org-mode file...
Property "orgtrello-local-checksum" deleted [8 times]
org-trello - Sync buffer from trello - Catch error: (wrong-type-argument integer-or-marker-p nil)
```

Here's my test buffer. This has happened to my other (arguably much more complex) buffers.

```org
:PROPERTIES:
#+PROPERTY: board-name Testorg
#+PROPERTY: board-id 5550e2394a1e5cbd41bc1997
#+PROPERTY: CANCELED 5550e23b9ebd9161fe4b31de
#+PROPERTY: DONE 5550e23a7fdfc4743179b81a
#+PROPERTY: IN-PROGRESS 5550e23ab2a66a62870e6932
#+PROPERTY: WAIT 5550e23af08159a706173319
#+PROPERTY: TODO 5550e23a8487cfce607c0c2b
#+TODO: TODO WAIT IN-PROGRESS | DONE CANCELED 
#+PROPERTY: orgtrello-user-cpilking 5436a831b40e6db5049de930
#+PROPERTY: :green 
#+PROPERTY: :yellow 
#+PROPERTY: :orange 
#+PROPERTY: :red 
#+PROPERTY: :purple 
#+PROPERTY: :blue 
#+PROPERTY: orgtrello-user-me cpilking
:END:
#+TITLE: Test org buffer
#+AUTHOR: Christopher J. Pilkington

* Develop the plan
:PROPERTIES:
:orgtrello-id: orgtrello-marker-3c751597a03b3f33f77f2dab5083cb44e70079e3
:END:
** IN-PROGRESS Determine resources
:PROPERTIES:
:orgtrello-id: orgtrello-marker-79679a2589255afe5c926abd93fd48ee72097785
:END:

Alice might want in, but Bob will only join if she's involved.
Mallory is trying to get on board also, but unsure if she can be
trusted to work with Alice and Bob.

** TODO Get funding
- [ ] Talk to boss
- [ ] Beg management :PROPERTIES: {"orgtrello-id":"orgtrello-marker-9428a1128e98a2a8626f3b807bdb021c4f5e820c"}
** TODO Develop schedule

* TODO Execute plan

```

Using GNU Emacs 24.4.1 (x86_64-apple-darwin14.1.0, NS apple-appkit-1344.72), with the builitin org
org-trello 20150509.627

**Comment by ardumont** [comment]
Hello,

Thanks for the neat issue :D 

Do not use ** heading, it's used only for comments #254.

Org-trello now uses org's checkbox system for trello checklist and trello items.
It used to use `**` for checkbox and `***` for items, as in the video tutorials (which need to be updated #136).

Cheers,

**Comment by cjp** [comment]
Ok, after flattening the outline levels, the sync works correctly.

The documentation should make it clear that org-trello is a *subset* of org; that standard org files are not necessarily compatible.

**Comment by ardumont** [comment]
> Ok, after flattening the outline levels, the sync works correctly.

Cool.

> The documentation should make it clear that org-trello is a subset of org; that standard org files are not necessarily compatible.

Yeah! I mentioned it here http://org-trello.github.io/install.html#load-org-trello.
But this seems to be not in the right place nor enough.

I admit that the org subset was not my original intent and it was not at first.
Then cames a bunch of evolutions (org checkboxes, then comments, etc....) and along the way, the compatibility got lost.

It's quite complicated to have the necessary data for org-trello without breaking anything in org.

Anyway, thanks for the heads up!

Cheers,

**Comment by cjp** [comment]
Yes, I agree org-trello is an incredible challenge. You have my thanks.

I really wish the hierarchy could minimally collapse down, i.e., treat *, ** and *** the same, rather than failing ungracefully. It would be super to be able to take a project planned in org, drop it into trello, and have it reasonably usable.

**Comment by ardumont** [comment]
> I really wish the hierarchy could minimally collapse down, i.e., treat , * and *** the same, rather than failing ungracefully. It would be super to be able to take a project planned in org, drop it into trello, and have it reasonably usable.

Yes, I agree.

It could be an issue to open.
I do not know when I'll find the time but still, it could be worth mentionning it.
Who knows, maybe somebody will drop by and propose some code :D 

Cheers,
