### ISSUE TITLE
First posting here -three problems - from an email

### ISSUE THREAD

**Issue by boudiccas** [org-trello/org-trello#260]
This is an example of what I'm seeing
```
* Doing- test-pad
:PROPERTIES:
:orgtrello-id: 555a24b76d992c82948e0241
:orgtrello-local-checksum: c4aa326c729dc2433dd2f478ffbd7008c3fb6a0764e64a5b929aaa70ea306154
:END:
- [ ] test one
- [ ] first-level
  - [ ] test 2
 :PROPERTIES: {"orgtrello-id":"555a24b898d87fc61780cca5","orgtrello-local-checksum":"d942325cf2b6e203fdd75f7702d82eedc98c3730f8a2eeb298e734433bc6c877"}
  - [ ] second level
:PROPERTIES: {"orgtrello-id":"555a24b8bff7736f0519f1e1","orgtrello-local-checksum":"2c790f2367816851363afafec0df46c959bb979510ed68e6dcfe17eac24d4dbc"}
```
This is on emacs 24.5.50.1, org-mode 8.2.10, from uptodate git, org-trello 0.6.9.5. 

This is how it is in my auth.org (my emacs init file)
```
** TODO Org and Trello
  Using [[https://github.com/org-trello/org-trello][org-trello]] to sync particular org-mode files with [[https://trello.com/b/Kp6XZg2b][trello.com]]
Needs setting up properly.
#+BEGIN_SRC elisp
    (defun sk/org-trello-sync ()
      (interactive)
      (when (require 'org-trello nil t)
        (org-trello-mode 1)
        (org-trello/sync-buffer t)))

(custom-set-variables '(org-trello-files '("~/.emacs.d/org/trello1.org" "~/.emacs.d/org/trello2.org")))
(global-set-key (kbd "S-<f1>") 'sk/org-trello-sync)
#+END_SRC
[2015-05-01 Fri 15:04]
```
Oh, and by the way, none of the keybindings work!

**Comment by ardumont** [comment]
Hello,

First, thanks for getting back to me this quick with details.

I need some time to investigate (no time right now, need to go).

But there is indeed some trouble I can see.
Your buffer should look like more:

```org
* Doing- test-pad
:PROPERTIES:
:orgtrello-id: 555a24b76d992c82948e0241
:orgtrello-local-checksum: c4aa326c729dc2433dd2f478ffbd7008c3fb6a0764e64a5b929aaa70ea306154
:END:
  - [ ] test one
  - [ ] first-level
    - [ ] test 2 :PROPERTIES: {"orgtrello-id":"555a24b898d87fc61780cca5","orgtrello-local-checksum":"d942325cf2b6e203fdd75f7702d82eedc98c3730f8a2eeb298e734433bc6c877"}
    - [ ] second level :PROPERTIES: {"orgtrello-id":"555a24b8bff7736f0519f1e1","orgtrello-local-checksum":"2c790f2367816851363afafec0df46c959bb979510ed68e6dcfe17eac24d4dbc"}
```

That is:
- indentation at level 2 for the checkbox that represents trello checklists.
- indentation at level 4 for the checkbox that represents trello items.

As a note, the `:PROPERTIES:` for the checkboxes should be invisible when org-trello is activated.

I guess the sample `auth.org` you are using is a literate programming effort to document and execute your emacs-lisp init file? (I did not yet use my emacs that way so never tested it that way).

For my culture, do you have something online that I could check out?

> Oh, and by the way, none of the keybindings work!

This is strange.

Do you have your *Compile-Log* buffer (this is the package install buffer) somewhere (with the org-trello install that is)?

Cheers,
