### ISSUE TITLE
Colors broken in org trello

### ISSUE THREAD

**Issue by pschorf** [org-trello/org-trello#263]
Whenever the org-trello minor mode is active, the org mode colors I have don't work. For instance, if I load a file without org-trello, the file is highlighted correctly. Any changes I make, like adding a new line, changing a deadline, etc. are not correctly highlighted. If I load a file with org-trello enabled, nothing is highlighted correctly. I believe I'm using the latest version, 20150509.

**Comment by ardumont** [comment]
Hello,

Can you please provide some more information?
- org-mode version (<kbd>M-x org-version</kbd>)
- emacs version (<kbd>M-x emacs-version</kbd>)
- org-trello version (<kbd>M-x org-trello/version</kbd>)
- an extract of your anonymised org-buffer (which does reproduce your problem)?

Can you also please explain to me what you mean by colors? (Screenshots before/after would be nice if you can... Drag'n drop inside the textarea, gh magic will do the rest).

Cheers,

**Comment by pschorf** [comment]
Sure:
- org-version: Org-mode version 7.9.3f (release_7.9.3f-17-g7524ef @ /usr/share/emacs/24.3/lisp/org/) 
- emacs-version: GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian
- org-trello version: org-trello - version: 0.6.9.5

Here's normal org mode (org-trello disabled)
![colors](https://cloud.githubusercontent.com/assets/88803/7789973/00cc02b8-023a-11e5-8268-cb675d9e8f53.png)
Here's after adding one card with org-trello active
![colors-partial](https://cloud.githubusercontent.com/assets/88803/7789974/00d638d2-023a-11e5-8a76-458408312281.png)
Here's what it looks like if org-trello starts on load.
![nocolors](https://cloud.githubusercontent.com/assets/88803/7789975/00db94ee-023a-11e5-899b-a10ff6df704d.png)

Does that help?

**Comment by ardumont** [comment]
Hello,
> I believe I'm using the latest version, 20150509.

0.6.9.5 is not the latest.
Still, I don't think this will help in this matter.

>  Does that help?

Yes!
I mean it triggers some other questions now.

- What do you do between the 3rd screenshot and the 2nd one to have the colors back again?
- As a curiosity, what's the date between square brackets?

Cheers,
