### ISSUE TITLE
initial sync buffer, setup problem

### ISSUE THREAD

**Issue by llj098** [org-trello/org-trello#269]
Hi,

Version: org-trello 0.7.0, steps:

1. org-trello-install-key-and-token success
2. org-trello-install-board-metadata success
3. org-trello-sync-buffer fail, error:

```
You can run the command `org-trello-sync-buffer' with C-c o s
org-trello - List of errors:
 - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token
```

1. retry org-trello-install-key-and-token, result:  `already existing, skipping`
2. org-trello-sync-buffer still the same error

Is it a bug?

**Comment by llj098** [comment]
Versions:

Org-mode version 8.2.10 (8.2.10-41-g42228a-elpa @ /Users/lj/.emacs.d/elpa/org-20150622/)
GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-06-12 on LJMBP.local

**Comment by ardumont** [comment]
Hello @llj098,

> Is it a bug?

Possibly!

Some questions:

- Can you please show me your anonymised buffer including the properties part?

- In iterm (or any other terminal), what does `ls ~/.emacs.d/.trello` returns you?

- Is it your first org-trello tryout?

Thanks for your feedback,

Cheers,

**Comment by Bregor** [comment]
Same issue here.

What properties do you need?

    $ ls ~/.emacs.d/.trello
    bregor@evilmartians.com.el

For me it is first tryout, yes.

Thanks in advance!

**Comment by Bregor** [comment]
Just in case:

- org-trello - version: 0.7.0
- GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-04-12 on alais.local
- Org-mode version 8.3beta (release_8.3beta-1231-ga0a883 @ /Users/bregor/.emacs.d/el-get/org-mode/lisp/)

**Comment by ardumont** [comment]
Hello,

> For me it is first tryout, yes.

Thanks.
I asked because old user will have their setup transparently changed.
New user will depend on their input in the install key and token phase.

> What properties do you need?

Specifically 
```
#+PROPERTY: orgtrello-user-me <trello-login>
```
It is the trello login.

For me it's `ardumont` and it must match the configuration file on disk `~/.emacs.d/.trello/ardumont.el`.

> bregor@evilmartians.com.el

And what's your trello login?

Please, adapt your configuration filename with your trello login and give it another try.

Cheers,

**Comment by Bregor** [comment]
Hell, yeah!
When used email as login, property `orgtrello-user-me` was `nil`.

So, I removed `~/.emacs.d/.trello/bregor@evilmartians.com.el` and used `bregor` as login.
Now it seems to be OK.

Thank you!

P.S. is it possible to "download" trello board to org file?

**Comment by ardumont** [comment]
> Hell, yeah!

\o/

> When used email as login, property orgtrello-user-me was nil.

That's not good indeed.

> So, I removed ~/.emacs.d/.trello/bregor@evilmartians.com.el and used bregor as login.

Simply renaming would have been good I think.

```sh
mv ~/.emacs.d/.trello/bregor@evilmartians.com.el ~/emacs.d/.trello/bregor.el
```
> Now it seems to be OK.
> Thank you!

Thanks for getting back to me :D 

> P.S. is it possible to "download" trello board to org file?

That would be: <kbd>C-u M-x org-trello-sync-buffer</kbd>
(http://org-trello.github.io/quick-start.html)

Cheers,

**Comment by ardumont** [comment]
@llj098 Does this solve your problem too?

Cheers,

**Comment by llj098** [comment]
Hi @ardumont , I rename `liulijin@feinno.com.el` to `liulijin.el` , error disappears, when I try org-trello-sync-buffer, I got:  `org-trello - No card(s) to sync.`  But there are more than 20 cards in that board.

Is it a bug or did I do something wrong ?

Thanks very much.

**Comment by Bregor** [comment]
@llj098 without unuiversal argument `org-trello-sync-buffer` will sync org-file to trello.
For synchronization from trello to org you need `C-u M-x org-trello-sync-buffer`.

**Comment by Bregor** [comment]
Or `C-u C-c o s`

**Comment by ardumont** [comment]
> @llj098 without unuversal argument org-trello-sync-buffer will sync org-file to trello.
For synchronization from trello to org you need C-u M-x org-trello-sync-buffer.

> Or C-u C-c o s

Exactly :D

**Comment by llj098** [comment]
@ardumont  Works like charm, thank you very much for your excellent support!

**Comment by ardumont** [comment]
Great news!

Have a nice day.

Cheers,

**Comment by devogon** [comment]
For what it's worth, I had an initial sync problem as well. Logged in with email address, but had to change the filename from email@address.net.el to username.el to make it all work.

**Comment by ardumont** [comment]
Hello,

> For what it's worth, 

All user feedback is worth it :D 
Thanks for it.

> I had an initial sync problem as well. Logged in with email address, but had to change the filename from email@address.net.el to username.el to make it all work. (username is different in my case 

I'm not sure I understood your sentence.

> ok never mind that. 

Lol, you mean I can dismiss the first sentence I did not understand, right?

> now i get "nil" on org-trello-user-me and i've got to change that manually...

That's definitely a bug.
If you have time to describe the steps you followed, it would be nice!
Thanks anyway.

Also, you could try <kbd>M-x org-trello/update-board-metadata</kbd>
It's a command to update the board information, e.g. if someone new is attached to the board.
But it could be tried in this case (I have a reasonable doubt about the `orgtrello-user-me nil` situation though...)

Cheers,

Thanks for your feedback and for trying to make it work nonetheless!

Cheers,

**Comment by mprokopov** [comment]
i've managed to get into the same issue. 

Fixed with renaming credentials from email to user id.

In my case I renamed ~/.emacs.d/.trello/nexus@it-premium.com.ua.el to ~/.emacs.d/.trello/nexus2.el, which was mentioned in board metadata property "orgtrello-user-me".

Thanks!

**Comment by unhammer** [comment]
Perhaps this should go in the docs on https://org-trello.github.io/trello-setup.html ? I had the same problem, took a while to find this discussion.

**Comment by unhammer** [comment]
Also, trello allows changing usernames …

**Comment by ardumont** [comment]
> Perhaps this should go in the docs on https://org-trello.github.io/trello-setup.html ? I had the same problem, took a while to find this discussion.

Indeed.

I thought i did https://org-trello.github.io/migration.html#0-7-0

But now i realize this is clearly not enough... way too much implicit :D 

> Also, trello allows changing usernames …

You can still change your name in trello and then you should adequately change manually the configuration file.

Thanks for the heads up.

Cheers,

**Comment by wmmurrah** [comment]
I am having a similar, but more basic problem (I think). I have the package installed and my .trello/username.el file correctly named. but when do C-c o I, I get:

     Board to install (TAB to complete): [No match]

It seems that org mode can't find my trello account. I have checked the key and the token, which I think are correct. I cannot create a board from org either. When I create a board I get the metadata but is seems incomplete.
after C-c o b the metadata is:

     :PROPERTIES:
     #+PROPERTY: board-name 
     #+PROPERTY: board-id 

     #+PROPERTY: orgtrello-user-me williammurrah
     :END:

But no board is created 

If I try to push to a card I get a setup error. I have checked that my list names and todos match
Any ideas what is going on?

**Comment by ardumont** [comment]
Hello,

@wmmurrah 

Sorry for the late reply, was out of reliable 

Can you please open a new issue?
Just open a new one with the copy/paste of what you already typed here.
Also, please, add the result of <kbd>M-x org-trello-bug-report</kbd> as introduction.

Thanks,

Cheers,
