### ISSUE TITLE
Sync buffer from trello - Catch error: (error "Not in an item")

### ISSUE THREAD

**Issue by Bregor** [org-trello/org-trello#270]
Hello again!

Synchronization of one of boards fails with catch error.
Due to \*Messages\* synchronization stops in the middle of card with partly completed checklist.

Cards without checklist and with fully completed checklists are synchronizing normally. 

Can I turn on something like debug for more precise investigation?

**Comment by ardumont** [comment]
Hello,

> Synchronization of one of boards fails with catch error.
> Due to *Messages* synchronization stops in the middle of card with partly completed checklist.

I do not understand this sentence.

> Cards without checklist and with fully completed checklists are synchronizing normally. 

Ok.

> Can I turn on something like debug for more precise investigation?

Yes, you can: http://org-trello.github.io/contributions.html#issues

Cheers,

**Comment by Bregor** [comment]
> I do not understand this sentence.

    org-trello - Synchronizing entity 'Поговорить про дальнейшие шаги' with id '5575fc9bff54dfba4fbb0533'...
    org-trello - Synchronizing entity 'Сделать бакет S3' with id '5575fc9f19e1d4509e056eeb'...
    org-trello - Sync buffer from trello - Catch error: (error "Not in an item")

Failed checklist item (due to debug) is:

    #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:position 50571 :name "Сделать машину (машины) исходя из предположения о меньшем трафике" :id "5575fcacb85f03a1c5cb34c4" :checked "complete" :level 3))

**Comment by ardumont** [comment]
>     org-trello - Synchronizing entity 'Поговорить про дальнейшие шаги' with id '5575fc9bff54dfba4fbb0533'...
>    org-trello - Synchronizing entity 'Сделать бакет S3' with id '5575fc9f19e1d4509e056eeb'...
>    org-trello - Sync buffer from trello - Catch error: (error "Not in an item")

Ok.

Can you show me an anonymised sample of your buffer please?

Cheers,

**Comment by Bregor** [comment]
Which buffer and what is anonymised sample? ;)
Which part I can anonymize without hurt to investigation?

**Comment by ardumont** [comment]
> Which buffer 

The buffer you are actually using for trying org-trello.

> and what is anonymised sample? ;)

The ids inside your buffer identify your board, etc...
It's up to you if you do not care about letting personal data flow :D 

> Which part I can anonymize without hurt to investigation?

Replace (or inject number inside) the identifiers (all hexadecimal strings).
I just want to take a look at the buffer's skeleton to `see` if there is not something wrong with it.

Cheers,

**Comment by Bregor** [comment]
Sorry for paranoid question, but can I just email you buffer content?

**Comment by ardumont** [comment]
> Sorry for paranoid question, but can I just email you buffer content?

Ok with me.
My public key http://keys.gnupg.net/pks/lookup?op=get&search=0x52E2E9840D10C3B8

Cheers,

**Comment by Bregor** [comment]
Hmmm...
Link leads to 404.

**Comment by ardumont** [comment]
> Link leads to 404.

Indeed, now it's down (I checked it in the train, it was up!)

Try this one!
http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x52E2E9840D10C3B8

My key fingerprint is BF00 203D 741A C9D5 46A8 BE07 52E2 E984 0D10 C3B8

(as a note, it's up again :D)

Cheers,

**Comment by Bregor** [comment]
Thank you!

Here is org-file: http://take.ms/1SgIR
And here is screenshot of trello board: http://take.ms/fQ4mI

Both are encrypted with your key.

**Comment by ardumont** [comment]
> Thank you!

> Here is org-file: http://take.ms/1SgIR
> And here is screenshot of trello board: http://take.ms/fQ4mI

Received, thanks.
You can destroy the destination links now.

> Both are encrypted with your key.

Decrypted alright, thanks.

--

So the trouble lies with the indentation (which is used to find the different metadata needed for org-trello to work). On card, it's the description (below drawer `:PROPERTIES:`) and the checkboxes (2 spaces for trello checklist and 4 for trello items).

The checklist must be indented and org-trello does enforce it.

But there seems to be a glitch with the initial state.

As there is no description nor empty drawer (`:PROPERTIES:...:END:`), the checklist keep getting indented at buffer save time.

```txt
* some card

- [ ] checklist
```

Remove the empty line.

```txt
* some card
- [ ] checklist
```

And all will be ok, the checklist will be rightly indented:

```txt
* some card
  - [ ] checklist
```

And the sync will work.

Cheers,

**Comment by Bregor** [comment]
> Remove the empty line.
> And all will be ok, the checklist will be rightly indented:

Not sure I got it right.
I need to edit card on trello.com board, or card in imported org file?

**Comment by ardumont** [comment]
> I need to edit card on trello.com board, or card in imported org file?

mmm...
(you should not edit anything in trello or else org-trello would not be necessary).

And, your question made me realise I'm the one who misunderstood.
I forgot the initial problem is that you sync FROM trello.

--
And, of course, this should not happen...
I am unable to reproduce with the small extract.

Can you please make a snapshot of the content of the problematic card (the one that fails... `eba...`)?

Cheers,

**Comment by Bregor** [comment]
JSON: https://dl.dropboxusercontent.com/u/213269/card.json.gpg
Screenshot: https://dl.dropboxusercontent.com/u/213269/card.png.gpg

**Comment by ardumont** [comment]
Hello,

I received the files, thanks. 
I now need to find some time to continue the investigation.

Thanks for your patience.

Cheers,

**Comment by Bregor** [comment]
No problem, take your time.
And thank you for your wonderful work!

**Comment by ardumont** [comment]
> No problem, take your time.
> And thank you for your wonderful work!

Thanks!

--

I have absolutely no idea of what I'm reading.
Thus, my inner voice is silent while I'm reading (for a change).
It's a funny feeling :D (but somehow distracting)...

Anyway, I created manually the card from the json you sent (copy/paste) the checklist/items and comments...

Sync back and forth and no issues arose...
I added you to a trello board I created with your issue to show you :D 

A question arise, what encoding for your buffer are you using?
My emacs buffer is in utf-8-unix.

Thanks for your feedback,

Cheers,

**Comment by Bregor** [comment]
It seems something wrong with my setup.
The same error with your board:

    org-trello - Sync buffer from trello - Catch error: (error "Not in an item")

**Comment by Bregor** [comment]
`C-h C` tells following:

    Coding system for saving this buffer:
      U -- utf-8-auto-unix

**Comment by Bregor** [comment]
After `M-x set-buffer-file-coding-system RET utf-8 RET` and resync amount of synced items decreased ;)

**Comment by Bregor** [comment]
My setup to be clear:

- OS X 10.10.3
- GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-04-12 on alais.local (compiled from HomeBrew)
- Org-mode version 8.3beta (release_8.3beta-1231-ga0a883 @ /Users/bregor/.emacs.d/el-get/org-mode/lisp/)

**Comment by ardumont** [comment]
> After M-x set-buffer-file-coding-system RET utf-8 RET and resync amount of synced items decreased ;)

Ok.
You still have the issue though, right?

Cheers,

**Comment by Bregor** [comment]
Yes.
Both with your board and with my.

**Comment by ardumont** [comment]
Hello,

Just so you know. 

Deep down the rabbit hole, https://github.com/tkf/emacs-request, the http client used to query trello uses curl (if detected).
So there might lie the settings trouble.

I cannot dig in further right now though...

Also, this might be of interest to you: https://github.com/ardumont/org/blob/master/org-trello/debug.org 
(I just started it, this can come in handy and will certainly be injected in the main site...)

Cheers,

**Comment by ardumont** [comment]
Regarding encoding problem, all those #318 (#309 #307) can help!

Also, now there is M-x org-trello-bug-report which help synthesize the platform used.

Cheers,

**Comment by Bregor** [comment]
Still the same with 0.7.8 as well:

    org-trello - Synchronizing entity 'Actions' with id '56d5a52da0cde51ff8ffdc24'...
    org-trello - Synchronizing entity 'Build package' with id '56d5a52da0cde51ff8ffdc25'...
    org-trello - Synchronizing entity 'Write chef recipe' with id '56d5a52da0cde51ff8ffdc27'...
    org-trello - Sync trello board 'Groupon Ops' to buffer 'trello.org'... FAILED. Error: (error "Not in an item")

No cyrillic letters this time, all in english

**Comment by ardumont** [comment]
Hello,

> Still the same with 0.7.8 as well:

Ack.

> Also, now there is M-x org-trello-bug-report which help synthesize the platform used.

Can you show the output of this command please?
It could help me in the long run to understand the platform divergences.
Thanks!

Cheers,

**Comment by Bregor** [comment]
System information:
	- system-type: darwin
	- locale-coding-system: utf-8-unix
	- emacs-version: GNU Emacs 24.5.1 (x86_64-apple-darwin15.0.0, NS apple-appkit-1404.11)
	 of 2015-10-01 on alais.local
	- org version: 8.3.4
	- org-trello version: 0.7.8
	- org-trello path: /Users/bregor/.emacs.d/el-get/org-trello/org-trello.el
	- request-backend: curl

**Comment by ardumont** [comment]
> System information:

Thanks!

**Comment by Jell** [comment]
I'm experiencing the same issue:

```
System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, NS apple-appkit-1348.17)
 of 2015-09-07 on jell-pro.local
- org version: 8.2.10
- org-trello version: 0.7.8
- org-trello path: /Users/Jell/.emacs.d/el-get/org-trello/org-trello.el
- request-backend: curl
```

**Comment by ardumont** [comment]
Hello,

What strikes me is the very similar configuration you have, only the org-version change but you have the same issue.

...

# el-get recipe?

The dependencies defined on the el-get recipe seems a bit off...
(they seem because i don't remember every detail about el-get)

- el-get: https://github.com/dimitri/el-get/blob/master/recipes/org-trello.rcp
- bare deps: https://github.com/org-trello/org-trello/blob/master/org-trello.el#L8

As a first step, can you please check if you have all the listed dependencies defined in the bare deps defined higher?

# request-backend

If deps are fine, can you please try to change from curl to request-backend, it helped in the past.
To do it, hit<kbd>M-:</kbd> and paste the following snippet:
```lisp
(require 'request)
(custom-set-variables '(request-backend 'url-retrieve))
```
Then hit enter.

Then try and do the sync again.

to revert (when done), apply the following.
```lisp
(custom-set-variables '(request-backend 'curl))
```

# if all else fails

Can you please provide a snippet of your org-buffer (anonymizing ids if need be)?

Thanks for your feedback.

Cheers,

**Comment by Jell** [comment]
so I tries all of the above, including by-passing the recipe given by el-get and installing via elpa, I am still getting the same error.

The part which I think is relevant is the last card, it fails the sync after syncing the first item in a checklist on that card:

```
* Checkout Improve error messages for mobile and pno                    :blue:
  :PROPERTIES:
  :orgtrello-users: ozcarstormer1
  :orgtrello-local-checksum: 933ca6451f85b3f97ff078a80f4e31766d80610872732734db590644fd0ddd60
  :END:

    - [ ] Rename existing phraseapp keys for invalid mobile and invalid pno :PROPERTIES: {"orgtrello-id":"57444171a766d69e1f2cfa81","orgtrello-local-checksum":"68ef1e447b5df890837dbfd6fa81b6c96391e5a8c088e59df934b817ca52d883"}
```

**Comment by Jell** [comment]
thanks for helping btw! :p Forgot to say that in my reply

**Comment by Jell** [comment]
if I switch the order of the checklist items, I get the same error, so I don't think the content of the checklist item is relevant

**Comment by ardumont** [comment]
> thanks for helping btw! :p Forgot to say that in my reply

Well, sure ^^

> so I tried all of the above, including by-passing the recipe given by el-get and installing via elpa, I am still getting the same error.

It's still progress ^^
It means, it's neither el-get nor curl the problem.

> The part which I think is relevant is the last card, it fails the sync after syncing the first item in a checklist on that card:

Do you mean that the other cards from the board are ok?

What strikes me in your sample is that the card does not own its `orgtrello-id` but its first checklist does...

> if I switch the order of the checklist items, I get the same error, so I don't think the content of the checklist item is relevant

Ack

-- 

Checking org's source code, this is the org-list namespace's which triggers those errors.
And specifically, related to movement function in list (what i call checklist).
Those function are used by org-trello to move around in buffer (to read or write stuff).
So definitely something wrong somewhere.

I'll reopen this one.

**Comment by Jell** [comment]
Yes I succeed in loading a bunch of cards before that one, then the syncing fails on the card with the checklist.

**Comment by Jell** [comment]
Here is the last two cards in the buffer after `C-u C-c o s`:

```
* Checkout Show an icon for valid / invalid input                       :green:red:lime:
  :PROPERTIES:
  :orgtrello-users: jeanlouis40,ozcarstormer1
  :orgtrello-id: 5742d171cb205772464cc514
  :orgtrello-local-checksum: b63b9e37b47610e116e34882439925d10a5940d7a83741964d3027813abed89a
  :END:
  give visual feedback (checkmark/x) when valid/invalid form entry.
* Checkout Improve error messages for mobile and pno                    :blue:
  :PROPERTIES:
  :orgtrello-users: ozcarstormer1
  :orgtrello-local-checksum: 933ca6451f85b3f97ff078a80f4e31766d80610872732734db590644fd0ddd60
  :END:

    - [ ] Rename existing phraseapp keys for invalid mobile and invalid pno :PROPERTIES: {"orgtrello-id":"57444171a766d69e1f2cfa81","orgtrello-local-checksum":"68ef1e447b5df890837dbfd6fa81b6c96391e5a8c088e59df934b817ca52d883"}
```

**Comment by ardumont** [comment]
This is no longer a duplicate since this is not encoding related as initially thought.

**Comment by ardumont** [comment]
> Yes I succeed in loading a bunch of cards before that one, then the syncing fails on the card with the checklist.

Do you imply that every other card has no checklist in them?

**Comment by Jell** [comment]
correct

**Comment by Jell** [comment]
If I move up the card with a checklist on the trello website, then I `C-u C-c o s` in emacs, all cards before that card on the website will be properly imported in emacs, then the syncing will fail after importing the first item in the checklist of that card in emacs.

**Comment by Jell** [comment]
So only the cards that are "before" the card with a checklist will be successfully imported, all after will fail to be imported, and the only thing imported from the card with a checklist is the first item in that checklist.

**Comment by ardumont** [comment]
> > Do you imply that every other card has no checklist in them?

> correct

Interesting.
...

oh...
i remember something...
checklist (first level list) must be indented at 2.
item (second level list) must be indented at 4.

So you are indeed not in an item... (according to your sample)
But you should not have to do anything about it.
...

**Comment by ardumont** [comment]
> So only the cards that are "before" the card with a checklist will be successfully imported, all after will fail to be imported, and the only thing imported from the card with a checklist is the first item in that checklist.

This enforces the probable indentation hypothesis then...

**Comment by Jell** [comment]
alright I've created a very bare trello board, with a single card and a checklist with two items, and I get the same error. You can see it here: https://trello.com/b/9DHQIxL4/testing

**Comment by Jell** [comment]
I have the following org-mode settings in my `custom.el` if that could help:
```
 '(org-babel-load-languages
   (quote
    ((emacs-lisp . t)
     (haskell . t)
     (clojure . t)
     (python . t))))
 '(org-image-actual-width 100)
 '(org-startup-with-inline-images t)
 '(org-startup-with-latex-preview t)
```

**Comment by ardumont** [comment]
> alright I've created a very bare trello board, with a single card and a checklist with two items, and I get the same error. You can see it here: https://trello.com/b/9DHQIxL4/testing

Thanks.
Can you please add me to it?

I tested on something similar but do not reproduce.
Still, i'm better off using the same stuff as you to decrease the risk.

> I have the following org-mode settings in my custom.el if that could help:

We are of one mind ^^
And nothing seems to be inclined to alter org's behavior there.

--

I wonder if the org-trello hooks provided are correctly installed...

I cannot look into it right now.
But i wil.

Thanks for speaking up!

Cheers,

**Comment by Jell** [comment]
I've invited you to that board, please let me know if I can do more things to help.

**Comment by ardumont** [comment]
Merci!
I mean thx (your firstname is french... sorry)

I'll ping you if i need something.

Cheers,

tony / @ardumont

**Comment by Jell** [comment]
So I deleted my .emacs.d and installed org-trello from elpa, and this time it works. So it could be a minor mode or something that's causing problems. I will investigate a bit more

**Comment by Jell** [comment]
I found the issue! The issue is when 'kill-whole-line is set to true! \o/
```
(setq kill-whole-line 't)
```
As simple as that! :) Took me a while to bisect my custom.el file, but the good news is the fix should be quite simple now!

**Comment by Jell** [comment]
I've made a PR that solve the problem for me! I will look into writing a regression test next, but worst case I leave that to you. Cheers!

**Comment by ardumont** [comment]
Awesome! Thx.

I need some time to take a look though.

Cheers,
