### ISSUE TITLE
Sync all deadlines to/from Trello by converting user's timezone to/from UTC 

### ISSUE THREAD

**Issue by LukeSwart** [org-trello/org-trello#277]
[Trello saves card due dates in UTC](http://webapps.stackexchange.com/questions/24741/what-time-zone-are-due-dates-in), so all times from the org-trello buffer should be converted to UTC before updating Trello, and from UTC before importing into the org-trello buffer.

For example, if I set a time using [org-mode's deadline feature](http://orgmode.org/manual/Deadlines-and-scheduling.html) (default binding is `C-c C-d`) to 2015-07-14 at 18:00, then I am prompted the date selection via [emacs' calendar tool](http://members.optusnet.com.au/~charles57/GTD/org_dates/#sec-6) then org-mode outputs this line: `DEADLINE: <2015-07-14 Tue 18:00>`. If I am in PST (ie Seattle, WA, USA), this line should be converted to its UTC equivalent `DEADLINE: <2015-07-15 Wed 01:00>` before updating my Trello card.

The same thing goes for importing dates from the Trello board - the dates are currently imported to the org-trello buffer in UTC. For example, if I use Trello's GUI to set a date for 2015-07-14 at 18:00, and I am in PST, Trello stores that date internally as 2015-07-15 at 01:00, and org-trello imports that date as `DEADLINE: <2015-07-15T01:00:00.000Z>`. (NOTE: It appears the DEADLINE format is not affected by Trello or org-trello, so `DEADLINE: <2015-07-15T01:00:00.000Z>` and `DEADLINE: <2015-07-15 Wed 01:00>` are equivalent)

I think the best approach is to convert all deadlines from UTC to the user's local timezone when syncing from Trello to the org-trello buffer, and converting all deadlines from the user's local timezone to UTC when syncing from the org-trello buffer to Trello. Let me know if there is a better approach.

**Comment by ardumont** [comment]
Hello,

Nice description.
Indeed, no date conversion is done. 

What you propose, as usual, seems quite reasonable.

But of course, now here is the kicker, I need some time to see how to implement this the emacs way.
In the mean time, if someone could propose a PR, that would be nice :D 

Cheers,

**Comment by ardumont** [comment]
Link times in there: http://www.gnu.org/software/emacs/manual/html_node/elisp/System-Interface.html#System-Interface

Avoid losing some time api scratch tinkering:

```lisp
;; date manipulation

(parse-time-string "Thu Aug 6 09:54:43 CEST 2015")
;; parse-time-string -> (SEC MIN HOUR DAY MON YEAR DOW DST TZ)
;;                      (43  54  9    6   8   2015 4 nil nil)


(apply 'encode-time '(43  54  9    6   8   2015 4 nil nil)) ;; (21955 4803)

(format-time-string "%d-%m-%Y %H:%M:%s" nil 'universal) "06-08-2015 08:32:1438846375"

(format-time-string "%d-%m-%Y %H:%M:%s" (apply 'encode-time (parse-time-string "Thu Aug  6 09:54:43 2015")) 'universal);; "06-08-2015 07:54:1438844083"
(format-time-string "%d-%m-%Y %H:%M:%s" (apply 'encode-time (parse-time-string "Thu Aug  6 09:54:43 2015")) );; "06-08-2015 09:54:1438847683"

(current-time) ;; (21955 6357 585689 14000)
(current-time-string) ;; "Thu Aug  6 10:21:08b 2015"

(current-time-zone);; (7200 "CEST")
(float-time) ;; 1438849379.9876146
```

For those of us not `time` guru:
- DOW Day Of Week
- DST Daylight Saving Time (nonsense :D)
- TZ Time Zone

**Comment by ardumont** [comment]
Trails:
- http://orgmode.org/manual/Deadlines-and-scheduling.html
- http://ergoemacs.org/emacs/elisp_parse_time.html
- https://github.com/org-trello/org-trello/blob/dc77390a3b96bb6b6f5bf2fa1cf2a5b46b48c409/org-trello-buffer.el#L485-492

**Comment by ardumont** [comment]
Some links:

    https://www.gnu.org/software/emacs/manual/html_node/elisp/Formatting-Strings.html
    https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators
    http://www.gnu.org/software/libc/manual/html_node/Locales.html#Locales
    http://www.gnu.org/software/emacs/manual/html_node/elisp/System-Environment.html#System-Environment

At the moment, I do not get how to set the local though emacs-lisp’ api to permit to check multiple behavior on multiple different time locale.

I need it for tests -> travis-ci’s node is not on the same locale as my machine, thus break as expected remotely.

If someone knows, this could help in getting faster.

**Comment by ardumont** [comment]
Encountering http://stackoverflow.com/questions/1571141/setting-timezone-of-org-mode.

And completing with emacs docstring:
```lisp
(set-time-zone-rule TZ)

Set the local time zone using TZ, a string specifying a time zone rule.
If TZ is nil, use implementation-defined default time zone information.
If TZ is t, use Universal Time.

Instead of calling this function, you typically want (setenv "TZ" TZ).
That changes both the environment of the Emacs process and the
variable `process-environment', whereas `set-time-zone-rule' affects
only the former.
```

**Comment by ardumont** [comment]
Great! Now covered!

Adding this in the test context and now it's happy:
```lisp
(setenv "TZ" "/usr/share/zoneinfo/Europe/London")
```

**Comment by LukeSwart** [comment]
@ardumont Thank you very much! This feature is working great, and all of my deadlines are syncing with my local timezone.

**Comment by ardumont** [comment]
@ardumont Thank you very much! This feature is working great, and all of my deadlines are syncing with my local timezone.

Cool!
Thanks for the feedback.

Cheers,
