### ISSUE TITLE
Issue when overloading "#+TODO: " for list names

### ISSUE THREAD

**Issue by yangchenyun** [org-trello/org-trello#282]
The problem is in the default parsing behavior for "#+TODO:" in org-mode.

>Remember that the keywords after the vertical bar (or the last keyword if no bar is there) must always mean that the item is DONE (although you may use a different word). 

So a meta like below will make the Reality tag a DONE which usually has a different head font setting s(like striking through) than other states. 
```
#+TODO: Spontaneous-Ideas Ideas-being-thought-through Ideas-will-be-realized Reality
```

Will it be a better idea to use a grouped labels instead?

**Comment by ardumont** [comment]
Hello,

> The problem is in ...

I understand the first part.

> Will it be a better idea to use a grouped labels instead?

I don't know, what's a grouped label?

Cheers,

**Comment by ardumont** [comment]
I still don't get the 'grouped label', can you please clarify?

**Comment by yangchenyun** [comment]
I used the wrong phrase, it is called ["grouped tag"](http://orgmode.org/guide/Tag-groups.html#Tag-groups) in org-mode.

I would suggest use a @trello_* like for the group, it will have a better support for more generic labels like the one I had in the above example.

The downside is: for a default trello list setup (TODO/DOING/DONE), maps to org-mode's '#+TODO' reasonably, so we maybe we could provide a customize option for either using grouped tags (@trello_*) or current behaviors to save list information of a board.

**Comment by ardumont** [comment]
Hello,

thanks for getting back to me.

> I used the wrong phrase, it is called "grouped tag" in org-mode.

Ok. I did not know this notion.

> I would suggest use a @trello_* like for the group, it will have a better support for more generic labels like the one I had in the above example.
> The downside is: for a default trello list setup (TODO/DOING/DONE), maps to org-mode's '#+TODO' reasonably, so we maybe we could provide a customize option for either using grouped tags (@trello_*) or current behaviors to save list information of a board.

After reading couple of times, i admit i don't quite get it.
This seems to be in a search context.

This seems also quite complicated a change for a bad rendering face problem (for just one org keyword).

> So a meta like below will make the Reality tag a DONE which usually has a
different head font setting s(like striking through) than other states.

Can't we just use emacs' (hooks, custom-set-faces, custom-set-variables, etc...)
and org-mode mechanisms to overcome this?

What i understand is that you are annoyed with some font rendering for one todo
word (the last one).
Would it not be simpler for example to override the fonts in org-trello's file?

Here is how i have setuped my org-mode for the display part and some part seems
relevant here:

```lisp
;; keywords sequence for org-mode
'(org-todo-keywords
  '((sequence "TODO(t)" "IN-PROGRESS(i)" "PENDING(p)" "|" "DONE(d)" "FAILED(f)" "DELEGATED(e)" "CANCELLED(c)")))
;; modifying the color for the different keywords
'(org-todo-keyword-faces
  '(("TODO"        . (:foreground "firebrick2" :weight bold))
    ("IN-PROGRESS" . (:foreground "olivedrab" :weight bold))
    ("PENDING"     . (:foreground "sienna" :weight bold))
    ("DONE"        . (:foreground "forestgreen" :weight bold))
    ("DELEGATED"   . (:foreground "dimgrey" :weight bold))
    ("FAILED"      . (:foreground "steelblue" :weight bold))
    ("CANCELLED"   . shadow)))

;; those last lines seems quite interesting for your use case
(custom-set-faces
 '(org-done ((t (:foreground "PaleGreen" 
                             :weight normal
                             :strike-through t))))
 '(org-headline-done
   ((((class color) (min-colors 16) (background dark))
     (:foreground "LightSalmon" :strike-through t)))))
```

So something like this in your user configuration should do the trick:

```lisp
(add-hook 'org-trello-mode-hook (lambda ()
                                  ;; replace this by your specific setup that removes the particular bad faces...
                                  (custom-set-faces
                                   '(org-done ((t (:foreground "PaleGreen" 
                                                               :weight normal
                                                               :strike-through t))))
                                   '(org-headline-done
                                     ((((class color) (min-colors 16) (background dark))
                                       (:foreground "LightSalmon" :strike-through t))))))
          nil t) ;; t means local so that it should be only for your org-trello buffer
```
(This is not tested, i'm merely pointed out some hints that you'll have to dig in).

Hoping that helps.

Thanks for reporting back here your tryouts.
This could indeed interest others ;p

Cheers,
