### ISSUE TITLE
feature request: toggle-assign-me

### ISSUE THREAD

**Issue by yangchenyun** [org-trello/org-trello#283]
As it will only be one action for assign/unassign given one state, it makes more sense to just have a toggle function instead of current prefix for unassign.

**Comment by ardumont** [comment]
Which if i remember correctly is what it was initially (or maybe i did not push it...)

**Comment by yangchenyun** [comment]
Right now, prefix arguments distinguish this two actions. 
If you already have it,  we could close it.

**Comment by ardumont** [comment]
> Right now, prefix arguments distinguish this two actions. 

Indeed.
I merely pointed out that the behavior changed (i'm more certain of it now).

I remember having adapted the behavior of all commands.
Unified them when they started using the universal argument to be symmetrical.

But you're right, the toggling seems more user-friendly here.

> If you already have it, we could close it.

Nope, don't close it just yet.

Cheers,
