### ISSUE TITLE
org-trello - client - Problem during request - error-thrown: (json-readtable-error)

### ISSUE THREAD

**Issue by boothead** [org-trello/org-trello#287]
Hi,

I have hit a problem with setting up org-trello under spacemacs. The machine is windows behind a proxy. `C-c o i` seemed to go fine as I have org-trello in my list of application now. However when I try `C-c o I` I do not get a list of board names to complete on and `org-trello - client - Problem during request - error-thrown: (json-readtable-error)` appears in my `*Messages*` buffer.

**Comment by ardumont** [comment]
Hello,

It'd be great if you could please, <kbd>M-x org-trello-bug-report</kbd> and paste the result over here.
Thanks.

On with the rest :D 

> I have hit a problem with setting up org-trello under spacemacs. The machine is windows behind a proxy.

I do not test under windows nor other emacs' flavors so there might be shortcomings I'm not aware of.
As hints, on windows, the previous errors reported were related to:
-  gnutls not installed
- problems with curl not in %path% (`request` is emacs' library used to http query and it uses curl if it finds it or use emacs' internal mechanism otherwise)

(In short, not having a package manager does not help... might be chocolatey could help?)

> C-c o i seemed to go fine as I have org-trello in my list of application now.

I do not understand this sentence. Can you please clarify?

<kbd>C-c o i</kbd> is not for installing org-trello, it's for credential setup.
org-trello needs only be installed through one of emacs' packaging system (melpa, marmalade, et-get) and it's then present in emacs' load-path.

>  However when I try C-c o I I do not get a list of board names to complete on and org-trello - client - Problem during request - error-thrown: (json-readtable-error) appears in my *Messages* buffer.

Ok.

I did not reproduce (as per my machine's setup though so potentially irrelevant)

<kbd>C-c o i</kbd> does not interact through http directly to trello. The user is the medium in this case. That's why it worked.

However, <kbd>C-c o I</kbd> does http request trello.

Can you please check the connection works with <kbd>C-c o d</kbd>?
This will check by requesting to trello your user and going on to the same process as parsing etc...
So it's an environment problem, this should fail the same way.

--

We could have more information with this following snippet of code to execute in emacs' repl:
<kbd>M-x ielm</kbd>

```lisp
;; basically the same as C-c o d
(let ((org-trello--user-logged-in "<user-here>"))
  (orgtrello-controller-load-keys)
  (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))

;; or
;; basically the same as C-c o I (the part that does not work on your side)
(let ((org-trello--user-logged-in "<user-here>"))
  (orgtrello-controller-load-keys)
  (orgtrello-controller--list-boards))
```

Cheers,

**Comment by boothead** [comment]
Here's the output of the bug report (that is an awesome thing to add to a library BTW!):

```
org-trello - List of errors:
 - Setup problem.
Either you did not connect your org-mode buffer with a trello board, to correct this:
  * attach to a board through C-c o I or M-x org-trello-install-board-metadata
  * or create a board from scratch with C-c o b or M-x org-trello-create-board-and-install-metadata).
Either your org-mode's todo keyword list and your trello board lists are not named the same way (which they must).
For this, connect to trello and rename your board's list according to your org-mode's todo list.
Also, you can specify on your org-mode buffer the todo list you want to work with, for example: #+TODO: TODO DOING | DONE FAIL (hit C-c C-c to refresh the setup)

org-trello - Checking setup. DONE.
org-trello - Please:
- Describe your problem with clarity and conciceness (cf. https://www.gnu.org/software/emacs/manual/html_node/emacs/Understanding-Bug-Reporting.html)
- Explicit your installation choice (melpa, marmalade, el-get, tarball, git clone...).
- Activate `'trace`' in logs for more thorough output in *Message* buffer: (custom-set-variables '(orgtrello-log-level orgtrello-log-trace)).
- A scrambled sample (of the user's and board's ids) of your org-trello buffer with problems.
- Report the following message trace inside your issue.

System information:
- system-type: windows-nt
- locale-coding-system: cp1252
- emacs-version: GNU Emacs 24.5.1 (i686-pc-mingw32)
 of 2015-04-11 on LEG570
- org version: 8.2.10
- org-trello version: 0.7.4
- org-trello path: c:/Users/1518675/AppData/Roaming/.emacs.d/elpa/org-trello-20150824.1549/org-trello.el
```

> C-c o i seemed to go fine as I have org-trello in my list of application now.
> I do not understand this sentence. Can you please clarify?

What I meant here was that after I run `C-c o i` to install org-trello's credentials, I see org-trello in the list of applications under my account. From that I assume that the initial set up of credentials worked fine.

Here's the out put of the commands:

```
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (let ((org-trello--user-logged-in "boothead"))
  (orgtrello-controller-load-keys)
  (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
nil
ELISP> (let ((org-trello--user-logged-in "boothead"))
  (orgtrello-controller-load-keys)
  (orgtrello-controller--list-boards))
nil
ELISP> 
```

It's entirely possible that some of the unixey stuff you ask about isn't available. Although I have a cygwin environment, for reasons of incredible enterprise lunacy I have to use a native windows emacs. Any idea how I could debug that further for you?

Thanks for the swift feedback!

**Comment by ardumont** [comment]
Hello,

> that is an awesome thing to add to a library BTW!

Well, thanks.

It hit me that it could help improve the feedback if I simply coded what i
needed.

Also, bunch of libraries and Emacs itself got it so I inspired from it.

> What I meant here was that after I run C-c o i to install org-trello's credentials, I see org-trello in the list of applications under my account. From that I assume that the initial set up of credentials worked fine.

ok.

> > Here's the out put of the commands:
> 
> *** Welcome to IELM ***  Type (describe-mode) for help.
> ELISP> (let ((org-trello--user-logged-in "boothead"))
           >          (orgtrello-controller-load-keys)
           >          (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
> nil
> ELISP> (let ((org-trello--user-logged-in "boothead"))
           >          (orgtrello-controller-load-keys)
           >          (orgtrello-controller--list-boards))
> nil
> ELISP> 
>
> Any idea how I could debug that further for you?

Well, 2 things i think:

- first, are the credentials really ok?
What's the content of ~/.emacs.d/.trello/boothead.el?

(I think `~` means c:/Users/1518675/AppData/Roaming/.emacs.d/ for you)

It's supposed to be something like:

```lisp
(setq org-trello-consumer-key "consumer-key")
(setq org-trello-access-token "access-token")
```

You can double check in ielm by inputting them directly.
It's supposed to be something, if nil, trouble there is.

Can you please check the content is ok?

- i do not understand why it did not return anything else than nil.
It's supposed to return a hashtable with trello data...

Something like the following:
```lisp
ELISP> (let ((org-trello--user-logged-in "ardumont"))
         (orgtrello-controller-load-keys)
         (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data
              (:username "ardumont" :url "https://trello.com/ardumont" :status "disconnected" :full-name "Antoine R. Dumont" :id "some-id"))
```

Can you please retry the following (the log level changed) and check the *Message* buffer after that:
```lisp
(let ((org-trello--user-logged-in "ardumont")
      (orgtrello-log-level orgtrello-log-trace))
  (orgtrello-controller-load-keys)
  (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))

(let ((org-trello--user-logged-in "ardumont")
      (orgtrello-log-level orgtrello-log-trace))
  (orgtrello-controller-load-keys)
  (orgtrello-controller--list-boards))
```

Thanks.

--

> It's entirely possible that some of the unixey stuff you ask about isn't available.

It's possible indeed but... maybe it's simply the credentials which are badly set.

> Although I have a cygwin environment, for reasons of incredible enterprise lunacy

I feel you!
Out of curiosity, how does that work exactly?

You use the native emacs by launching it with the .exe file
or do you launch emacs from within cygwin?

> I have to use a native windows emacs.

Well as long as there is no external dependency on the system, native windows
emacs should be as badass as the rest of them all...

The pain came when there is dependency on operating system's tools...

But, technically, regarding org-trello, as it uses request which uses `url.el`
as default if no curl installation is present (https://github.com/tkf/emacs-request)
org-trello should work on windows no problem too...

Cheers,

**Comment by boothead** [comment]
OK, I've checked my credentials and re-authorised. With the new command you gave above I get:

```
org-trello - Detailed response: [cl-struct-request-response 400 nil nil (json-readtable-error) parse-error "https://api.trello.com/1/members/me/boards?key=<my-key>&token=<my-token>&filter=open&lists=open" nil (:sync t :type "GET" :params ((key . "<my-key>") (token . "<my-token>") ("filter" . "open") ("lists" . "open")) :parser orgtrello-query--http-parse :success orgtrello-query--standard-success-callback :error orgtrello-query--standard-error-callback :url "https://api.trello.com/1/members/me/boards?key=<my-key>&token=<my-token>&filter=open&lists=open" :response #0) #<killed buffer> "HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
Content-Length: 691
" nil url-retrieve nil]
```

When I hit that URL in the browser it works as expected. I assume that this is some oddity in how my organisation handles SSL certificates. If I try wget (from within cygwin) I get told that the certificate isn't valid. Could you give me any further pointers on how to debug further?

I was using emacs from within cygwin but I ended up having too many problems with various other enterprise crapware so now I just run native windows spacemacs.

**Comment by ardumont** [comment]
Hello,

For the sake of completeness, I confirm request's doc about curl and url.el:

```lisp
(defcustom request-backend (if (executable-find request-curl)
                               'curl
                             'url-retrieve)
  "Backend to be used for HTTP request.
Automatically set to `curl' if curl command is found."
  :group 'request)
```

> OK, I've checked my credentials and re-authorised.

Does it imply there was a problem in your credentials file?

> With the new command you gave above I get:
> 
> org-trello - Detailed response: [cl-struct-request-response 400 nil nil (json-readtable-error) parse-error "https://api.trello.com/1/members/me/boards?key=<my-key>&token=<my-token>&filter=open&lists=open" nil (:sync t :type "GET" :params ((key . "<my-key>") (token . "<my-token>") ("filter" . "open") ("lists" . "open")) :parser orgtrello-query--http-parse :success orgtrello-query--standard-success-callback :error orgtrello-query--standard-error-callback :url "https://api.trello.com/1/members/me/boards?key=<my-key>&token=<my-token>&filter=open&lists=open" :response #0) #<killed buffer> "HTTP/1.1 400 Bad Request
> Cache-Control: no-cache
> Pragma: no-cache
> Content-Type: text/html; charset=utf-8
> Proxy-Connection: close
> Connection: close
> Content-Length: 691
> " nil url-retrieve nil]
> 
> When I hit that URL in the browser it works as expected.
> I assume that this is some oddity in how my organisation handles SSL certificates.
> If I try wget (from within cygwin) I get told that the certificate isn't valid.

> Could you give me > any further pointers on how to debug further?

I'll try.

For logging more, on request's side, i see those defcustoms (user customizable variable):
```lisp
(defcustom request-log-level -1
  "Logging level for request.
One of `error'/`warn'/`info'/`verbose'/`debug'.
-1 means no logging."
  :group 'request)

(defcustom request-message-level 'warn
  "Logging level for request.
See `request-log-level'."
  :group 'request)
```

I do not get yet why there are 2 customs for that but i'd suggest setting one already:

mmphh, it did not work immediately, so looking into the levels definition gives:
```lisp
(defconst request--log-level-def
  '(;; debugging
    (blather . 60) (trace . 50) (debug . 40)
    ;; information
    (verbose . 30) (info . 20)
    ;; errors
    (warn . 10) (error . 0))
  "Named logging levels.")
```
(Sorry for the details but i use the issues as memories)

So something like:

```lisp
ELISP> (let ((org-trello--user-logged-in "ardumont")
             (orgtrello-log-level orgtrello-log-trace)
             (request-log-level 'blather)
             (request-message-level 'blather))
         (orgtrello-controller-load-keys)
         (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
```

should definitely show more trace inside the *Message* buffer.

If the `let` did not make more output, we could always set this verbosity level `globally` (at current emacs' session that is):

```lisp
(custom-set-variables '(request-log-level 'blather)
                      '(request-message-level 'blather))
```

Hoping this will help...

--

By the way, i see one shortcoming in org-trello.
This, setting the underlayer trace level, should be handled by org-trello's
logging mechanism.
So, again, thanks for raising the issue and keeping up the debugging investigation.

Cheers,

**Comment by boothead** [comment]
OK, so I tried that and I get lots of 'blather :-) unfortunately it's all from the corporate proxy saying that I've got a malformed request, eg:

```
<HTML><HEAD>
<TITLE>Request Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Request Error (invalid_request)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your request could not be processed. Request could not be handled
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This could be caused by a misconfiguration, or possibly a malformed request.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
```

I guess I've been out enterprised :-(

Thank you very much for your help - I'll try and use org-trello on another machine.

**Comment by ardumont** [comment]
> I guess I've been out enterprised :-(

It's a crappy world... indeed...

> Thank you very much for your help - I'll try and use org-trello on another machine.

Thank you for trying your best at this.

-- 

Could it be that something somehow split/limit the request along the way?
Thus rendering the requests malformed...

I've already seen this, not for org-trello, mind you but for other stuff.
The thing was that a request initiated by a client was bounced by a server but got splitted by the server and then the proxy said... `No way, bad request dude, go away...`...

So if somehow, there were more than 1 proxy (don't know why...) it could be that...

Thanks again for trying...

Cheers,
