### ISSUE TITLE
Install key and token... FAILED. Error: (invalid-function ((access-token consumer-key user-login) data))

### ISSUE THREAD

**Issue by SamHasler** [org-trello/org-trello#295]
I'm getting the following error after providing the key and access token to `org-trello-install-key-and-token`

```
org-trello - Install key and token... FAILED. Error: (invalid-function ((access-token consumer-key user-login) data))
org-trello - version: 0.7.5
```

**Comment by ardumont** [comment]
Hello,

Do you still have the *Compile log* from your installation process?

If you have, can you please paste it here? Thanks.

Also copy/paste the result of <kbd>M-x org-trello-bug-report RET</kbd> here would be great.

Thanks

Cheers,

**Comment by SamHasler** [comment]
I installed with el-get. I tried removing and reinstalling but there wasn't anything about org-trello in the compile log.

```
System information:
- system-type: windows-nt
- locale-coding-system: cp1252
- emacs-version: GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)
 of 2015-09-07
- org version: 8.2.10
- org-trello version: 0.7.5
- org-trello path: c:/Users/<username>/.emacs.d/el-get/org-trello/org-trello.el
```

**Comment by ardumont** [comment]
Hello,

Thanks for the feedback.

No hint as of now.

Cheers,

**Comment by SamHasler** [comment]
ok, let me know if there's anything I can do to provide more details.

**Comment by brool** [comment]
I had this exact error and tracked it back to a old version of dash that did not implement -let in my packages, version number 2014xxxx or something such.   Updating dash fixed the issue.

**Comment by ardumont** [comment]
@brool Thanks a bunch!

**Comment by ardumont** [comment]
Ah yes, the version numbering scheme... 
Depending on the installation process, apparently the installation can be ****ed up it seems.

I reference the dependency version the normal way...
So if you don't have dash (2.5.0 i think), it will fetch it.

But if you already have it with version say 2014xxxx (so greater than the normal), it won't...
And indeed, if some of dash's functionalities is not found, it crashes...

@brool Again, thanks for the hint!

Cheers,

**Comment by SamHasler** [comment]
@brool Thanks!

I had multiple versions of dash installed by package.el and el-get. I couldn't get el-get to recognise the one that package.el had installed, and package.el said that dash was a dependency of several other packages, so I ended up doing an el-get-remove for dash and org-trello and then reinstalling org-trello with package.el.

**Comment by SamHasler** [comment]
Closing as it's not a bug in org-trello and this issue is documentation enough for someone else to find and fix it.
