### ISSUE TITLE
Create

### ISSUE THREAD

**Issue by graham-m-dunn** [org-trello/org-trello#298]
I've created a trello board from an emacs buffer `M-x  org-trello/create-board-and-install-metadata`, but all cards are created empty, and I can't sync any of the items (neither `M-x org-trello/sync-card` or `M-x org-trello/sync-buffer` work).

What should I be looking at?

```
org-trello - List of errors:
 - Setup problem.
Either you did not connect your org-mode buffer with a trello board, to correct this:
  * attach to a board through C-c o I or M-x org-trello-install-board-metadata
  * or create a board from scratch with C-c o b or M-x org-trello-create-board-and-install-metadata).
Either your org-mode's todo keyword list and your trello board lists are not named the same way (which they must).
For this, connect to trello and rename your board's list according to your org-mode's todo list.
Also, you can specify on your org-mode buffer the todo list you want to work with, for example: #+TODO: TODO DOING | DONE FAIL (hit C-c C-c to refresh the setup)
```

**Comment by ardumont** [comment]
Hello,

> I've created a trello board from an emacs buffer M-x org-trello/create-board-and-install-metadata, but all cards are created empty, and I can't sync any of the items (neither M-x org-trello/sync-card or M-x org-trello/sync-buffer work).

Can you please copy-paste the content of `M-x org-trello-bug-report`?

Thanks.

> What should I be looking at?

I do not know yet.

The `org-trello/` commands you mention is the old api. This is now deprecated.
This won't change anything to the actual behavior you have though.
(The old function name are aliases of the new api which is dash separated now so `org-trello-`)

So is this possible you updated recently org-trello to a new one?

If so take a look at your ~/.emacs.d/.trello/ folder.
This is now supposed to contain at least one file with your trello login filename ending in `.el`
and this is supposed to contain the credentials for trello...
(this must be exactly the trello login but i don't remember why...)

My trello login is ardumont so for me it's ardumont.el.
This is supposed to be also in the org-trello buffer as header.

Again for me, it's:
```org
#+PROPERTY: orgtrello-user-ardumont someid
#+PROPERTY: orgtrello-user-me ardumont
```

Do you see any divergence with your install?

Cheers,

**Comment by graham-m-dunn** [comment]
I archived everything from my org file, then synced a new board and things are working as expected now, so I guess there was something in my org file that wasn't compatible.
