### ISSUE TITLE
Errors in Emacs 25 related to setq

### ISSUE THREAD

**Issue by myrjola** [org-trello/org-trello#299]
I get the following errors when trying to compile org-trello on `GNU Emacs 25.0.50.8 (x86_64-apple-darwin15.0.0, NS appkit-1404.34 Version 10.11.2 (Build 15C50)) of 2015-12-09`:

```
Compiling file /Users/martin/.emacs.d/elpa/org-trello-20150905.1124/org-trello.el at Wed Dec  9 16:55:22 2015
org-trello.el:527:1:Error: missing value for `org-trello-mode-on-hook' at end of setq
org-trello.el:552:1:Error: missing value for `org-trello-mode-off-hook' at end of setq
```

Seems that setq needs one more argument to be able to set the value.

**Comment by ardumont** [comment]
Hello,

I have not tested org-trello with emacs-25 yet so thanks for the feedback.

It seems the `setq` definition changed.

which means that:
> https://github.com/org-trello/org-trello/blob/master/org-trello.el#L552
> https://github.com/org-trello/org-trello/blob/master/org-trello.el#L527

need to change to either using `defvar`:

```lisp
(defvar org-trello-mode-on-hook)
(defvar org-trello-mode-off-hook)
```
(depending on defvar's definition also changed or not)

and `setq` them to nil:
```lisp
(setq org-trello-mode-on-hook nil)
(setq org-trello-mode-off-hook nil)
```

or both.

Cheers,

**Comment by ardumont** [comment]
I've pushed what i believe is a fix https://github.com/org-trello/org-trello/commit/8fde2d061f6a67e190c11c7565205bcafa464d97

I can't test it though so any feedback is welcome.
(melpa-unstable will package it all by itself)

Cheers,

**Comment by ardumont** [comment]
For information, org-trello on melpa got rebuilt.
If you want to test the fix, it'd be great :D 

Cheers,

**Comment by myrjola** [comment]
I updated my packages and org-trello installed successfully. Thanks for fixing this!

```
org-trello is an installed package.

     Status: Installed in ‘org-trello-20151209.745/’
    Version: 20151209.745
```

**Comment by ardumont** [comment]
Cool.

Thx for the feedback.

Cheers,
