### ISSUE TITLE
Failed sync: "Can't preview LaTeX fragment in a non-file buffer"

### ISSUE THREAD

**Issue by coyotespike** [org-trello/org-trello#303]
Thanks for making and maintaining org-trello! I'm excited to start using it.

After successfully inserting the board metadata to the top of the buffer, `C-u C-c o s` correctly insert the first card from the board, but then halts with the message `org-trello - Sync trello board 'Expunct' to buffer 'Trello.org'... FAILED. Error: (user-error "Can't preview LaTeX fragment in a non-file buffer")`

This message occurs regardless of which card is placed first, and it occurs on both boards I've tested it on. Whichever card is first, it loads correctly, then the error occurs. 

I use LaTex preview all the time in org-mode (and I've exported LaTex to PDF), so I'm puzzled.

Thanks for any help!

System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.3.1
- org version: 8.2.8
- org-trello version: 0.7.5
- org-trello path: /Users/me/.emacs.d/elpa/org-trello-20151213.736/org-trello.el

I also ran `orgtrello-log-trace`. This shows all the cards returning from the call.
`org-trello - Opened trello-cards: [cards here]`
`org-trello - Sync trello board .... [error message as above]`

**Comment by ardumont** [comment]
Hello,

> I use LaTex preview all the time in org-mode (and I've exported LaTex to PDF), so I'm puzzled.

I am puzzled too :D 

Some questions:
- What's latex preview?  Is this related to http://orgmode.org/worg/org-tutorials/org-latex-preview.html?

- Do you have some latex formulae on your org-file? Do you have please some basic samples to look at?

Cheers,

**Comment by coyotespike** [comment]
lol!

Yes, that's the latex preview I mean. This is enabled by default in all org files if your .emacs has in its custom-set-variables: 
```
 '(org-pretty-entities t)
 '(org-startup-with-inline-images t)
 '(org-startup-with-latex-preview t)
```.
With that, org-mode displays automatically all the symbols found here: http://orgmode.org/worg/org-symbols.html

No, the org-file has no latex formulae in it! It is a blank buffer. The Trello board also has no latex in it.

I just tried disabling latex preview in that buffer, to see if that would make a difference, but the same error crops up.

So, right now I can't tell if this error is related to org-mode in particular, or Emacs.

Here is a Gist with the stack trace. Please let me know anything else I can provide! I didn't turn up anything useful with half an hour or so of Googling.
https://gist.github.com/coyotespike/c827b7208d0d50964de4

**Comment by ardumont** [comment]
> With that, org-mode displays automatically all the symbols found here: http://orgmode.org/worg/org-symbols.html

This seems quite nice.

> No, the org-file has no latex formulae in it! It is a blank buffer. The Trello board also has no latex in it.

Hum, puzzled... bedaffled even :D 

Activating the option 'org-startup-with-latex-preview you are referring too, i now reproduce the issue (all were nil on my part).

> So, right now I can't tell if this error is related to org-mode in particular, or Emacs.

Deactivating it and the trouble disappears...
I don't know yet what to do with this though...

Hackish solution not perfect:

```lisp
(make-local-variable 'org-startup-with-latex-preview)
(add-hook 'org-trello-mode-on-hook (lambda () (setq org-startup-with-latex-preview nil)))
(add-hook 'org-trello-mode-on-hook (lambda () (setq org-startup-with-latex-preview t))
``` 
(unfortunately, make-local-variable did not have effect on my side... having multiple buffer opened, the value was the same on all buffers... *sigh*)

The other lines de/activate the variable's content according to your use case when org-trello activates or deactivates.

The documentation of this variable mentions:
```org
#+STARTUP: nolatexpreview
```
which seems less hackish but the problem is not solved! That is i have the error...

Like i said, i don't quite know make of this yet.

**Comment by coyotespike** [comment]
Fantastic! I got exactly the same results.

1. Changing  `(org-startup-with-latex-preview t)` to `nil` removed the problem.
2. Leaving  `org-startup-with-latex-preview t)` as `t`, including the local-variable, and closing all other org files also removed the problem. This solution doesn't work with other org files open.

Your local-variable also works for me without the third line, in other words like this:
```
(make-local-variable 'org-startup-with-latex-preview)
(add-hook 'org-trello-mode-on-hook (lambda () (setq org-startup-with-latex-preview nil)))
;;; (add-hook 'org-trello-mode-on-hook (lambda () (setq org-startup-with-latex-preview t))
```

Probably the simplest solution is to leave latex-preview nil, then enable on a per-file basis. If that's too much trouble, then just closing other org files before syncing will work for now.

Still, I've no idea where to begin looking for a more granular solution! `M-x debug` doesn't provide any additional info.

Thanks so much for jumping into this!

**Comment by ardumont** [comment]
> Probably the simplest solution is to leave latex-preview nil, then enable on a per-file basis. If that's too much trouble, then just closing other org files before syncing will work for now.

Indeed.

> Still, I've no idea where to begin looking for a more granular solution! M-x debug doesn't provide any additional info.

When hitting there, then remains the code as final step :D 

And so taking a look at org.el's code, Here is the interesting mode's definition part:

```lisp
(define-derived-mode org-mode outline-mode "Org"
...
     (when org-startup-with-latex-preview (org-toggle-latex-fragment))
...
```

And the  interesting function definition part is at the beginning of the function:
```lisp
(defun org-toggle-latex-fragment (&optional arg)
  "Preview the LaTeX fragment at point, or all locally or globally.
...
  (unless (buffer-file-name (buffer-base-buffer))
    (user-error "Can't preview LaTeX fragment in a non-file buffer"))
...
```

(This is the only error message in the code that match.)

So, apparently, your buffer needs to have a filename for this preview thingy to work (or so i understand).

Does this help?

Cheers,

**Comment by coyotespike** [comment]
"When all else fails, read the directions." ;-) Nice find!

But, and I hesitate to be stupid here, the buffer has a name! I used the function below to confirm, and then also ran `M-x eval-expression` with `(buffer-file-name (buffer-base-buffer))`. Both of these methods display the full path to the file, ending with the file name.

```
(defun insert-file-name ()
  "Insert the full path file name into the current buffer."
  (interactive)
  (insert (buffer-file-name (window-buffer (minibuffer-selected-window)))))
```
Is there a temporary unnamed filed created, which org-latex-preview attempts to prepare for latex rendering?

**Comment by ardumont** [comment]
> "When all else fails, read the directions." ;-) Nice find!

Nice sum up :D 

> But, and I hesitate to be stupid here,

Don't :D 

I feel less alone when i'm not alone `being stupid` :D 

> the buffer has a name! I used the function below to confirm, and then also ran M-x eval-expression with (buffer-file-name (buffer-base-buffer)). Both of these methods display the full path to the file, ending with the file name.

Yep, that's not it then.

> Is there a temporary unnamed filed created, which org-latex-preview attempts to prepare for latex rendering?

It's a good question.
Regarding org-latex..., I have no clue. The function i mention seems to not be doing that.

... (thinking of something...) ...

Hum... now, org-trello does use `with-current-temp` for computing entities checksums at
https://github.com/org-trello/org-trello/blob/3718ed704094e5e5a491749f1f722d76ba4b7d73/org-trello-buffer.el#L841

And i do activate (org-mode) https://github.com/org-trello/org-trello/blob/3718ed704094e5e5a491749f1f722d76ba4b7d73/org-trello-buffer.el#L843
(which as i show early on is one way to trigger the issue)

So, can you please try this:

```lisp
(defun orgtrello-buffer--compute-string-for-checksum (region)
  "Given a REGION, compute the string to checksum."
  (lexical-let ((region region)
                (buffer-name (current-buffer)))
    (with-temp-buffer
      (apply 'insert-buffer-substring (cons buffer-name region))
      (let ((org-startup-with-latex-preview nil))
        (org-mode))
      (orgtrello-buffer-delete-property org-trello--label-key-local-checksum)
      (when orgtrello-setup-use-position-in-checksum-computation
        (goto-char (point-max))
        (insert (format "\n%s" (car region))))
      (buffer-substring-no-properties (point-min) (point-max)))))
```
(In this new definition, i override explicitely this flag to nil when activating org-mode.)

Copy this on a scratch buffer and <kbd>M-x eval-buffer</kbd>.
This will override your current org-trello install with this new function monkey-patched (it's volatile, at next reboot, it's lost).

Then activates globally the flag `org-startup-with-latex-preview` to t.
Then at last, trigger what you did initially, is the problem gone for you as well?

Cheers,

**Comment by coyotespike** [comment]
(sorry for the delay, holidays took me away!) Dang, I think it worked! :D

I tested this several times. After setting `org-startup-with-latex-preview` to t, I restarted my Emacs to ensure that the problem persisted without this function, then eval'd it on a scratch buffer a second time. The problem seems to be gone. Magic! Your emacs-fu is advanced. :-)

So, if I paste this in my .emacs, then it will get eval'd every time I start emacs - a permanent monkey-patch. What do you think?

**Comment by ardumont** [comment]
> (sorry for the delay, holidays took me away!) 

No problem. I thought as much.

> Dang, I think it worked! :D
> I tested this several times. After setting org-startup-with-latex-preview to t, I restarted my Emacs to ensure that the problem persisted without this function, then eval'd it on a scratch buffer a second time. 
> The problem seems to be gone. 

Awesome!

> Magic! Your emacs-fu is advanced. :-)

Well thanks!
It was a joint effort!
Your perseverance and questions narrowed it down so thanks a bunch.

> So, if I paste this in my .emacs, then it will get eval'd every time I start emacs - a permanent monkey-patch. What do you think?

You can do that for the time being.
Up until i do a new release that is (i don't know when the next release will be yet).

Cheers and happy holidays,

**Comment by coyotespike** [comment]
Great, I'll do that, and close out this issue for the time being.

This was a pleasure.

Cheers and happy holidays!
