### ISSUE TITLE
Setup problem - Problem during credentials loading (consumer-key and read/write access-token)

### ISSUE THREAD

**Issue by peterstradinger** [org-trello/org-trello#306]
All my diagnostics check out and I'm able to read the boards. I'm clearly getting some data, but when I go to sync I get a permissions error. I checked the 

```org
:PROPERTIES:
#+PROPERTY: board-name pds_test
#+PROPERTY: board-id 5698...96b91b1
#+PROPERTY: DONE 5698...32dfd32
#+PROPERTY: TODO 56984...c33fff23
#+TODO: TODO | DONE
#+PROPERTY: orgtrello-user-myuser 5697db981....4cd
#+PROPERTY: :blue
#+PROPERTY: :purple
#+PROPERTY: :red
#+PROPERTY: :orange
#+PROPERTY: :yellow
#+PROPERTY: :green
#+PROPERTY: orgtrello-user-me myuser
:END:
```

This is from the applications portion of the account setting page.
```txt
org-trello
read and write access on all your boards
read and write access on all your teams
Approved: today at 4:45 PM
Never Expires
```

From the self-check
```txt
org-trello - Checking setup. DONE.
```
Can someone please give me guidance on what to check next? I looked at my config file, and there were no extra spaces or anything.

**Comment by ardumont** [comment]
Hello,

For reference's sake, can you please <kbd>M-x org-trello-bug-report</kbd>?

Otherwise, from what you describe, everything seems about right.

Is the `myuser` your trello user login?

Cheers,

**Comment by bsima** [comment]
@peterstradinger I had a similar issue because I used my email address instead of my username. Try:

`mv ~/.emacs.d/.trello/myemail@example.com.el ~/.emacs.d/.trello/myuser.el`

**Comment by jethrokuan** [comment]
Also fixed by using username instead of email
