### ISSUE TITLE
Be logged into multiple trello accounts at once

### ISSUE THREAD

**Issue by skebanga** [org-trello/org-trello#308]
When logged into Google with multiple accounts, you can access both inboxes as follows

    https://mail.google.com/mail/u/0/#inbox <-- inbox 1 (personal)
    https://mail.google.com/mail/u/1/#inbox <-- inbox 2 (work)

It would be very useful to be able to be logged into multiple trello accounts at the same time. 

AFAICS, this is not currently possible - going to trello.com automatically redirects you to a single logged in user's profile.

There is no way to log into another trello account at the same time

**Comment by ardumont** [comment]
Hello,

Sorry for the late reply, was out of reliable connection.

> ...
> It would be very useful to be able to be logged into multiple trello accounts at the same time.

Indeed.

> AFAICS, this is not currently possible - going to trello.com automatically redirects you to a single logged in user's profile.
> There is no way to log into another trello account at the same time

org-trello is not trello.
This is a feature request for the trello team.

org-trello does permit to use multiple account on a buffer (file) basis.
You can, for example, have 3 buffers with 3 different trello accounts (so long as you have installed those 3 credentials).

The only shortcoming i see is that if you use bindings that uses the browser (display a card, display the board, ...) you will hit the problem you mention... That is it will only work for one of the account you are actually logged-in in trello. So you will have extra steps to log out first and log in with the current account you want to use (and then use the bindings you want from the org buffer).

I cannot do anything about that.

Cheers,
