### ISSUE TITLE
org-trello not finding trello account

### ISSUE THREAD

**Issue by wmmurrah** [org-trello/org-trello#311]
I have installed org-trello as described on the website. I have the key and the token in the correct file. 
I am on Ubuntu 14.04 with Emacs 24.4.1, using Chromium. When I go to connect to a board with `C-c o I` I get

    Board to install (TAB to complete): [No match]

if I start typing a board it does not find a completion.

I also tried creating a board with `C-c o b` and it creates metadata, but is seems to be missing important
information: 

    :PROPERTIES:
    #+PROPERTY: board-name 
    #+PROPERTY: board-id 

    #+PROPERTY: orgtrello-user-me williammurrah
    :END:

So, it seems to me that org-trello is not finding my trello account. Any suggestions?

**Comment by ardumont** [comment]
Hello again,

> ...
> So, it seems to me that org-trello is not finding my trello account. Any suggestions?

Can you please give the result of <kbd>M-x org-trello-bug-report</kbd>?

There are multiple problem possibilities:
- credentials installation (filename which must be `~/.emacs.d/.trello/williammurrah.el` from what i gather of your extract, williammurrah must also be your trello login).

The content of such file should be along:

```lisp
(setq org-trello-consumer-key "abc")   ;; 32 characters string
(setq org-trello-access-token "def") ;; 64 characters string
```

- input completion mechanism (using helm/ido without it being installed for instance, default being using ido which is an emacs 24 default). 

Can you please also show me your customization?

<kbd>M-x customize-group RET org-trello RET</kbd> should give something along the line:

![2016-02-07_17-45-05](https://cloud.githubusercontent.com/assets/718812/12873625/aec415a0-cdc2-11e5-8f2b-19c42f7bdf62.png)

This will permit me to know which completion mechanism you use (for instance, i use helm and org-trello installation does not require it as dependencies so if you do, you must install it yourself).

**Comment by wmmurrah** [comment]
bug report:

```
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8)
 of 2015-12-03 on wmmurrah-Lenovo-V570
- org version: 8.3.3
- org-trello version: 0.7.5
- org-trello path: /home/wmmurrah/.emacs.d/elpa/org-trello-20160206.2342/org-trello.el
```

Customization:

```
For help using this buffer, see Easy Customization in the Emacs manual.

                                          Search 

Operate on all settings in this buffer:
 Revert...   Apply   Apply and Save 


Parent groups: Org

Org-trello group:  Org-trello customisation group.
       State : something in this group has been set and saved.
   
Hide Org Trello Current Prefix Keybinding: C-c o
    State : SAVED and set.
   The default prefix keybinding to execute org-trello commands.

Show Value Org Trello Files 
   Org-trello files that needs org-trello activated when opened. More

Show Value Org Trello Input Completion Mechanism 
   The completion mechanism the user can choose from. More

Show Value Org Trello Mode Hook 
   Define org-trello hook for user to extend mode with their own behavior.

Show Value Orgtrello Log Level 
   Set log level. More

Show Value Orgtrello Setup Use Position In Checksum Computation 
   Let the user decide if (s)he wants to use the position in the checksum. More

```
Thanks for your help

**Comment by ardumont** [comment]
Thanks, but i unfortunately miss some information...

Is your williammurrah.el file consistent with what i described?

What's the current value of `org-trello-input-completion-mechanism`?
From an org-buffer: <kbd>M-: org-trello-input-completion-mechanism RET</kbd>?

Thanks again,

**Comment by wmmurrah** [comment]
My williammurrah.el file does look the way you described.
Looking in the customize-group output, I get STANDARD. After `M:` command I get default.

**Comment by ardumont** [comment]
Ok, all is normal for now then.
Moving along...

What does this give you?

<kbd>M-x ielm RET</kbd>
(emacs lisp repl)

```lisp
(let ((org-trello--user-logged-in "williammurrah"))
  (orgtrello-controller-load-keys)
  (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
```

Is this working?
This should returns something along:

```lisp
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data
              (:username "will" :url **"https://trello.com/wil" :status "disconnected" :full-name "You" :id "24-string-identifier"))
```

This will permit to check the tokens are ok or not.

Cheers,

**Comment by wmmurrah** [comment]
I get nil

**Comment by ardumont** [comment]
> I get `nil`

mmm, this is not right but i don't get what's wrong.

> I have installed org-trello as described on the website.

Did you have the following screens show up during the install key and token process?
(Probably but still)

-- 

Ah, what does the following evaluation snippet return?

<kbd>M-: request-backend RET</kbd>

This is the backend that org-trello will use to query the trello api.

It's either 'curl or 'url-retrieve.

Thanks.

**Comment by wmmurrah** [comment]
I get curl

**Comment by wmmurrah** [comment]
I am also noticing the following error in the *Messages* buffer when I try to connect to a board

    org-trello - client - Problem during request - error-thrown: (error . exited abnormally with code 77)

**Comment by ardumont** [comment]
ahah.

from `man curl`, the error code 77 is:

```man
77     Problem with reading the SSL CA cert (path? access rights?).
```

>  so maybe it is something with my emacs setup on my Linux computer?

So this may be something around the computer setup indeed.

**Comment by ardumont** [comment]
# workaround

You can try to change the backend that request uses from 'curl to 'url-retrieve:

```lisp
(custom-set-variables '(request-backend 'url-retrieve))
```

Then try again:
```lisp
(let ((org-trello--user-logged-in "williammurrah"))
  (orgtrello-controller-load-keys)
  (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
```

But this sounds like a workaround.
To rollback:
```lisp
(custom-set-variables '(request-backend 'curl))
```

# better approach? (seems like it)

It's better to try and fix the ssl path access but i don't know much about these...

Apparently you can check what's your curl install used for certificates path with:

For example here is mine with emphasis on the ssl options that seems being problematic on your side:

```sh
# tony at corellia in ~ [14:22:21]
$ curl-config --configure | grep certs
 '--build=x86_64-linux-gnu' ... '--with-ca-path=/etc/ssl/certs' '--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt' ...
```

As a next step, check that the path exists and that your user have access to those.

Mine again:
```sh
# tony at corellia in ~ [14:25:25]
$ ls -ld /etc
drwxr-xr-x 172 root root 12288 Feb  9 12:45 /etc

# tony at corellia in ~ [14:25:29]
$ ls -ld /etc/ssl
drwxr-xr-x 4 root root 4096 Feb  7 13:15 /etc/ssl

# tony at corellia in ~ [14:25:32]
$ ls -ld /etc/ssl/certs
drwxr-xr-x 3 root root 24576 Jan 27 15:06 /etc/ssl/certs

# tony at corellia in ~ [14:25:36]
$ ls -ld /etc/ssl/certs/ca-certificates.crt
-rw-r--r-- 1 root root 274340 Jan 27 15:06 /etc/ssl/certs/ca-certificates.crt
```
Note: I'm on Debian right now, but no trouble on NixOS either.
Also, i never changed any of those default access rights.


If the path referenced by curl does not exist, i suppose defining an alias around the curl command line or better defining some environment variables as defined below could be an option:

```man
       --cacert <CA certificate>
              (SSL) Tells curl to use the specified certificate file to verify the peer. The file may contain multi‐
              ple CA certificates. The certificate(s) must be in PEM format. Normally curl is built to use a default
              file for this, so this option is typically used to alter that default file.

              curl  recognizes the environment variable named 'CURL_CA_BUNDLE' if it is set, and uses the given path
              as a path to a CA cert bundle. This option overrides that variable.

              The windows version of curl will automatically look for a CA certs  file  named  ´curl-ca-bundle.crt´,
              either  in the same directory as curl.exe, or in the Current Working Directory, or in any folder along
              your PATH.

              If curl is built against the NSS SSL library, the NSS PEM PKCS#11 module (libnsspem.so)  needs  to  be
              available for this option to work properly.

              If this option is used several times, the last one will be used.

       --capath <CA certificate directory>
              (SSL)  Tells curl to use the specified certificate directory to verify the peer. Multiple paths can be
              provided by separating them with ":" (e.g.  "path1:path2:path3"). The certificates must be in PEM for‐
              mat,  and  if curl is built against OpenSSL, the directory must have been processed using the c_rehash
              utility supplied with OpenSSL. Using --capath can allow OpenSSL-powered curl to  make  SSL-connections
              much more efficiently than using --cacert if the --cacert file contains many CA certificates.

              If  this option is set, the default capath value will be ignored, and if it is used several times, the
              last one will be used.
```

I'm no expert on these matters...
Hoping this helps anyway.

Cheers,

**Comment by wmmurrah** [comment]
The first work-around indeed worked, so I think you have identified the correct problem. But I am also not very familiar with the curl certificate procedures. So I will explore that issue as I have time. 

Thanks very much for your work on this. I look forward to using org-trello

**Comment by ardumont** [comment]
> The first work-around indeed worked, so I think you have identified the correct problem. 

That's progress :D

> But I am also not very familiar with the curl certificate procedures. So I will explore that issue as I have time.

Ok.
Don't forget to please drop a line if you find some time and you solve this.
This could help other people along the way.
Thanks in advance.

> Thanks very much for your work on this. I look forward to using org-trello

No problem.
Thanks for your feedback every step of the way.

Cheers,
