### ISSUE TITLE
adds keybindings without being asked to 

### ISSUE THREAD

**Issue by unhammer** [org-trello/org-trello#312]
org-trello-20160206.2342 from melpa takes over my "C-c o" keybinding, presumably due to https://github.com/org-trello/org-trello/blob/master/org-trello-tools.el#L237 which looks like debug leftovers

**Comment by ardumont** [comment]
Hello,

This should not happen.

org-trello-tools is a namespace for developers, not for production.
But indeed, i see that [the melpa recipe includes it](https://github.com/melpa/melpa/blob/master/recipes/org-trello#L3).

In the mean time (patching time of the recipe to exclude it), you should not try and use any 'orgtrello-tools-*' functions. Sorry for the inconsistency here.

Normally, the way to customize the prefix is [as described](http://org-trello.github.io/customize.html):

```lisp
(custom-set-variables
   '(org-trello-current-prefix-keybinding "C-c x")) ;; C-c x as the default prefix
```

What's the current value of `org-trello-current-prefix-keybinding`?

Cheers,

**Comment by unhammer** [comment]
nil

**Comment by ardumont** [comment]
> nil

Hum, i've missed your initial point.
org-trello does indeed define `C-c o` as default (nil defaults to `C-c o`).
[It's a beginner's mistake I made and did not dare change](https://github.com/org-trello/org-trello/issues/72).

Still, the proper way to customize [is as suggested](http://org-trello.github.io/bindings.html#prefix-binding-override) or [in this more global example](http://org-trello.github.io/customize.html).

Also, it should not take over on all your buffers... (that's what i understand from your sentence).
Only the ones where org-trello is activated (it should not always be that case).

**Comment by unhammer** [comment]
Yeah the emacs-lisp bindings still look like a mistake :-)

**Comment by ardumont** [comment]
> Yeah the emacs-lisp bindings still look like a mistake :-) 

My fault was that i did not know that 'C-c <letter>' was a prefix reserved for user-bindings only.

How do you think i could improve this? Thanks for any suggestion.

Cheers

**Comment by unhammer** [comment]
https://github.com/org-trello/org-trello/blob/master/org-trello-tools.el#L237  could probably be put into a function `org-trello-setup-debug-keybindings`. Regarding the `C-c' default when org-trello-minor-mode is on, that seems ok to me, as long as it only affects org-mode buffers and there's an option to change it …

**Comment by ardumont** [comment]
Ok, org-trello-tools is the problem here!
I did not measure the impact even though i talked about it this morning.
It defines hook which are ran... It is not intended that way.

So, the bug fix is actually to exclude it from melpa's recipe!

I [create the package for marmalade and I do not include it](https://github.com/org-trello/org-trello/blob/master/Cask#L5-L24).

Thanks!

Cheers,

**Comment by ardumont** [comment]
Hello, 

the recipe fix has been merged in melpa. Now, we can wait for melpa to rebuild the recipe and publish.
Then updating the package should fix your initial problem.

Cheers,

**Comment by unhammer** [comment]
Seems to have worked :-)
