### ISSUE TITLE
Don't give a library the generic name "utilities.el"

### ISSUE THREAD

**Issue by tarsius** [org-trello/org-trello#319]
`utilities.el` is a bad name for a library because any other package might come with a library by that name.

I am not sure how to best fix this. Maybe you should just merge `utilities.el` into `test/utilities-test.el`.

Currently there are at least two packages that contain a `utilities.el` library: this and [org2jekyll](https://github.com/ardumont/org2jekyll/pull/30). I hope both of them get fixed.

**Comment by ardumont** [comment]
Hello again,

> utilities.el is a bad name for a library because any other package might come with a library by that name.

Indeed.

> I am not sure how to best fix this. Maybe you should just merge utilities.el into test/utilities-test.el.

This sounds reasonable enough. 
Will do that. Thanks.

> Currently there are at least two packages that contain a utilities.el library: this and org2jekyll. I hope both of them get fixed.

org2jekyll is now fixed. Thanks again for that.

Cheers,

**Comment by tarsius** [comment]
Thanks!

**Comment by ardumont** [comment]
>>    I am not sure how to best fix this. Maybe you should just merge utilities.el into test/utilities-test.el.

> This sounds reasonable enough.
> Will do that. Thanks.

Not really what i did but still, the issue should no longer be.

I renamed:
- utilities.el to test/org-trello-tests.el
- test/utilities-test.el to test/org-trello-tests-test.el

Expanded the default .ert-runner load-path to also lookup the 'test/' folder.
And now everything is good.

Thanks @tarsius for raising this up.

Cheers,

**Comment by ardumont** [comment]
As proof: https://travis-ci.org/ardumont/org-trello/builds/111195446

**Comment by tarsius** [comment]
Did you intentionally push this only to your own repository?

**Comment by ardumont** [comment]
> Did you intentionally push this only to your own repository?

Yes, that's why it's not closed yet.
I'm doing a PR (per release) when i'm ready to make a new release for self review.
