### ISSUE TITLE
Freezes if trello buffer is huge

### ISSUE THREAD

**Issue by pavkum** [org-trello/org-trello#322]
Hello,
   First of all thank you for org-trello. 

  This may not be a bug or I may be handling incorrectly. I couldn't find help any where else, so creating as an issue here.

  After syncing my work board (~ 550k) emacs started freezing. I ran `C-u M-x org-trello-sync-buffer` which pulled everything from my board. I don't want all the cards in the board, how would I pull cards which are only related to me. 

  Also could you please provide information regarding `Remove entity`. Does it mean locally removing a card which I'm not interested in?

**Comment by ardumont** [comment]
Hello,

> First of all thank you for org-trello.

Thanks.

> After syncing my work board (~ 550k) emacs started freezing. 

Ok.
Not to be mean or something but like the issue template explained, <kbd>M-x org-trello-bug-report</kbd> would be a nice start...

> I ran C-u M-x org-trello-sync-buffer which pulled everything from my board. I don't want all the cards in the board, how would I pull cards which are only related to me.

Interesting question!
Well, you cannot. It retrieves all the board's information and writes it in the local buffer.

It could be a good idea to open a feature request about this!

> Also could you please provide information regarding Remove entity. 

Well, <kbd>C-c o h</kbd> or <kbd>M-x org-trello-help</kbd> on  says:
```
C-c o k - M-x org-trello-kill-entity - Kill the entity (and its arborescence tree) from the trello board and the org buffer.
```
There is also http://org-trello.github.io/bindings.html...

As a hint, you can `M-x org-trello-` and with some some super mode like helm you could see functions from org-trello (or other modes...).

![2016-03-13_21-01-06](https://cloud.githubusercontent.com/assets/718812/13730971/e04d2758-e95e-11e5-9b18-000d9ac38c82.png)

> Does it mean locally removing a card which I'm not interested in?

`from the trello board and the org-buffer`
No, it does not mean local removing.
It removes entity (card/checklist,item) from the trello board and then removes locally.
It removes with arborescence so a card will be removed along with checklists and items, a checklist will be removed along with its items, item is alone so only the item.

> This may not be a bug or I may be handling incorrectly. 
> I couldn't find help any where else, so creating as an issue here.

No problem.
This is the way to go ^^

Cheers,

**Comment by pavkum** [comment]
@ardumont : Thanks for the explanation.

Please debug trace below as requested.

- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.6)
 of 2015-09-18 on lgw01-52, modified by Debian
- org version: 8.2.10
- org-trello version: 0.7.8
- org-trello path: /home/pavan/.emacs.d/elpa/org-trello-0.7.8/org-trello.el
- request-backend: curl

I presume 550KB of buffer shouldn't cause any issue, am I correct?

**Comment by ardumont** [comment]
> Please debug trace below as requested.

Thanks.

> I presume 550KB of buffer shouldn't cause any issue, am I correct?

I would think so.
Then again, i never had the chance to test something like that.

Cheers,

**Comment by pavkum** [comment]
@ardumont I figured out the issue. The problem was with line numbers.

https://lists.gnu.org/archive/html/emacs-orgmode/2008-12/msg00224.html

I have disabled line numbers and everything works like a charm. 

Sorry for the trouble.

**Comment by ardumont** [comment]
> @ardumont I figured out the issue. The problem was with line numbers.

Cool.

> https://lists.gnu.org/archive/html/emacs-orgmode/2008-12/msg00224.html
> I have disabled line numbers and everything works like a charm.
> Sorry for the trouble.

Well, thanks. It's no trouble really.
Issue tracker are for stuff like this! And now it's referenced so it will be possibly help people in the future!

Cheers,
