### ISSUE TITLE
Support kanboard too

### ISSUE THREAD

**Issue by divansantana** [org-trello/org-trello#324]
Noticed this great extension. It really is awesome - nice! :)

### What do you want?

IMO, Kanboard[1] is another great piece of free software, very similar
to Trello, but is free software and can be self-hosted if one requires.
It's also a very active project.

As the Kanboard project is quite similar to trello, I was wondering if
it's feasible to request this software (org-trello) to support Kanboard
as well. API docs are here[2].

It's likely not and out of what this project is about. Nevertheless I thought I'd share the thought as it may be of interest to org and trello users.

### Why is it better?

This would be better because kanboard is (a) free software and can be internally hosted which benefits users that are concerned about security and privacy.

Feel free to close this issue/proposal.

[1]: http://kanboard.net/
[2]: http://kanboard.net/documentation/

**Comment by ardumont** [comment]
> Noticed this great extension. It really is awesome - nice! :)

Thanks.

> IMO, Kanboard1 is another great piece of free software, very similar
> to Trello, but is free software and can be self-hosted if one requires.

Definitely plusses over trello.

(from a dev standpoint, to run it locally can greatly improve testing.)

> As the Kanboard project is quite similar to trello, I was wondering if
it's feasible to request this software (org-trello) to support Kanboard
as well. API docs are here2.

This seems quite similar indeed.
I like it already ^^

> It's likely not and out of what this project is about. 

But, indeed, It's not org-trello's goal to be multi-backend.

> Nevertheless I thought I'd share the thought as it may be of interest to org and trello users.

Still, I completely agree, it is of high interest.

Either asking https://github.com/arbox/org-sync (which is multi backend) to add a new backend.
Or it's a new project altogether that needs to start.
For example, one dubbed org-kanboard (to be original).

> Feel free to close this issue/proposal.

Thanks for the heads up on kanboard!

Cheers,

**Comment by divansantana** [comment]
Great :) Thanks for the reply! :+1: 

Will check out https://github.com/arbox/org-sync too.
