### ISSUE TITLE
Due dates are being added to cards without any user intervention when I sync to trello.

### ISSUE THREAD

**Issue by sorter** [org-trello/org-trello#325]
Hello,

Can you please provide the following information?

Thanks in advance.

## bug?

Due dates are being added to cards without any user intervention when I sync to trello.

### M-x org-trello-bug-report
```
- Activate `'trace`' in logs for more thorough output in *Message* buffer: (custom-set-variables '(orgtrello-log-l\
evel orgtrello-log-trace)).
- A scrambled sample (of the user's and board's ids) of your org-trello buffer with problems.
- Report the following message trace inside your issue.

System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0)
 of 2015-12-20 on elcapitanvm.local
- org version: 8.2.10
- org-trello version: 0.7.8
- org-trello path: /Users/sykhader/.emacs.d/elpa/org-trello-0.7.8/org-trello.el
- request-backend: curl
```

### Expected behavior

Due dates should only be added to a card when I specifically assign one.

C-c o s

### Actual behavior

The first of the month is set as the due date to cards seemingly at random.

### Steps to reproduce the behavior

Add a new card to a board and sync to Trello.

**Comment by ardumont** [comment]
Hello,

Thanks for the thorough report.

> Due dates should only be added to a card when I specifically assign one.

I agree.
It's not org-trello's behavior to force a due date.

> The first of the month is set as the due date to cards seemingly at random.
> Add a new card to a board and sync to Trello.

I don't reproduce.

I tried with:
- an old board.
- a new board created for the occasion.

Ok, so i tried from trello to org (that is create a new card and sync from trello).
And now i understand you mean the other way around.

I was confused by the trello term again (when i read trello terms, card, board, etc... i still think of trello not of org).

Still, I confirm it's not org-trello's behavior.
I still don't reproduce.

Creating a simple card does not add due date.

You must have some org specific setup that triggers this (a hook might be a way for example).
Can you please check your emacs configuration?

Thanks

Cheers,

**Comment by sorter** [comment]
@ardumont Wow, thanks for the quick and thorough response! 
When it happens again I'll try to narrow down specific steps to reproduce the bug.

Here is my emacs configuration. 
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-trello-files '("/Users/sykhader/scratch/test-org/viceroy-trello.org"))
 '(org-enforce-todo-dependencies t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(setq browse-url-browser-function 'browse-url-default-macosx-browser)
(require 'package)
(add-to-list 'package-archives '("melpa-stable" . "http://melpa-stable.milkbox.net/packages/") t)
(package-initialize)
(require 'org-trello)
```

**Comment by ardumont** [comment]
> ...

Assuming your snippet is complete, I don't see anything fancy which could justify the described behavior.

org is extremely configurable to the point where local headers on your buffer can also have impacts on the current behavior. Can you please show me your org buffer headers?

Note: 
I believe the custom variable `org-log-done` has a behavior close to what is described here.
I activated it on my configuration https://github.com/ardumont/orgmode-pack/blob/master/orgmode-pack.el#L24 to have the time when the task is done but it's my conf not org-trello's :)

Cheers,

**Comment by sorter** [comment]
Admittedly I haven't run into the original issue since I reported it. 

However, there is another easily reproducible bug regarding deadlines that I'm encountering. Should I file it in a separate issue?

Bug: Removing a scheduled deadline via org-trello and syncing to Trello results in the deadline being changed to 12:00 AM of the current day.

Steps to reproduce:

1. Create a new board in org-trello via `C-c o b`
2. Create a card and sync it via `C-c o c`
3. Assign a deadline `C-c C-d` and sync it
4. Move to DONE and sync it
5. Remove scheduled deadline via `C-u C-c C-d` and sync the card
6. On Trello the card is assigned a new deadline (today at midnight)

Here is a screenshot of the Trello activity feed

![image](https://cloud.githubusercontent.com/assets/763548/14233284/03cb06c6-f992-11e5-9427-01c2b81ccc96.png)


P.S. -

I love org-trello and at the beginning of my next development cycle I plan to make time for contributing

**Comment by ardumont** [comment]
Hello,

Sorry for the delay. 
Ack on everything but just no time to deal with everything.

> Admittedly I haven't run into the original issue since I reported it. 

What changed between your tryouts? (emacs restarted or something?)

> Bug: ...

But no time just yet.

> However, there is another easily reproducible bug regarding deadlines that I'm encountering. Should I file it in a separate issue?

I think it's indeed a separate issue.
If you have the time to just copy your last comment into a new issue.
And reference this issue (add #325 in the new issue's text box) as the original point (no need to reference back your initial org-trello settings).

Thanks.

> I love org-trello and at the beginning of my next development cycle I plan to make time for contributing

This is awesome news!

Cheers,

**Comment by sorter** [comment]
Yeah I think it was an emacs restart that resolved the issue. I haven't encountered it since. My best guess is that I had org-log-done enabled temporarily.
