### ISSUE TITLE
Removing a scheduled deadline via org-trello and syncing to Trello results in the deadline being changed to 12:00 AM of the current day.

### ISSUE THREAD

**Issue by sorter** [org-trello/org-trello#326]
Hello,

Can you please provide the following information?

Thanks in advance.

## bug?

Removing a scheduled deadline via org-trello and syncing to Trello results in the deadline being changed to 12:00 AM of the current day.

First reported in #325 

### M-x org-trello-bug-report
```
- Describe your problem with clarity and conciceness (cf. https://www.gnu.org/software/emacs/manual/html_node/emacs/Understanding-Bug-Reporting.html)
- Explicit your installation choice (melpa, marmalade, el-get, tarball, git clone...).
- Activate `'trace`' in logs for more thorough output in *Message* buffer: (custom-set-variables '(orgtrello-log-level orgtrello-log-trace)).
- A scrambled sample (of the user's and board's ids) of your org-trello buffer with problems.
- Report the following message trace inside your issue.

System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0)
 of 2015-12-20 on elcapitanvm.local
- org version: 8.2.10
- org-trello version: 0.7.8
- org-trello path: /Users/sykhader/.emacs.d/elpa/org-trello-0.7.8/org-trello.el
- request-backend: curl
```

### Expected behavior

I was expecting the due date to be removed from the card.

### Actual behavior

deadline is changed to 12:00 AM of the current day.

### Steps to reproduce the behavior

1. Create a new board in org-trello via C-c o b
2. Create a card and sync it via C-c o c
3. Assign a deadline C-c C-d and sync it 
4. Move to DONE and sync it
5. Remove scheduled deadline via C-u C-c C-d and sync the card
6. On Trello the card is assigned a new deadline (today at midnight)

I have re-verified these steps at the time of submitting this as a stand-alone issue. Two screenshots of repeated occurrences are included below.

### What do you want?

Let's remove the deadline instead of resetting it to an undesired time.

### Why is it better?

This is better because it exactly matches the native org-mode functionality and is what the user expects.

Thanks for sharing!

Cheers,

![image](https://cloud.githubusercontent.com/assets/763548/14373642/332ad514-fd1a-11e5-8734-e6266f36e94d.png)
![image](https://cloud.githubusercontent.com/assets/763548/14373703/cb2b0848-fd1a-11e5-924a-62e2d1290c40.png)

**Comment by ardumont** [comment]
Hello,

> ...

I don't reproduce exactly this but... I have worse behavior. 
I am actually unable to remove the due date on trello's side.

Details, I can:
- create a deadline in org buffer and sync as due date in trello
- update a deadline in org buffer and sync as due date in trello
- retrieve the due date in org-buffer from trello
- but not delete from org-card and sync to trello, the due date remains in trello (bug)

So there definitely is something wrong in regards to org-deadline/trello-due-date mapping here.

...

Ok, i think i have found something for my case which must be related to yours.
Adding trace to the api function call:

```lisp
(trace-function 'orgtrello-api-move-card)      
;; (untrace-function 'orgtrello-api-move-card)  ;; to revert back to normal
```

Scenario:
- Adding a deadline/due-date and update card to trello, we see the due date as parameters:
```
======================================================================
1 -> (orgtrello-api-move-card "57075f2319bc53da237a1c45" "53fc6e1754c24b2ab5d5eef5" "Joy of FUN(ctional) LANGUAGES" "2016-04-30T09:50:00.000Z" #1="" "hello description
- with many
- lines

- including

- blanks lines
- lists
- with start or dash  are now possible
  - indentation too
" #1# 1114)
1 <- orgtrello-api-move-card: #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:params (("pos" . 1114) ("labels" . #1="") ("desc" . "hello description
- with many
- lines

- including

- blanks lines
- lists
- with start or dash  are now possible
  - indentation too
") ("due" . "2016-04-30T09:50:00.000Z") ("idMembers" . #1#) ("name" . "Joy of FUN(ctional) LANGUAGES") ("idList" . "53fc6e1754c24b2ab5d5eef5")) :method "PUT" :uri "/cards/57075f2319bc53da237a1c45"))
```

- Then removing the deadline/due date and sync to trello, it's no longer seen:
======================================================================
1 -> (orgtrello-api-move-card "57075f2319bc53da237a1c45" "53fc6e1754c24b2ab5d5eef5" "Joy of FUN(ctional) LANGUAGES" nil #1="" "hello description
- with many
- lines

- including

- blanks lines
- lists
- with start or dash  are now possible
  - indentation too
" #1# 1114)
1 <- orgtrello-api-move-card: #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:params (("pos" . 1114) ("labels" . #1="") ("desc" . "hello description
- with many
- lines

- including

- blanks lines
- lists
- with start or dash  are now possible
  - indentation too
") ("idMembers" . #1#) ("name" . "Joy of FUN(ctional) LANGUAGES") ("idList" . "53fc6e1754c24b2ab5d5eef5")) :method "PUT" :uri "/cards/57075f2319bc53da237a1c45"))
```

The fix should be to set the due to "" systematically (and not nil)

With the following fix:

```lisp
(defun orgtrello-api-move-card (card-id idList
                                        &optional name due id-members desc
                                        labels pos)
  "Create an update a card CARD-ID to IDLIST.
Optional NAME, DUE date, ID-MEMBERS, DESC, LABELS, POS query."
  (let ((due (if due due "")))  ;; hack: to remove the due date, it must be empty, not nil.
    (->> (orgtrello-api--deal-with-optional-values
          `((,name . ("name" . ,name))
            (,id-members . ("idMembers" . ,id-members))
            (,due . ("due" . ,due))
            (,desc . ("desc" . ,desc))
            (,labels . ("labels" . ,labels))
            (,pos . ("pos" . ,pos)))
          `(("idList" . ,idList)))
         (orgtrello-api-make-query "PUT" (format "/cards/%s" card-id)))))
```

Retrying the last step of removing the deadline, the deadline/due date appears in the api call as empty (see below) and the end result is that the deadline is out ^^:

```
======================================================================
1 -> (orgtrello-api-move-card "57075f2319bc53da237a1c45" "53fc6e1754c24b2ab5d5eef5" "Joy of FUN(ctional) LANGUAGES" nil #1="" "hello description
- with many
- lines

- including

- blanks lines
- lists
- with start or dash  are now possible
  - indentation too
" #1# 1114)
1 <- orgtrello-api-move-card: #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:params (("pos" . 1114) ("labels" . #1="") ("desc" . "hello description
- with many
- lines

- including

- blanks lines
- lists
- with start or dash  are now possible
  - indentation too
") ("due" . #1#) ("idMembers" . #1#) ("name" . "Joy of FUN(ctional) LANGUAGES") ("idList" . "53fc6e1754c24b2ab5d5eef5")) :method "PUT" :uri "/cards/57075f2319bc53da237a1c45"))
```

Can you please try to apply the fix i propose and check if this also fix fix your improper behavior?

Thanks for raising this up!

Cheers,

**Comment by sorter** [comment]
Unfortunately applying your patch doesn't seem to have worked. 

I attempted to comment out the version of `orgrello-api-move-card` and replace it with the version you provided within `org-trello-api.el` 

But when I re-attempt my steps to reproduce, the issue isn't resolved. Here is a screenshot of what occurred on the Trello activity feed.

Admittedly I need to refresh my elisp fluency but perhaps when removing the date via `C-u C-c C-d` the card is assigned a deadline we don't expect? Just a guess.

![image](https://cloud.githubusercontent.com/assets/763548/14390689/5e3476ea-fd86-11e5-9772-d8c9ecf4bb06.png)

**Comment by ardumont** [comment]
> Unfortunately applying your patch doesn't seem to have worked. 
> I attempted to comment out the version of orgrello-api-move-card and replace it with the version you provided within org-trello-api.el

I'm sorry i was not clearer ^^.
You need to evaluate the snippet i provided you with.
Not replace the existing one which won't have any effect.

To evaluate, for example, `M-: <paste-snippet-here> RET`.
![2016-04-08_19-33-31](https://cloud.githubusercontent.com/assets/718812/14392292/f4176bf6-fdc0-11e5-9596-cba4ab0ff9a6.png)

Now the function definition should be installed (just for your current emacs session).
Now try again ^^

> Admittedly I need to refresh my elisp fluency but perhaps when removing the date via C-u C-c C-d the card is assigned a deadline we don't expect? Just a guess.

It could but it's not implemented that way (with a decorator function around `org-deadline` for example).
Org-trello do not do anything when removing the deadline (it's org that is in charge).
It's the sync to trello which is in charge of sending the appropriate data to the server (trello).

Cheers,

**Comment by sorter** [comment]
I can confirm that your patch fixes the issue for my steps to reproduce!

Thank you for clarifying that I had to eval the new function value. 
Why is it that that replacing the existing one had no effect?

**Comment by ardumont** [comment]
> I can confirm that your patch fixes the issue for my steps to reproduce!

Cool!

> Thank you for clarifying that I had to eval the new function value.
> Why is it that that replacing the existing one had no effect?

emacs-lisp is just text. You need to make the runtime (here emacs') aware that the text means something and it's `eval` which does that :D 

(M-: is one of many ways to evaluate emacs-lisp expression within emacs)

Cheers,



Cheers,
