### ISSUE TITLE
Setup failed: (void-variable *consumer-key*)

### ISSUE THREAD

**Issue by oscarperpinan** [org-trello/org-trello#327]
Hello,

I have installed org-trello via melpa. The first step of the setup (credentials) works correctly. However, I am not able to connect an org-mode buffer to a board. When I use `M-x org-trello-install-board-metadata` I get the error message:

>  `Symbol's value as variable is void: *consumer-key*`.

This is confirmed with `org-trello-check-setup`, that gives:

> `org-trello- Checking setup. FAILED. Error: (void-variable *consumer-key*)`

This is my system information (as provided by `org-trello-bug-report`)
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.6)
 of 2016-01-22 on binet, modified by Debian
- org version: 8.3.4
- org-trello version: 0.7.8
- org-trello path: /home/oscar/.emacs.d/elpa/org-trello-20160301.941/org-trello.el
- request-backend: curl

Thanks in advance for your help.

Oscar.

**Comment by ardumont** [comment]
Hello,

> I have installed org-trello via melpa. The first step of the setup (credentials) works correctly. > However, I am not able to connect an org-mode buffer to a board. When I use M-x org-trello-install-board-metadata I get the error message:
> ```
> Symbol's value as variable is void: *consumer-key*.
> ```

Can you please evaluate the following snippet of code and show the result (anonymize the values)?

```lisp
(let ((username "oscarperpinan"))
  (with-temp-buffer
    (insert-file-contents (orgtrello-controller-config-file username))
    (buffer-string)))
```

This will evaluate the snippet which will load the content of the configuration file for your trello user and dump the output of the file inside the scratch buffer.

Note:
I assumed https://trello.com/oscarperpinan as your trello login which matches your github avatar :D )

Mine with username `ardumont` is something like:

```lisp
"(setq org-trello-consumer-key \"123\")
(setq org-trello-access-token \"456\")
"
```
Note: I changed my values.

To evaluate emacs-lisp snippet, for example, place yourself in a scratch buffer and:
<kbd>C-u M-: <paste-snippet-here> RET</kbd>.

--

The background about `*consumer-key*.
It's is an old variable used for storing the consumer-key. It's no longer used but kept for legacy reasons. It should not interfere for new installation...

Cheers,

**Comment by oscarperpinan** [comment]
Hi,

You are right about my trello username. So this is the result of the snippet (with anonymous values):

> "(setq org-trello-consumer-key \"xyz\"
>              org-trello-access-token \"abc\")"

Thanks!

Oscar.

**Comment by ardumont** [comment]
> ```
> "(setq org-trello-consumer-key \"xyz\"
> org-trello-access-token \"abc\")"
> ```

Mmm, there is something i don't get.
I don't reproduce. Started from scratch, that is:
- destroy ~/.emacs.d/.trello
- trigger install key and token
- then triggering install board and metadata.
I do have access to my list of boards to choose from...

So, looking at the code, the only stuff that uses this is https://github.com/org-trello/org-trello/blob/master/org-trello-controller.el#L102.
It's a function to migrate old configuration file path (~/.trello) to the actual and correct one (~/.emacs.d/.trello). I speak in unix term but it's the same way on other platform.

And the code that tries to look at *consumer-key* is evaluated if ~/.trello folder exists - https://github.com/org-trello/org-trello/blob/master/org-trello-controller.el#L100.

So quick question, do you have a ~/.trello folder?

Cheers,

**Comment by oscarperpinan** [comment]
Yes! That was the reason.
Now it works perfectly. Thanks a lot.

**Comment by ardumont** [comment]
> Yes! That was the reason.
> Now it works perfectly. Thanks a lot.

Cool!

**Comment by bhyde** [comment]
I encountered the same issue.  After stepping thru the oauth process.   After reading the above I discoverd I had both a ~/.emacs.d/.trello/foo1.el file (with the correct developer key info), and a ~/.trello file with earmuff developer keys for somebody else
```
(setq *consumer-key* "58b...585")
(setq *access-token* "6e3...7cd")
```
I moved ~/.trello aside and things appear to be working now.  My insta-theory(tm): the package I download didn't have that info cleared out before it was built.  This is version 0.7.9

**Comment by ardumont** [comment]
Hello,

> I encountered the same issue. After stepping thru the oauth process. After reading the above I discoverd ...

Thanks for your feedback!

> the package I download didn't have that info cleared out before it was built. 

I'm not sure i understand your theory.
~/.trello is not packaged.

(And if it is, it's not me that did the package :D)

In the past (no longer remember when), ~/.trello was generated by trello through user impulse (<kbd>M-x org-trello-install-key-and-token</kbd>). The user still uses this routine for setup installation, those information are just stored elsewhere (see below).

When I realized that it was not in emacs' good conventions to let such configuration in the HOME user, i changed that setup and made a migration routine to the new scheme for existing installation setup. The new setup is that configuration file are stored at: **~/.emacs.d/.trello/<trello-login>.el**.

(To be exhaustive, the few times, IIRC, when it was hand-written by the user would have been in the first 2 or 3 versions of org-trello, that's a long time ago :)

Anyway, a good workaround is indeed about this is:
- Remove ~/.trello (or simply move for later analysis)
- <kbd>M-x org-trello-install-key-and-token</kbd>

Cheers,

**Comment by bhyde** [comment]
Looking at my Time Machine backup I can see that this ~/.trello folder and it's contents are dated Apr 2004.  So yes my insta-theory that slandered the packaging was wrong.
