### ISSUE TITLE
Add an (optional) confirmation on org-trello-kill-cards

### ISSUE THREAD

**Issue by arichiardi** [org-trello/org-trello#330]
Hello,

Can you please provide the following information?

Thanks in advance.

## bug?
No

## Improvements?
Yes, just one.

### What do you want?
I would like to suggest to add an additional confirmation or `org-trello-kill-cards`, and yes, I have been bitten by this. Given that the `org-trello` is very handy though, I was able to create back all the cards by erasing `:orgtrello-id:` and `:orgtrello-local-checksum:` in `PROPERTIES`. Another idea would be to add an automatic function that does the property deletion for each individual card for you so that you can recreate them when accidentally deleted. Some sort of undo but of course specifying that the cards will have a new owner/creator.

### Why is it better?
It is a safety net against dumbness like mine above.

Thanks for you work!

**Comment by ardumont** [comment]
> I would like to suggest to add an additional confirmation or org-trello-kill-cards

This sounds completely reasonable.

Cheers,

**Comment by arichiardi** [comment]
Awesome, thanks for the prompt patch!

**Comment by ardumont** [comment]
> Another idea would be to add an automatic function that does the property deletion for each individual card for you so that you can recreate them when accidentally deleted. Some sort of undo but of course specifying that the cards will have a new owner/creator.

I realize i did not answer that part.
You could use emacs' undo and then clean up manually the properties (there is one function which does it on all the buffer (i don't remember its name... <kbd>M-x org-trello-delete-setup</kbd>) but that must not be what you want.

(If you are familiar with git) Also, i'm kind of using git for my org buffers, so when i do something wrong and i just can't make up a clean undo step, i just clean the unstaged changes...

Still, if you want that second part, please create a new issue.
I like to have one idea per issue, it makes the thread clearer.

Cheers,

**Comment by arichiardi** [comment]
Ok I will check `org-trello-delete-setup` and open a new issue in case. For now everything is good and I am using it pretty well. If I find some other problem I will report it but it is a very neat tool indeed.
Thanks!
