### ISSUE TITLE
org-trello - No card(s) to sync.

### ISSUE THREAD

**Issue by bimawa** [org-trello/org-trello#336]
Hi i'm connect org-trello to board with tickets, but after <kbd>M-x org-trello-sync-buffer</kbd>

This my bug-log:

```
The mark is not set now, so there is no region
org-trello - Request ’sync org buffer to trello board’...
Loading /Users/bimawa/.emacs.d/.trello/bimawa.el (source)...done
org-trello - Synchronizing org-mode file to board ’TestEmacsBoard’. This may take some time, some coffee may be a good idea...
org-trello - No card(s) to sync.
org-trello - Please:
- Describe your problem with clarity and conciceness (cf. https://www.gnu.org/software/emacs/manual/html_node/emacs/Understanding-Bug-Reporting.html)
- Explicit your installation choice (melpa, marmalade, el-get, tarball, git clone...).
- Activate ‘’trace‘’ in logs for more thorough output in *Message* buffer: (custom-set-variables ’(orgtrello-log-level orgtrello-log-trace)).
- A scrambled sample (of the user’s and board’s ids) of your org-trello buffer with problems.
- Report the following message trace inside your issue.

System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1004))
 of 2016-10-19
- org version: 8.3.6
- org-trello version: 0.7.9
- org-trello path: /Users/bimawa/.emacs.d/elpa/org-trello-20160604.645/org-trello.el
- request-backend: curl
Aborting an helm session running in background
Quit

```

**Comment by ardumont** [comment]
Hello,

```
org-trello - Synchronizing org-mode file to board ’TestEmacsBoard’. This
may take some time, some coffee may be a good idea...
org-trello - No card(s) to sync.
```

M-x org-trello-sync-buffer pushes the cards from your org buffer *to* the
trello board.
Apparently, you have nothing on your org buffer.

The other way around, pull *from* trello to org buffer, is `C-u M-x
org-trello-sync-buffer` as explained in
http://org-trello.github.io/bindings.html.
(`C-u` being emacs' universal modifier).

Cheers,

tony / @ardumont

**Comment by bimawa** [comment]
@ardumont wow thx

**Comment by ardumont** [comment]
> @ardumont wow thx

You are welcome :D

Cheers,

**Comment by bimawa** [comment]
@ardumont Maybe you know, in spacemacs i'm must use <kbr>SPC SPC org-trello-sync-buffer C-u RET</kbr> how can i rebind C-u for easy use? Just spacemacs community silent to give me advice ^_^

**Comment by ardumont** [comment]
Hello,

> how can i rebind C-u for easy use? 

I don't think it's spacemacs specific. It's emacs.
Maybe [this](http://stackoverflow.com/questions/4808756/how-do-you-move-the-prefix-argument-to-a-different-key-in-emacs) can help.
I did not try though.

> Just spacemacs community silent to give me advice ^_^

They might not know.

Cheers,

**Comment by bimawa** [comment]
@ardumont YES! Thanks for the tip. <kbr>C-u</kbr> in sapcemacs <kbr>SPC-u</kbr> now work all!
