### ISSUE TITLE
Sync from Trello to org buffer fails on a fresh setup.

### ISSUE THREAD

**Issue by rekado** [org-trello/org-trello#337]
### M-x org-trello-bug-report

```
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9)
 of 2016-11-22
- org version: 9.0.1
- org-trello version: 0.7.9
- org-trello path: /home/rekado/.guix-profile/share/emacs/site-lisp/guix.d/my-emacs-org-trello-0.7.9/org-trello.el
- request-backend: url-retrieve
```
### Expected behavior

I expected my board to be synchronized to the org buffer.

### Actual behavior

Only one card was transferred.  This message was displayed:

```
org-trello - Sync trello board ’Snippets’ to buffer ’trello.org’... FAILED. Error: "Invalid function: (region region)"
```
Here's the full output:

```
org-trello - Request ’sync org buffer from trello board’...
Loading /home/rekado/.emacs.d/.trello/rekado.el (source)...done
org-trello - Sync trello board ’Snippets’ to buffer ’trello.org’...
Contacting host: api.trello.com:443 [2 times]
org-trello - Computing card ’A’ data...
org-trello - Computing card ’B’ data...
org-trello - Computing card ’C’ data...
org-trello - Computing card ’D’ data...
org-trello - Computing card ’E’ data...
org-trello - Computing card ’R’ data...
org-trello - Synchronizing entity ’A’ with id ’583966ff840566b724fa9d5c’...
org-trello - Sync trello board ’Snippets’ to buffer ’trello.org’... FAILED. Error: "Invalid function: (region region)"
```

### Steps to reproduce the behavior

After initial setup and connecting an empty buffer to a board use `C-u C-c o s` to attempt to synchronize the board from Trello to the org buffer.

I get the same error when running `(orgtrello-buffer-card-checksum)`.  Here's the debugger backtrace:

```
Debugger entered--Lisp error: (invalid-function (region region))
  (region region)("trello.org")
  orgtrello-buffer--compute-string-for-checksum((490 572))
  orgtrello-buffer-compute-generic-checksum(orgtrello-entity-card-region)
  orgtrello-buffer-card-checksum()
  eval((orgtrello-buffer-card-checksum) nil)
  eval-expression((orgtrello-buffer-card-checksum) nil)
  funcall-interactively(eval-expression (orgtrello-buffer-card-checksum) nil)
  #<subr call-interactively>(eval-expression nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-expression nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-expression nil nil))
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by ardumont** [comment]
Hello,

Thanks for the thorough report.

I don't reproduce this issue yet.

My configuration is almost the same as yours:
```
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.31)
 of 2016-10-31
- org version: 8.3.6
- org-trello version: 0.7.9
- org-trello path: /nix/store/dnm3h75mmkinys9333dqq8skzsagi8jq-emacs-packages-deps/share/emacs/site-lisp/elpa/org-trello-20160604.645/org-trello.el
- request-backend: curl
```

The main differences i see are:
- the gtk lib emacs is compiled against (don't think this is a problem).
- I use nix instead of guix (guix being inspired from nix, i don't think that poses a problem either)
- org-mode is still 8.3.6 (the trouble may lie there)

So i need to check how to upgrade org to check the reproducibility.

Reading through the backtrace you showed me though, i thought of an api breaking change between emacs-24 and emacs-25 (already seen at least one in #335) but i should also have the issue...

Or it's also possible it's that and your emacs' compiled version from 22/11/2016 contains one api breaking change that mine, compiled before that, the 31/10/2016 does not...

So i also need to check and compile a later version of emacs to check the reproducibility.

Cheers,

**Comment by rekado** [comment]
Antoine R. Dumont <notifications@github.com> writes:

> My configuration is almost the same as yours:
> ```
> System information:
> - system-type: gnu/linux
> - locale-coding-system: utf-8-unix
> - emacs-version: GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.31)
>  of 2016-10-31
> - org version: 8.3.6
> - org-trello version: 0.7.9
> - org-trello path: /nix/store/dnm3h75mmkinys9333dqq8skzsagi8jq-emacs-packages-deps/share/emacs/site-lisp/elpa/org-trello-20160604.645/org-trello.el
> - request-backend: curl
> ```

Nice to see you’re using Nix :)

> The main differences i see are:
> - the gtk lib emacs is compiled against (don't think this is a problem).
> - I use nix instead of guix (guix being inspired from nix, i don't think that poses a problem either)
> - org-mode is still 8.3.6 (the trouble may lie there)

I have also tried this again after uninstalling Org mode (thereby
defaulting to the built-in Org-mode 8.x), but I got the same error.

> Reading through the backtrace you showed me though, i thought of an api breaking change between emacs-24 and emacs-25 (already seen at least one in #335) but i should also have the issue...
>
> Or it's also possible it's that and your emacs' compiled version from 22/11/2016 contains one api breaking change that mine, compiled before that, the 31/10/2016 does not...
>
> So i also need to check and compile a later version of emacs to check the reproducibility.

What exact version of Emacs do you use?  I could build that here and
check if I still see the error then.

I also tried starting Emacs with “emacs -Q” and only loading org-trello
and dependencies, but the problem is exactly the same as before: the
first card is synchronized and then it fails with “Invalid function:
(region region)”

-- 
Ricardo

GPG: BCA6 89B6 3655 3801 C3C6  2150 197A 5888 235F ACAC
http://elephly.net

**Comment by ardumont** [comment]
> Nice to see you’re using Nix :)

Well, and you guix :D

> What exact version of Emacs do you use? I could build that here and check if I still see the error then.

Well, i use whatever the latest nix-channel version i got.
```
$ nix-channel --version
nix-channel (Nix) 1.11.2
$  nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

My emacs function is https://github.com/ardumont/dot-files/blob/master/nixos/emacs.nix
(if that makes sense to you)

--

i finally successfully have an emacs version which match yours.
(I have a real slow network...)

```
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.31)
 of 2016-11-28
- org version: 9.0.1
- org-trello version: 0.7.9
- org-trello path: /nix/store/fjr6s0hiln1bdqfivrlh65m6ppd1sw1j-emacs-packages-deps/share/emacs/site-lisp/elpa/org-trello-20160604.645/org-trello.el
- request-backend: curl
```

Anyway, i still don't reproduce this.
So my assertions are wrong, which is progress :D

Can you please provide a sample of your buffer?
There might lie the problem.

Cheers,

**Comment by ExMateria** [comment]
I'm getting a similar problem, my buffer looks like 

:PROPERTIES:
#+PROPERTY: board-name Dailies
#+PROPERTY: board-id 5930f3e2b4583f56ab95178b
#+PROPERTY: Done 5930f3e8eeb842fe413009b4
#+PROPERTY: Doing 5930f3e88238b088b77ff28e
#+PROPERTY: To-Do 5930f3e7940adbc2555793cf
#+TODO: To-Do Doing | Done
#+PROPERTY: orgtrello-user-supercriticalfluid 4ffb72686f4c2e3c5f010cf0
#+PROPERTY: :blue
#+PROPERTY: :purple
#+PROPERTY: :red
#+PROPERTY: :orange
#+PROPERTY: :yellow
#+PROPERTY: :green
#+PROPERTY: orgtrello-user-me supercriticalfluid
:END:

-*-org-*-

* IN-PROGRESS Joy of FUN(ctional) LANGUAGES
  - [-] LISP
    - [X] Emacs-Lisp
    - [X] Common-Lisp
    - [ ] Scheme
    - [X] Clojure
  - [X] ML
    - [X] Haskell
    - [X] Ocaml
  - [X] Hybrid
    - [X] Scala
  - [ ] little more detail, this is level 2, so checklist in trello board
    - [ ] item 3
      - [ ] any entities with level superior to 4 are considered level 3

with these versions - 
- NixOS 17.09pre106299.7f3b857d0d (Hummingbird) 64-bit
- Org mode version 9.0.5 (9.0.5-elpa @ /nix/store/67b7r69w0gznznxhybnhgf06cfsvk1r9-emacs-packages-deps/share/emacs/site-lisp/elpa/org-20170210/)
- GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.12) of 2017-04-27
- org-trello - version: 0.8.0

I get the following when I try to update

org-trello - Request ’sync org buffer from trello board’...
Loading /home/asenath/.emacs.d/.trello/myemail.el (source)...done
org-trello - Sync trello board ’Dailies’ to buffer ’dailies’... FAILED. Error: (invalid-function (region region))

**Comment by gjw** [comment]
Essentially the same thing on a fairly different install.

- Check setup reports ok, but buffers won't sync. Org-trello actually connects, sees the appropriate boards, sets the properties... and then can never sync, either way.

- ‘’trace‘’ 
```
org-trello - Request ’sync org buffer to trello board’...
Loading /Users/xx/.emacs.d/.trello/xx.el (source)...done
org-trello - Synchronizing org-mode file to board ’outstanding’. This may take some time, some coffee may be a good idea...
helm-M-x: Invalid function: (region region)
```

System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.2.1 (x86_64-apple-darwin16.6.0, Carbon Version 157 AppKit 1504.83)
 of 2017-05-26
- org version: 9.0.8
- org-trello version: 0.8.0
- org-trello path: /Users/xx/.emacs.d/elpa/org-trello-20170225.1247/org-trello.el
- request-backend: curl
- kill-whole-line: nil

**Comment by gjw** [comment]
Wew.  Actually, fixed it for me.

The 8.2.10 org from the brew install was breaking the 9.0.8 elpa install.
Destroyed the `share/emacs/25.2/lisp/org`, restarted, immediately fixed.

**Comment by sleep-walker** [comment]
It seems I face the same problem but removing emacs' org code doesn't help me.

termux environment, emacs-25.2,
current elpa packages
 * org 9.0.8-elpa
 * org-trello 0.8.0

**Comment by sleep-walker** [comment]
Surprisingly, on some other machine with same distribution, same emacs package, same org and org-trello package it works.

**Comment by sleep-walker** [comment]
trace doesn't seem to be useful:
```
org-trello - Hello master, help is ‘M-x org-trello-help-describing-bindings RET’ or ‘C-c o h’.
org-trello - Request ’sync entity with structure to trello...
Loading /home/tcech/.emacs.d/.trello/tomascech1.el (source)...done
orgtrello-buffer--compute-string-for-checksum: Invalid function: (region region)
nil
org-trello - Request ’sync org buffer from trello board’...
Loading /home/tcech/.emacs.d/.trello/tomascech1.el (source)...done
org-trello - Sync trello board ’org-trello bughunting’ to buffer ’org-trello-bughunting-trello.org’...
org-trello - Response: [cl-struct-request-response 200 nil nil nil success "https://api.trello.com/1/boards/593f1196683e4767dbaef026/cards?key=0123456789abcdef0123456789abcdef&token=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef&filter=closed&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos" nil (:sync t :type "GET" :params ((key . "0123456789abcdef0123456789abcdef") (token . "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef") ("filter" . "closed") ("fields" . "closed,desc,due,idBoard,idList,idMembers,labels,name,pos")) :parser orgtrello-query--http-parse :success orgtrello-query--standard-success-callback :error orgtrello-query--standard-error-callback :url "https://api.trello.com/1/boards/593f1196683e4767dbaef026/cards?key=0123456789abcdef0123456789abcdef&token=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef&filter=closed&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos" :response #0) #<killed buffer> "HTTP/2 200 
cache-control: max-age=0, must-revalidate, no-cache, no-store
x-content-type-options: nosniff
strict-transport-security: max-age=15768000
x-xss-protection: 1; mode=block
x-frame-options: DENY
x-trello-version: 1.978.0
x-trello-environment: Production
access-control-allow-origin: *
access-control-allow-methods: GET, PUT, POST, DELETE
access-control-allow-headers: Authorization, Accept, Content-Type
x-server-time: 1497305844607
expires: Thu, 01 Jan 1970 00:00:00
content-type: application/json; charset=utf-8
content-length: 2
etag: W/\"2-d4cbb29\"
vary: Accept-Encoding
date: Mon, 12 Jun 2017 22:17:24 GMT
" nil curl nil]
org-trello - Data: nil
org-trello - Response: [cl-struct-request-response 200 nil (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:id "593f1280644edbb53a532806" :closed nil :desc "" :due nil :board-id "593f1196683e4767dbaef026" :list-id "593f12180566afb5a5e51063" :member-ids nil :labels nil :name "blue bug" :position 65535 :comments nil :checklists nil :level 1)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:id "593f12841a5aa7ce9ec77202" :closed nil :desc "" :due nil :board-id "593f1196683e4767dbaef026" :list-id "593f12180566afb5a5e51063" :member-ids nil :labels nil :name "lady bug" :position 131071 :comments nil :checklists nil :level 1))) nil success "https://api.trello.com/1/boards/593f1196683e4767dbaef026/cards?key=0123456789abcdef0123456789abcdef&token=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef&actions=commentCard&checklists=all&filter=open&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos" nil (:sync t :type "GET" :params ((key . "0123456789abcdef0123456789abcdef") (token . "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef") ("actions" . "commentCard") ("checklists" . "all") ("filter" . "open") ("fields" . "closed,desc,due,idBoard,idList,idMembers,labels,name,pos")) :parser orgtrello-query--http-parse :success orgtrello-query--standard-success-callback :error orgtrello-query--standard-error-callback :url "https://api.trello.com/1/boards/593f1196683e4767dbaef026/cards?key=0123456789abcdef0123456789abcdef&token=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef&actions=commentCard&checklists=all&filter=open&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos" :response #0) #<killed buffer> "HTTP/2 200 
cache-control: max-age=0, must-revalidate, no-cache, no-store
x-content-type-options: nosniff
strict-transport-security: max-age=15768000
x-xss-protection: 1; mode=block
x-frame-options: DENY
x-trello-version: 1.978.0
x-trello-environment: Production
access-control-allow-origin: *
access-control-allow-methods: GET, PUT, POST, DELETE
access-control-allow-headers: Authorization, Accept, Content-Type
x-server-time: 1497305844943
expires: Thu, 01 Jan 1970 00:00:00
content-type: application/json; charset=utf-8
content-length: 460
etag: W/\"1cc-2dba9c4a\"
vary: Accept-Encoding
date: Mon, 12 Jun 2017 22:17:24 GMT
" nil curl nil]
org-trello - Data: (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:id "593f1280644edbb53a532806" :closed nil :desc "" :due nil :board-id "593f1196683e4767dbaef026" :list-id "593f12180566afb5a5e51063" :member-ids nil :labels nil :name "blue bug" :position 65535 :comments nil :checklists nil :level 1)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:id "593f12841a5aa7ce9ec77202" :closed nil :desc "" :due nil :board-id "593f1196683e4767dbaef026" :list-id "593f12180566afb5a5e51063" :member-ids nil :labels nil :name "lady bug" :position 131071 :comments nil :checklists nil :level 1)))
org-trello - Archived trello-cards: nil
org-trello - Opened trello-cards: (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:id "593f1280644edbb53a532806" :closed nil :desc "" :due nil :board-id "593f1196683e4767dbaef026" :list-id "593f12180566afb5a5e51063" :member-ids nil :labels nil :name "blue bug" :position 65535 :comments nil :checklists nil :level 1)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:id "593f12841a5aa7ce9ec77202" :closed nil :desc "" :due nil :board-id "593f1196683e4767dbaef026" :list-id "593f12180566afb5a5e51063" :member-ids nil :labels nil :name "lady bug" :position 131071 :comments nil :checklists nil :level 1)))
org-trello - Sync trello board ’org-trello bughunting’ to buffer ’org-trello-bughunting-trello.org’... FAILED. Error: (invalid-function (region region))
```

**Comment by ardumont** [comment]
Hello,

First and foremost, thanks all for trying to investigate this!
This helps!

> The 8.2.10 org from the brew install was breaking the 9.0.8 elpa install.
> Destroyed the share/emacs/25.2/lisp/org, restarted, immediately fixed.

I don't know what to say here but wow! Nice catch!
It seems to not be a good idea to use both the distribution's package system (homebrew here) and some kind emacs's (elpa)...

Nonetheless, still, nice catch!
Thanks for raising and answering!

> trace doesn't seem to be useful:

I'm not so sure about that :)

I see this:
> orgtrello-buffer--compute-string-for-checksum: Invalid function: (region region)

And looking at the definition of that function, the first few line might match the error:

```
(defun orgtrello-buffer--compute-string-for-checksum (region)
  "Given a REGION, compute the string to checksum."
  (lexical-let ((region region) ...
```

Is `lexical-let` define on your machine?

Cheers,

**Comment by sleep-walker** [comment]
> Is lexical-let define on your machine?

My emacs-fu is weak but as symbol it is offered with completion and in ielm this works without error:
```
ELISP> (lexical-let ((x 1)))
nil
```

**Comment by ardumont** [comment]
> My emacs-fu is weak but as symbol it is offered with completion and in ielm this works without error:

bummer

**Comment by sleep-walker** [comment]
After a _lot of_ experiments and bisecting configuration I believe that the problem is in org-trello-buffer.elc. If this byte-compiled file is deleted, it works for me. Also `byte-compile-file` generates file, which no longer has this issue.

It doesn't seem that reported bug is related to org-trello but either my lack of knowledge of byte code files reusability on other machines or in generator itself. Time to learn more.

**Comment by sleep-walker** [comment]
OK, it seems that elc was generated in different condition and I need to bisect once again to find the real issue.

**Comment by EgZvor** [comment]
@sleep-walker yeah, didn't help me to remove any of the compiled files.

**Comment by sleep-walker** [comment]
Sorry, I no longer can reproduce the issue without `org-trello-buffer.elc`. Problematic conditions are gone.

**Comment by ardumont** [comment]
For information, for my part, the byte-compilation step is done by emacs at package installation time.

@EgZvor  @sleep-walker That begs the question, how did you install yours?

**Comment by EgZvor** [comment]
@ardumont it should work without those though, right?

**Comment by ardumont** [comment]
> @ardumont it should work without those though, right?

Probably.
I think it really depends on how you install it (emacs' load-path and everything)...

For my part, for development purposes, i use the [org-trello-tools namespace](https://github.com/org-trello/org-trello/blob/master/org-trello-tools.el) to help in loading those files. 
But it's manual step needed to be done each time, so i don't recommend this approach for real use.

**Comment by sleep-walker** [comment]
> @sleep-walker That begs the question, how did you install yours?
I copied ~/.emacs* to Termux environment in one case, in second case normal installation via `package-list-packages`.

Is it possible that you don't have specified all the dependencies at package management level so recompilation wasn't triggered when it should?

**Comment by ardumont** [comment]
> Is it possible that you don't have specified all the dependencies at package management level so recompilation wasn't triggered when it should?

Any error is possible.
The package dependencies are defined in [org-trello.el#L8](https://github.com/org-trello/org-trello/blob/master/org-trello.el#L8).

I tested the package installation back in the day i did it. 
Everything worked as expected.
Also in installing it again here, all is well.

> OK, it seems that elc was generated in different condition and I need to bisect once again to find the real issue.

One can check the **Compile-log** buffer after installation step (through emacs' "standard" package install). Maybe there were some errors referenced at the install time and that's why you got a scrambled `org-trello-buffer.elc`...

**Comment by declanqian** [comment]
Same error message here. After that reinstall `org-trello` everything works fine now.

**Comment by remcogerlich** [comment]
I had this issue today as well, with Emacs 25.2.2 and its builtin org-mode, and org-trello from MELPA. When I also installed org-mode from MELPA (and deleted my ~/.emacs.d/elpa so that everything reinstalled), the problem disappeared; only deleting org-trello wasn't enough.
