### ISSUE TITLE
Cannot sync with board after installing metadata due to credential loading error

### ISSUE THREAD

**Issue by holocronweaver** [org-trello/org-trello#343]
### M-x org-trello-bug-report

System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.91.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2017-01-18
- org version: 9.0.3
- org-trello version: 0.7.9
- org-trello path: /home/jesse/.emacs.d/elpa/org-trello-20160604.645/org-trello.el
- request-backend: curl

### Expected behavior

After installing metadata into an org buffer, `C-u M-x org-trello-sync-buffer` should sync my org buffer with the associated trello board.

### Actual behavior

I receive the error ` - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token`. However, that step was already done and was used to install the metadata in the firstplace using `org-trello-install-board-metadata`. I inspected the credential file and it is indeed in `~/.emacs.d/.trello/holocronweaver.el`.

Setting the org-trello trace to 5 did not produce any additional output.

### Steps to reproduce the behavior

My trello board is private, but here is the entire contents of my org file (sans my name):

> :PROPERTIES:
> #+PROPERTY: board-name Universe
> #+PROPERTY: board-id 5881ad219655d9c8ea6e365d
> #+PROPERTY: weeee 5881b1c1698c96973bcba480
> #+TODO: weeee
> #+PROPERTY: orgtrello-user-**** 55a6d63b6f055cc5071c3584
> #+PROPERTY: :blue
> #+PROPERTY: :purple
> #+PROPERTY: :red
> #+PROPERTY: :yellow
> #+PROPERTY: :orange
> #+PROPERTY: :green
> #+PROPERTY: orgtrello-user-me ****
> :END:

Since I haven't been able to sync the org buffer with the trello board there are no items.

**Comment by ardumont** [comment]
Hello,

Thanks for the thorough report.

Everything seems correctly set.

What does <kbd>M-x org-trello-check-setup</kbd> gives you?

With the log level trace your mentioned, here is my *Messages* buffer gives me this after this command:
```
org-trello - Checking setup....
Loading /home/tony/.emacs.d/.trello/ardumont.el (source)...done
org-trello - Checking trello connection...
org-trello - Checking setup. DONE.
org-trello - Response: [cl-struct-request-response 200 nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:id "4f2baa2f72b7c1293501cad3" :full-name "Antoine R. Dumont" :status "disconnected" :url "https://trello.com/ardumont" :username "ardumont")) nil success "https://api.trello.com/1/members/me?key=redacted&token=redacted" nil (:sync t :type "GET" :params ((key . "redacted") (token . "redacted")) :parser orgtrello-query--http-parse :success orgtrello-query--standard-success-callback :error orgtrello-query--standard-error-callback :url "https://api.trello.com/1/members/me?key=redacted&token=redacted" :response #0) #<killed buffer> "HTTP/2 200 
cache-control: max-age=0, must-revalidate, no-cache, no-store
x-content-type-options: nosniff
strict-transport-security: max-age=15768000
x-xss-protection: 1; mode=block
x-frame-options: DENY
x-trello-version: 1.871.0
x-trello-environment: Production
access-control-allow-origin: *
access-control-allow-methods: GET, PUT, POST, DELETE
access-control-allow-headers: Authorization, Accept, Content-Type
x-server-time: 1484989751414
expires: Thu, 01 Jan 1970 00:00:00
x-trello-index-last-update: null
content-type: application/json; charset=utf-8
etag: W/\"0V1kbDI5A+vV883nU3QTjQ==\"
vary: Accept-Encoding
content-encoding: gzip
content-length: 3042
date: Sat, 21 Jan 2017 09:09:11 GMT
" nil curl nil]
org-trello - Data: #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (:id "redacted" :full-name "Antoine R. Dumont" :status "disconnected" :url "https://trello.com/ardumont" :username "ardumont"))
org-trello - Account ’ardumont’ configured! Everything is ok!
```

This check is about loading the key and making a simple request to an api about the user to check everything works fine.
If is the credentials information are correctly installed, the result will be like my sample.
Otherwise, a problem should appear with the log and the request failure.

The important information are the key and token which are loaded from your `~/.emacs.d/.trello/holocronweaver.el` (they are redacted in my sample output).

Cheers,

**Comment by holocronweaver** [comment]
Oops, I forgot to include the output for `M-x org-trello-check-setup`:
> org-trello - Checking setup....
> org-trello - List of errors:
>  - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token

**Comment by holocronweaver** [comment]
I am still not sure what the error is, but I found a way around it:
1. Kill org buffer contents.
2. Yank contents back in.
3. `M-x org-trello-sync-buffer`
4. Successful sync!
However, after that initial sync the original problem occurs again. I can then repeat the workaround, killing and yanking the buffer contents, but it gets tedious fast!

**Comment by holocronweaver** [comment]
Er, I take back that fix. While it reports successful sync, and some items are downloaded, not everything is downloaded from trello and the things that are aren't organized according to list, card, etc. as expected - instead random cards are downloaded with no hierarchy (i.e., every card is just a bullet point, lists aren't explicitly represented at all).

**Comment by ardumont** [comment]
Well, that workaround is not acceptable anyway :D.

One step at a time, well as far as i could gather from your report, the initial problem was a connection issue. In that light, what does M-x org-trello-check-setup gives you in the *Messages* buffer? Can you report it back here?

Thanks in advance.

Cheers,

**Comment by holocronweaver** [comment]
The output of `M-x org-trello-check-setup` is the same that I gave in my second comment, unless I do my 'workaround'. It doesn't give the detailed output you posted, just that one message.

**Comment by ardumont** [comment]
> The output of M-x org-trello-check-setup is the same that I gave in my second comment, 

Yes, but that's not enough.

> It doesn't give the detailed output you posted, just that one message.

I'm sorry I was not clear.
I'd like the same message with the verbose output.
You mentioned that you already set the log level to trace in the original report so i thought this was ok.

>> Setting the org-trello trace to 5 did not produce any additional output.

Here is how to properly set it up:
```lisp
(custom-set-variables '(orgtrello-log-level orgtrello-log-trace))
```
source: https://github.com/org-trello/org-trello/blob/master/org-trello-log.el#L22

Can you please provide the <kbd>M-x org-trello-check-setup</kbd> with the detailed output?
(please, also replace the token and key with "redacted" string or something else before reporting it here)

Thanks in advance,

Cheers,

**Comment by holocronweaver** [comment]
Sorry for the delayed response.
I added that line to my init.el as you asked and here is what was produced in the `*Messages*` buffer:
```
org-trello - Request ’sync org buffer to trello board’...
org-trello - List of errors:
 - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token
- Setup problem - You need to install the consumer-key and the read/write access-token - C-c o i or M-x org-trello-install-key-and-token
```
Unfortunately none of the detailed log info you reported was in the buffer.

**Comment by holocronweaver** [comment]
I am not sure if it is relevant, but the MELPA version of org-trello is from 20160604.

**Comment by ardumont** [comment]
> I added that line to my init.el as you asked and here is what was produced in the *Messages* buffer after running M-x org-trello-check-setup:
...
> Unfortunately none of the detailed log info you reported was in the buffer.

Mmm, my bad, i actually forgot to tell you to evaluate that snippet of code.
Otherwise, this won't do much (unless you restart emacs).

<kbd>M-: (custom-set-variables '(orgtrello-log-level orgtrello-log-trace)) RET</kbd>

ps: `RET` is typing enter.

> I am not sure if it is relevant, but the MELPA version of org-trello is from 20160604.

Indeed, that's been a while since i released org-trello but i don't think this is the issue.

Cheers,

**Comment by holocronweaver** [comment]
> Mmm, my bad, i actually forgot to tell you to evaluate that snippet of code.
> Otherwise, this won't do much (unless you restart emacs).

Thanks for the quick response!

I actually did restart Emacs after adding the line my `init.el`. I also tried manually evaluating the expression. Either way, `M-x org-trello-check-setup` produced the same brief output in `*Messages*`.

However, I manually eval'd `(orgtrello-controller-check-trello-connection)` and it produced a full log, so there may be a bug in `org-trello-apply` or the setup of `org-trello-log-strict-checks-and-do`:

```
org-trello - Checking trello connection...
[cl-struct-deferred deferred:default-callback #[128 "ÂÀÃÁ\"\"" [orgtrello-log-msg (1 "Checking trello connection... FAILED. Error: %S") apply append] 6 "

(fn &rest ARGS2)"] deferred:default-cancel nil nil nil]
org-trello - client - Problem during request - error-thrown: (error http 401)
org-trello - Detailed response: [cl-struct-request-response 401 nil nil (error http 401) error "https://api.trello.com/1/members/me?key=nil&token=nil" nil (:sync t :type "GET" :params ((key) (token)) :parser orgtrello-query--http-parse :success orgtrello-query--standard-success-callback :error orgtrello-query--standard-error-callback :url "https://api.trello.com/1/members/me?key=nil&token=nil" :response #0) #<killed buffer> "HTTP/1.1 401 Unauthorized
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15768000
X-XSS-Protection: 1; mode=block
X-FRAME-OPTIONS: DENY
X-Trello-Version: 1.876.1
X-Trello-Environment: Production
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Headers: Authorization, Accept, Content-Type
Expires: Thu, 01 Jan 1970 00:00:00
Content-Type: text/plain; charset=utf-8
Content-Length: 11
ETag: W/\"b-ca7443e3\"
Vary: Accept-Encoding
Date: Fri, 27 Jan 2017 20:07:57 GMT
Connection: keep-alive
Set-Cookie: dsc=*****; Path=/; Expires=Mon, 30 Jan 2017 20:07:57 GMT; Secure
" nil curl nil]
org-trello - There is a problem with your credentials.
Make sure you used M-x org-trello-install-key-and-token and this installed correctly the consumer-key and access-token.
See http://org-trello.github.io/trello-setup.html#credentials for more information.
```
Judging by the nils in the url, it seems like org-trello is having trouble parsing the creds file.

**Comment by holocronweaver** [comment]
Btw, I checked the `org-trello` compilation log and found an error:
```
In orgtrello-controller-mode-off-hook-fn:
org-trello-controller.el:1425:4:Error: missing value for ‘org-trello--mode-activated-p’ at end of setq
```

**Comment by ardumont** [comment]
> However, I manually eval'd (orgtrello-controller-check-trello-connection) and it produced a full ...

Mmm, no this function needs unfortunately some state to be set before being called.
That's why it's wrapped as you can see in the main command in org-trello-check-setup.

Since you opened that box :D, a more appropriate unwrapping to eval using M-: from inside the org-trello buffer would be:

```lisp
(orgtrello-action-msg-controls-or-actions-then-do
   "Check setup is ok"
   '(orgtrello-controller-migrate-user-setup
     orgtrello-controller-set-account
     orgtrello-controller-load-keys
     orgtrello-controller-control-keys
     orgtrello-controller-setup-properties
     orgtrello-controller-control-properties)
   'orgtrello-controller-check-trello-connection))
```

This gives me:

```
org-trello - Checking trello connection...
[cl-struct-deferred deferred:default-callback #[128 "noisynoise" [orgtrello-log-msg (1 "Checking trello connection... FAILED. Error: %S") apply append] 6 "

(fn &rest ARGS2)"] deferred:default-cancel nil nil nil]
org-trello - Account ’ardumont’ configured! Everything is ok!
```

> Btw, I checked the org-trello compilation log ...

Mmm, damn, [that would be fixed in the 0.8.0 branch you don't have...](https://github.com/ardumont/org-trello/commit/bfc26ec156c49e01a380db94b30c181a15ff0eee)...

**Comment by holocronweaver** [comment]
> Since you opened that box :D, a more appropriate unwrapping to eval using...

I did so and it produced the same short output that calling `M-x org-trello-check-setup` does:

```
org-trello - Check setup is ok...
org-trello - List of errors:
 - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token
- Setup problem - You need to install the consumer-key and the read/write access-token - C-c o i or M-x org-trello-install-key-and-token
```

I used `toggle-debug-on-error` as well and no errors were caught.

> Mmm, damn, that would be fixed in the 0.8.0 branch you don't have......

Well, at least that was an easy enough manual fix. :smile:

**Comment by ardumont** [comment]
> I did so and it produced the same short output as M-x org-trello-check-setup...

Ok, strange but moving on :D

You said you checked it out, what does your trello credential file looks like?

It's supposed to be something like:
```lisp
(setq org-trello-consumer-key "redacted")
(setq org-trello-access-token "redacted")
```

Come to think of it, your credential file is named `holocronweaver`.
And https://trello.com/holocronweaver is not found (compared to mine https://trello.com/ardumont which and i'm logged out).

Does it match the trello user **** in your initial sample (see below)?
```text
#+PROPERTY: orgtrello-user-me ****
```

If not, please, try and rename it according to your trello login and check again.
Thanks in advance

Cheers,

**Comment by holocronweaver** [comment]
Ahhhh, yes, the issue was that Trello had generated a username for me and I wasn't aware. (It is a username I never would have chosen myself.) I changed the name to holocronweaver and can now sync the buffer.

After a bit of fidgeting about, I am now successfully using `org-trello` to edit my boards. Yay! Thanks so much for your help! :100:

**Comment by ardumont** [comment]
Awesome news.

Cheers,
