### ISSUE TITLE
Store dev branches in main repo

### ISSUE THREAD

**Issue by holocronweaver** [org-trello/org-trello#346]
I noticed @ardumont stores dev branches in his personal fork. For the sake of easing contributions, would you mind pushing the dev branch upstream? 

My initial impression was that there was no work towards a next version because I couldn't find a dev branch on the main repo. I am sure I am not the only one getting the wrong impression.

**Comment by ardumont** [comment]
Hello,

sounds reasonable!

Cheers,

**Comment by ardumont** [comment]
Beware though, I do use that branch as a draft.
So, even though it's not recommended, it happens that i rewrite the development branches.
That's why i initially avoided to push on the main repository.

**Comment by holocronweaver** [comment]
Thanks! And don't worry forced pushes, I expect that sort of thing for lone gunner projects.
