### ISSUE TITLE
Please add a prefix to test-helper.el to avoid conflicts with 68 other packages

### ISSUE THREAD

**Issue by tarsius** [org-trello/org-trello#348]
There exist at least 69 packages that contain a file named `test-helper.el` that also provides the feature `test-helper`.

This leads to issues for users who have at least two of these packages installed.  It is unlikely that such a user would be able to run the tests of all of those packages.  If the primary test file of one of those packages does `(require 'test-helper)`, then it is undefined which of the various `test-helper.el` files gets loaded.  Which it is, depends on the order of the `load-path`.

To avoid this conflicts, you should rename your `test-helper.el` to `<your-package>-test-helper.el` and adjust the feature accordingly.

Also don't forget to update the `require` form in your primary test file and/or update references to the library/feature elsewhere.  Also, if your primary test file is named something like `test.el`, then please consider renaming that too (same for any other utility elisp files your repositoroy may contain).

Thanks!

PS: This issue is a bit generic because I had to open 69 issues.

**Comment by ardumont** [comment]
Hello,

Well, i agree with your analysis... But for one point, this file is not packaged for runtime.
So this should not be an issue.

You can check either:
- the [Cask file which i use to package for marmalade](https://github.com/org-trello/org-trello/blob/master/Cask) (checked and ok)
- the [equivalent melpa recipe](https://github.com/melpa/melpa/blob/master/recipes/org-trello) (checked and ok)
- You can also check your elpa directory for the installed package and this file is not present (checked, you can only check this yourself with your install :)

But if that's a real bother, I do accept PR :)

(This remark goes for ardumont/markdown-toc, ardumont/org2jekyll,
etc...)

Cheers,

**Comment by tarsius** [comment]
I've been informed, that `ert-runner` automatically loads the `test-helper.el` file. So you should **not** rename that file. Instead please see [this issue](https://github.com/rejeep/ert-runner.el/issues/38), where I suggest that the `(provide 'test-helper)` should be dropped instead. Please accept my apologize for opening these issues prematurely.

**Comment by tarsius** [comment]
> So this should not be an issue.

It is a bit of a cosmetic issue, that much I admit ;-)

However the reasons you provide for why it is not an issue boil down to it not being an issue for Melpa users. My counter argument is that not everyone uses Melpa to install packages. (I for example use git submodules and have even written an alternative package manager, [borg](https://emacsmirror.net/manual/borg/).

> But if that's a real bother, I do accept PR :)

Okay then, if that's what it takes ;-) I am simply removing the `(provide 'test-helper)` for the reasons given in rejeep/ert-runner.el#38.

**Comment by tarsius** [comment]
> But if that's a real bother, I do accept PR :)

I have created four prs.

> (This remark goes for ardumont/markdown-toc, ardumont/org2jekyll, etc...)

..and hope I found all `etc...`.

**Comment by ardumont** [comment]
> It is a bit of a cosmetic issue, that much I admit ;-)

:D

> However the reasons you provide for why it is not an issue boil down to it not being an issue for Melpa users.  My counter argument is that not everyone uses Melpa to install packages. (I for example use git submodules and have even written an alternative package manager, borg.) "People not using Melpa" also includes those users who only temporarily use your package from the git repository because they want to contribute something to it. Those are the users who you really want to be able to run the tests.

Indeed, i also did the package work for marmalade properly (that is without integrating the 'tests namespace'). I also did el-get but did not check if this is wrong there (i don't think so).

But your counter argument keep working as i cannot assume myself to be exhaustive.
So, wrapping my head around, sure, you are right.

I did not know about borg, interesting. Thanks.

> Okay then, if that's what it takes ;-) I am simply removing the (provide 'test-helper) for the reasons given in rejeep/ert-runner.el#38.

Ah yes, i saw the ert-runner thread this week end.
And since the complexity dropped down as simply removing the provide statement, i thought 'oh well, why not!'. To sum up, i did change my mind but did not find the time to do it.

Of course, i forget to remove the flag here ¯\_(ツ)_/¯

> I have created four prs..

Well, thanks!

> ..and hope those cover all etc....

Well sorry for that. I was kind of annoyed by the "spam" at first.
Of course, this was not reasonable on my part :D

If there are misses, i'll do them (at some point).
Thanks again for trying to raise our collective awareness :D

Cheers,

**Comment by tarsius** [comment]
No no, it's okay to be a bit annoyed by the spam. That's understandable and happens occasionally when I open such issues. It's just something I have to live with to get this done. I did concentrate on the "real issues" first, like packages with unsatisfied dependencies, and now I have moved on to the more "hypothetical" ones. You can track my progress [here](https://emacsmirror.net/stats/kludges.html).

**Comment by ardumont** [comment]
> No no, it's okay to be a bit annoyed by the spam. That's understandable and happens occasionally when I open such issues. It's just something I have to live with to get this done. 

Right.

> I did concentrate on the "real issues" first, like packages with unsatisfied dependencies, and now I have moved on to the more "hypothetical" ones. You can track my progress here.

Awesome.

Also, I'll merge the PRs but not right now. 

Cheers,

**Comment by tarsius** [comment]
Thanks!
