### ISSUE TITLE
melpa release of 0.8?

### ISSUE THREAD

**Issue by imalsogreg** [org-trello/org-trello#351]
Hello! Would you consider making a release of the 0.8 branch to melpa? Is it ready? I'm on a version of emacs where I run into https://github.com/org-trello/org-trello/issues/335, and my low spacemacs understanding is making the workaround difficult to carry out.

**Comment by ardumont** [comment]
Yes, i'll try to find some time this week end.

(I need to unbreak the dev tools first though and that's what's blocking me.)

Cheers,

**Comment by ardumont** [comment]
blocked by #353

**Comment by ardumont** [comment]
Hello,

This is done.
Deployed to marmalade.
For melpa, you just need to wait for the next build ;p

Cheers,

**Comment by imalsogreg** [comment]
Such quick work - thank you very much!!!
