### ISSUE TITLE
org-trello won't sync

### ISSUE THREAD

**Issue by adnan-wahab** [org-trello/org-trello#355]
Hello,

Can you please provide the following information?

Thanks in advance.

## bug?

I navigate to org-file with 

:PROPERTIES:
#+PROPERTY: board-name research
#+PROPERTY: board-id 58ba2e5fc11af7eb437607f8
#+PROPERTY: DONE 58ba2e629d6ec1df150cd562
#+PROPERTY: TODO 58ba2e61afad803544019c53
#+TODO: TODO | DONE
#+PROPERTY: orgtrello-user-adnanwahab1 510f2ef7356d1bc9020018d3
#+PROPERTY: :blue
#+PROPERTY: :purple
#+PROPERTY: :yellow
#+PROPERTY: :red
#+PROPERTY: :orange
#+PROPERTY: :green
#+PROPERTY: orgtrello-user-me adnanwahab1
:END:

and org-trello-sync-buffer
and get the following error

### M-x org-trello-bug-report

```org-trello - Hello master, help is ‘M-x org-trello-help-describing-bindings RET’ or ‘C-c o h’.
org-trello - Request ’sync entity with structure to trello...
org-trello - List of errors:
 - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token
- Setup problem - You need to install the consumer-key and the read/write access-token - C-c o i or M-x org-trello-install-key-and-token

Quit
org-trello - Please:
- Describe your problem with clarity and conciceness (cf. https://www.gnu.org/software/emacs/manual/html_node/emacs/Understanding-Bug-Reporting.html)
- Explicit your installation choice (melpa, marmalade, el-get, tarball, git clone...).
- Activate ‘’trace‘’ in logs for more thorough output in *Message* buffer: (custom-set-variables ’(orgtrello-log-level orgtrello-log-trace)).
- A scrambled sample (of the user’s and board’s ids) of your org-trello buffer with problems.
- Report the following message trace inside your issue.

System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)
 of 2016-11-05
- org version: 9.0.2
- org-trello version: 0.8.0
- org-trello path: /Users/adnanwahab/.emacs.d/elpa/org-trello-20170225.1247/org-trello.el
- request-backend: curl
- kill-whole-line: nil

```
### Expected behavior

org-trello-sync-buffer

### Actual behavior

org-trello said i did not configure, but i created board using org-trello
and i installed my trello account using C-c o I

my account details are confirmed in .emacs.d/.trello/mail@adnanwahab.com.el

### Steps to reproduce the behavior

How can we try and reproduce?

if i run emacs-lisp-byte-compile from 
org-trello-controller.el
i get

Don't hesitate to show some scrambled sample of your org-mode file.
(or *Compile-Log* buffer when it's some packaging problem)...

Compiling file /Users/adnanwahab/.emacs.d/elpa/org-trello-20170225.1247/org-trello-controller.el at Fri Mar  3 21:25:16 2017

In orgtrello-controller-migrate-user-setup:
org-trello-controller.el:121:17:Warning: reference to free variable
    ‘*consumer-key*’
org-trello-controller.el:122:36:Warning: reference to free variable
    ‘*access-token*’

### More information on

http://org-trello.github.io/contributions.html#issues

**Comment by ardumont** [comment]
Note to self:
- is it possily related to login as email?
- possibly related to #347

**Comment by adnan-wahab** [comment]
ah yes that was in fact the issue. i used "adnanwahab1" as my login and it syncs now. 

i get an error now though that
orgtrello-buffer-compute-checksum: Symbol’s function definition is void: nil

**Comment by adnan-wahab** [comment]
I tried adding the following code to my config and it didnt change anything

(custom-set-variables
   '(orgtrello-log-level orgtrello-log-debug) ;; log level to debug
   '(org-trello-current-prefix-keybinding "C-c x") ;; C-c x as the default prefix
   '(orgtrello-setup-use-position-in-checksum-computation nil) ;; checksum without position
   '(org-trello-files '("~/docs/some-doc.trello"
                        "~/docs/some-other-doc.org"))) ;; automatic org-trello on files

**Comment by adnan-wahab** [comment]
my first thought is that it seems like 

org-trello and orgtrello are 2 separate namespaces and theres a conflict in the lookup?

**Comment by ardumont** [comment]
Hello,

sorry for the late reply, was taking some time off to rest.

> if i run emacs-lisp-byte-compile from
> org-trello-controller.el
> i get

Why do you need to do that?

> Don't hesitate to show some scrambled sample of your org-mode file.
> (or Compile-Log buffer when it's some packaging problem)...
> 
> Compiling file /Users/adnanwahab/.emacs.d/elpa/org-trello-20170225.1247/org-trello-controller.el at > Fri Mar 3 21:25:16 2017

> In orgtrello-controller-migrate-user-setup:
> org-trello-controller.el:121:17:Warning: reference to free variable
> ‘consumer-key’
> org-trello-controller.el:122:36:Warning: reference to free variable
> ‘access-token’

Yes, this happens because now those symbols are no longer used.
It's a relic from the past which i don't remove for retro-compatibility.
Maybe i still need to define those though.

> orgtrello-buffer-compute-checksum: Symbol’s function definition is void: nil

Mmm, that's problematic indeed.
Can you try and reinstall org-trello?
You should not have to byte compile anything since it's already done by emacs at installation time.

> org-trello and orgtrello are 2 separate namespaces and theres a conflict in the lookup?

Yes, they are separate namespaces but there are more than 2.
I kept the **org-trello-** function prefix name for the main namespace (the main interactive commands used with M-x) defined in org-trello.el.
Every other namespace starts with **orgtrello-**.
I don't think this is the problem though.

Cheers,

**Comment by DiogoFerrari** [comment]
I can push items, but it does not sync from Trello. Any idea.
