### ISSUE TITLE
 Sync the board metadata but no cards fetched from trello

### ISSUE THREAD

**Issue by BobCromwell** [org-trello/org-trello#357]
### M-x org-trello-bug-report
```
System information:
- system-type: darwin
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1212))
 of 2017-02-15
- org version: 9.0.5
- org-trello version: 0.8.0
- org-trello path: /Users/bob/.emacs.d/elpa/org-trello-20170225.1247/org-trello.el
- request-backend: curl
- kill-whole-line: nil
```

### Expected behavior

after  M-x org-trello-install-board-metadata, I expected to get all my cards and check items.

### Actual behavior

However the buffer only contains the list name 

```
:PROPERTIES:
#+PROPERTY: board-name 2017
#+PROPERTY: board-id 5885b8c0ec6b1afad6a622f4
#+PROPERTY: list-name 58b4d8fe4d988a1aa0506e54
...
#+PROPERTY: orgtrello-user-user54963355 57d0c1afebb497daf2632c7f
#+PROPERTY: :yellow label-name
...
#+PROPERTY: orgtrello-user-me user54963355
:END:
```
Nothing after that and no sub items found.

**Comment by ardumont** [comment]
Hello,

From within your trello buffer, what does <kbd>M-x org-trello-check-setup</kbd> gives you? (you may have to check the *Messages* buffer).

Expected right output:
```
org-trello - Checking trello connection...
org-trello - Checking setup. DONE.
org-trello - Account user54963355 configured! Everything is ok!
```

Cheers,

**Comment by BobCromwell** [comment]
```
org-trello - Checking setup....
org-trello - List of errors:
 - Setup problem - Problem during credentials loading (consumer-key and read/write access-token) - C-c o i or M-x org-trello-install-key-and-token
- Setup problem - You need to install the consumer-key and the read/write access-token - C-c o i or M-x org-trello-install-key-and-token
- Setup problem.
Either you did not connect your org-mode buffer with a trello board, to correct this:
  * attach to a board through C-c o I or M-x org-trello-install-board-metadata
  * or create a board from scratch with C-c o b or M-x org-trello-create-board-and-install-metadata).
Either your org-mode's todo keyword list and your trello board lists are not named the same way (which they must).
For this, connect to trello and rename your board's list according to your org-mode's todo list.
Also, you can specify on your org-mode buffer the todo list you want to work with, for example: #+TODO: TODO DOING | DONE FAIL (hit C-c C-c to refresh the setup)

org-trello - Checking setup. DONE.
```
but I do have trello key in my .emacsd/.trello folder.

May be the issue is I am using an email account?

```
~/.emacs.d/.trello/tianbaom@gmail.com.el
```

**Comment by ardumont** [comment]
> May be the issue is I am using an email account?

I'm inclined to think so. Please, take a look at #347 for explanation details (this issue feels strongly like a duplicate).

According to the provided metadata in your initial sample, i think this file should be named '~/.emacs.d/.trello/user54963355.el':

1. Indeed, https://trello.com/user54963355 exists
2. user54963355 is the `orgtrello-user-me` referenced in your header file
3. this should map the credential file

[Maybe something went wrong when initializing the credentials](https://github.com/org-trello/org-trello/issues/347#issuecomment-289400985).

Cheers,

**Comment by BobCromwell** [comment]
I re-install key using user54963355 however still same error. Are there  any other cache besides username.el file ?

**Comment by ardumont** [comment]
> I re-install key using user54963355 however still same error. 

That's unfortunate.

> Are there any other cache besides username.el file ?

No.

Have you checked the content of the file  '~/.emacs.d/.trello/user54963355.el'?

-- 

Maybe, try to revert the buffer (<kbd>M-x revert-buffer</kbd>) and try again.

Cheers,

**Comment by BobCromwell** [comment]
I will not investigate these days as I begin to busy with other projects. Maybe I can investigate this issue later and send a PR.  @ardumont Should I close this issue?

**Comment by ardumont** [comment]
Hello,

> I will not investigate these days as I begin to busy with other projects.

That happens :D

> Maybe I can investigate this issue later and send a PR.

Sure, if you find anything wrong, I'm all ears :D

> @ardumont Should I close this issue?

Yes, you could always reopen later on.

Cheers,

**Comment by DiogoFerrari** [comment]
Same problem here.
