### ISSUE TITLE
org-trello doesn't sync cards that already exist on Trello

### ISSUE THREAD

**Issue by anmoljagetia** [org-trello/org-trello#358]
Hello,
Thanks for creating this wonderful tool. I am really enjoying it.

## bug

I have been checking out the videos [here](http://org-trello.github.io/demo.html) and have been trying to establish the *sync all cards* feature. I can sync the cards I create in org to trello, but the reverse sync is not working for me, so unfortunately, all the cards that are on trello, I can't use from within emacs.

### M-x org-trello-bug-report

![image](https://cloud.githubusercontent.com/assets/6505326/24547322/d09a8ea8-162c-11e7-817c-34de67472b29.png)

### Expected behavior.

I expect to pull all existing cards from trello into the buffer.

### Actual behavior.

Sync only works for cards I create in the buffer. If I create a card on the web interface, it doesn't show up in my buffer.

### Steps to reproduce the behavior.

1.Install spacemacs.
2. Install org-trello.
3. Setup org-trello like the steps in the documentation.
4. Try and sync an already existing board from trello.

Thanks for creating this tool!

Cheers,
Anmol J

**Comment by ardumont** [comment]
> Thanks for creating this wonderful tool. I am really enjoying it.
> ...
> Thanks for creating this tool!

Thanks.

> but the reverse sync is not working for me, so unfortunately, all the cards that are on trello,

That's a bummer.

> Sync only works for cards I create in the buffer. If I create a card on the web interface, it doesn't show up in my buffer.

Can you please provide a sample of your `*Messages*` buffer after having tried to sync from trello?

Cheers,

**Comment by anmoljagetia** [comment]
```
org-trello - Synchronizing org-mode file to board ’SEM-DevOps’. This may take some time, some coffee may be a good idea...
org-trello - Entity ’Add PHP Configuration to EFS’ with id ’58dce3f51d8adfadfadafd’ synced!
Auto-saving...done
Saving file /Users/anmol.j/.emacs.d/.cache/recentf...
Wrote /Users/anmol.j/.emacs.d/.cache/recentf
Saving file /Users/anmol.j/.emacs.d/.cache/recentf...
Wrote /Users/anmol.j/.emacs.d/.cache/recentf
<M-s-drag-n-drop> is undefined
mwheel-scroll: Beginning of buffer [3 times]
Saving file /Users/anmol.j/.emacs.d/.cache/recentf...
Wrote /Users/anmol.j/.emacs.d/.cache/recentf
org-trello - Request ’sync org buffer to trello board’...
Loading /Users/anmol.j/.emacs.d/.trello/anmoljagetia1.el (source)...done
org-trello - Synchronizing org-mode file to board ’SEM-DevOps’. This may take some time, some coffee may be a good idea...
org-trello - Entity ’Add PHP Configuration to EFS’ with id ’58dce3f51d839fadsfadfb3d’ synced!
mwheel-scroll: End of buffer [3 times]

```

Also, looking at the demo videos, I think I am missing the reverse sync functions. For sync, I only have the following functions : 
![image](https://cloud.githubusercontent.com/assets/6505326/24567935/677908cc-167d-11e7-94a9-5e7021bbdb9c.png)

**Comment by anmoljagetia** [comment]
@ardumont Do you have any updates on this? Am I missing some functions?(which I suspect is the case).

**Comment by ardumont** [comment]
>  looking at the demo videos

Well, those videos were made a long time ago and the command have changed since then.
I mean, you no longer have functions for explicity sync from trello IIRC.

> Do you have any updates on this? 

Maybe.

> Am I missing some functions?

Not necessarily.
To sync a card/board from trello, you'd need to use the C-u prefix.
So sync a card to trello, it's <kbd>M-x org-trello-sync-card</kbd>.
But sync a card from trello would be <kbd>C-u M-x org-trello-sync-card</kbd>.
The same goes for other functions [as detailed in the doc](http://org-trello.github.io/bindings.html).

Is that what you did to try and sync from trello?

--

Otherwise, if you really think functions are missing, that *might* that the spacemacs' org-trello layer is incomplete. I tried spacemacs some time ago. I like their layers idea.
Still, i'm not fluent in it and i don't know how that layer is defined so i must be wrong.

Cheers,

**Comment by anmoljagetia** [comment]
> Is that what you did to try and sync from trello?

Yeah, I am trying to pull the 100 odd cards I have there on Trello.


> Otherwise, if you really think functions are missing, that might that the spacemacs' org-trello layer is incomplete. I tried spacemacs some time ago. I like their layers idea.

It was indeed the spacemacs binding interfering with the org-mode binding. I recently 'converted' to emacs from vim, and I use C-u to scroll up, didn't realise it was the universal command in Emacs, until this. Everything works as I expected now.

Thanks a lot for creating this 👍  I would love to buy you a beer. 

Cheers.

**Comment by ardumont** [comment]
> It was indeed the spacemacs binding interfering with the org-mode binding. I recently 'converted' to emacs from vim, and I use C-u to scroll up, didn't realise it was the universal command in Emacs, until this. Everything works as I expected now.

Awesome!

> Thanks a lot for creating this :+1:

Thanks again for you raising this up and patiently waiting for some cue.
With some luck, that might help others as well.

> I would love to buy you a beer.

In the mean time :beers:

Cheers,

**Comment by olymk2** [comment]
Might be usefull to others sync does not go in both directions by default which caught me out 
to sync to trello

    (org-trello-sync-buffer)

to sync exisiting cards you want 

    (org-trello-sync-buffer t)

hopefully that will help someone :)
