### ISSUE TITLE
Email id as username doesn't work

### ISSUE THREAD

**Issue by palaniraja** [org-trello/org-trello#359]
Logging it in here - https://github.com/org-trello/org-trello.github.io/issues/49

## bug?
If you use email id as your trello username instead of just username, It doesn't work as expected.

After a lot of struggle i figured that if you use trello userid (could be a email) then sync doesn't work throws the consumer-key/access-token issue, thought the .trello/~userid.el is populated with valid key and token.

Note: I'm using my email id as trello user id. I also use this to login to trello.com

partial text from minibuffer 

```
the consumer-key/access-token issue
```

### Expected behavior

Should work as Trello can be accessed using full email id instead of just userid.

### Actual behavior

`org-trello-install-key-and-token` completed without any issues, i can even see the <userid.email.el> file with correct data. But when i try to do a `org-trello-install-board-metadata` after setup, it throws the error with consumer-key/access

**Comment by ardumont** [comment]
Can you please remove the section deemed useless (the ones without an answer)?

--

> After a lot of struggle i figured that if you use trello userid (could be a email) then sync doesn't work throws the consumer-key/access-token issue, thought the .trello/~userid.el is populated with valid key and token.

whether you use the user-id or the email, your orgtrello-user-me entry and the credential file should match. [347#issuecomment-289229721](A recent check i did).

Is it the case? I just cannot tell from your summary.

Cheers,

**Comment by palaniraja** [comment]
updated. Thanks.

**Comment by ardumont** [comment]
>> Can you please remove the section deemed useless (the ones without an answer)?

> updated. Thanks.

Thank you

**Comment by wakatara** [comment]
I had this same issue in my setup and the original email I signed up with. I changed it to my account "name" rather than login and the credentials worked fine.

**Comment by ardumont** [comment]
> Same behavior and resolution encountered. I suggest that you amend the
> installation/setup instructions to clarify that the trello username (no "@")
> must be used, not the user's email address that trello also accepts at the
> login prompt. ‘org-trello-20180331.631/’

Agreed.

Though it can be argued it has been mentioned in the documentation for some
time... [1]

Let's agree it needs to be improved ;)

[1] https://org-trello.github.io/trello-setup.html

**Comment by ardumont** [comment]
And more recently by you in the synchronized documentation in that repository ;)

**Comment by daniel-birket** [comment]
Just a note to confirm that I don't seem to need to update the org-to-texi manual relative to this old issue. I see this mentioned there in CAPS. -- Daniel Birket

**Comment by ardumont** [comment]
> Just a note to confirm that I don't seem to need to update the org-to-texi
> manual relative to this old issue. I see this mentioned there in CAPS. --
> Daniel Birket

Quite so ;) I checked and found it quite sufficient that way indeed. Thanks for
double checking.

Cheers,
