### ISSUE TITLE
Delete label from card error 404

### ISSUE THREAD

**Issue by Sandsten** [org-trello/org-trello#361]
## bug?
When I use the following command it gives the error 404
```js
Trello.delete("cards/"+card.id+"/idLabels?idLabel="+label.id);
```
I've even tried to delete it directly after posting the label like this
```js
Trello.post("cards/"+card.id+"/labels?color="+color+"&name="+card.label , function(label){
   Trello.delete("cards/"+card.id+"/idLabels?idLabel="+label.id);
```
still the same error. 
This seems like a bug to me, can't understand why i'm receiving this error.

**Comment by ardumont** [comment]
Hello,

> Trello.delete("cards/"+card.id+"/idLabels?idLabel="+label.id);

This does not look like emacs-lisp ^^, more like a kind of javascript library client for trello.
Are you sure this is org-trello related?

**Comment by Sandsten** [comment]
Your right about that, i'm using client.js from Trellos website. Thought this repository was that, sorry about this.

**Comment by ardumont** [comment]
> Your right about that, i'm using client.js from Trellos website. Thought this repository was that, sorry about this.

Sure. No problem.

Cheers,
