### ISSUE TITLE
Syncing from trello: error http 408

### ISSUE THREAD

**Issue by skrat** [org-trello/org-trello#362]
## bug?

Syncing trello board to buffer

```
org-trello - Request ’sync org buffer from trello board’...
Loading /home/skrat/.emacs.d/.trello/dusanmaliarik.el (source)...done
org-trello - Sync trello board ’Current Development’ to buffer ’trello.org’...
org-trello - client - Problem during request - error-thrown: (error http 408)
(No changes need to be saved)
org-trello - Sync trello board ’Current Development’ to buffer ’trello.org’... DONE. [2 times]
```

### M-x org-trello-bug-report

System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 26.0.50 (build 1, x86_64-unknown-linux-gnu, GTK+ Version 3.22.8)
 of 2017-02-22
- org version: 9.0.7
- org-trello version: 0.8.0
- org-trello path: /home/skrat/.emacs.d/elpa/org-trello-20170225.1247/org-trello.el
- request-backend: curl
- kill-whole-line: nil

### Expected behavior

Synced org buffer

### Actual behavior

Does nothing

**Comment by skrat** [comment]
After changing `request-backend` to `url-retrieve`

```
org-trello - Sync trello board ’Current Development’ to buffer ’trello.org’...
Contacting host: api.trello.com:443 [2 times]
REQUEST [error] Error from parser orgtrello-query--http-parse: (json-readtable-error)
org-trello - client - Problem during request - error-thrown: (json-readtable-error)
(No changes need to be saved)
org-trello - Sync trello board ’Current Development’ to buffer ’trello.org’... DONE. [2 times]
```

**Comment by skrat** [comment]
@ardumont is there anything I can do to help debug this issue?

**Comment by ardumont** [comment]
Hello

> @ardumont is there anything I can do to help debug this issue?

Using the default request-backend (curl), can you please try some of the steps described at http://ardumont.github.io/debug and report your result here?

Thanks.

**Comment by skrat** [comment]
@ardumont I did `(trace-function 'orgtrello-query--get)`, it spat out bunch of output, including HTTP 200 response, and the board parsed into hash-table. I'm not posting the output here as it contains bunch of private data. Despite that, same error message appeared in `*Messages*` and the board wasn't synchronized to the buffer.

**Comment by ardumont** [comment]
> I'm not posting the output here as it contains bunch of private data. 

Well, you could anonymize those sensible data and report them here, couldn't you?
Everything that looks like id can be replaced with '*id*' for example.

> Despite that, same error message appeared in *Messages* and the board wasn't synchronized to the buffer.

It could really help if i could see those.
I can't help much otherwise :)

You know, "everybody lies", be it voluntary or involuntary (that one in that case :).

All i can say for now is about the http error code mentioned (which you probably know already).
408 is Request Timeout Error so there may be some requests which takes too long.
Now we need to determine which one it is...
And there your output seems quite important.

--

Also, you could try simple step first, for example, does that one succeed?

```
(let ((org-trello--user-logged-in "skrat"))
  (orgtrello-controller-load-keys)
  (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
```
Note: 
- i assume 'skrat' is your trello login, replace with the correct one if incorrect
- only the 'id' field is to be anonymized.

Cheers,

**Comment by skrat** [comment]
```
(let ((org-trello--user-logged-in "dusanmaliarik"))
 (orgtrello-controller-load-keys)
 (orgtrello-query-http-trello (orgtrello-api-get-me) 'sync))
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data
              (:id "xxx" :full-name "Dušan Maliarik" :status "disconnected" :url "https://trello.com/dusanmaliarik" :username "dusanmaliarik"))
```

and this one if from the syncing

```
======================================================================
1 -> (orgtrello-query--get "https://api.trello.com/1" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (:params (("filter" . "closed") ("fields" . "closed,desc,due,idBoard,idList,idMembers,labels,name,pos")) :method "GET" :uri "/boards/xxxx/cards" :sync sync)) nil nil with-authentication)
1 <- orgtrello-query--get: #2=[cl-struct-request-response 200 nil (#s(hash-table size 65 ACTUAL BOARD CONTENT PARSED TO HASH-TABLE))) nil success "https://api.trello.com/1/boards/xxx/cards?key=xxx&token=xxx&filter=closed&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos" t (:sync t :type "GET" :params ((key . "xxx") (token . "xxx") ("filter" . "closed") ("fields" . "closed,desc,due,idBoard,idList,idMembers,labels,name,pos")) :parser orgtrello-query--http-parse :success orgtrello-query--standard-success-callback :error orgtrello-query--standard-error-callback :url "https://api.trello.com/1/boards/xxx/cards?key=yyy&token=xxx&filter=closed&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos" :response #2#) #<killed buffer> "HTTP/1.1 200 OK
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15768000
X-XSS-Protection: 1; mode=block
X-FRAME-OPTIONS: DENY
X-Trello-Version: 1.985.0
X-Trello-Environment: Production
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Headers: Authorization, Accept, Content-Type
X-Server-Time: 1498208906624
Expires: Thu, 01 Jan 1970 00:00:00
Content-Type: application/json; charset=utf-8
ETag: W/\"IbNnMNvB5LlJ1alvVRyQbw==\"
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 39957
Date: Fri, 23 Jun 2017 09:08:26 GMT
Connection: keep-alive
" nil curl nil]
======================================================================
1 -> (orgtrello-query--get "https://api.trello.com/1" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data (:params (("actions" . "commentCard") ("checklists" . "all") ("filter" . "open") ("fields" . "closed,desc,due,idBoard,idList,idMembers,labels,name,pos")) :method "GET" :uri "/boards/xxx/cards" :sync sync)) nil nil with-authentication)
1 <- orgtrello-query--get: #1=[cl-struct-request-response 408 nil nil (error http 408) error "https://api.trello.com/1/boards/xxx/cards?key=yyy&token=xxx&actions=commentCard&checklists=all&filter=open&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos" t (:sync t :type "GET" :params ((key . "yyy") (token . "xxx") ("actions" . "commentCard") ("checklists" . "all") ("filter" . "open") ("fields" . "closed,desc,due,idBoard,idList,idMembers,labels,name,pos")) :parser orgtrello-query--http-parse :success orgtrello-query--standard-success-callback :error orgtrello-query--standard-error-callback :url "https://api.trello.com/1/boards/xxx/cards?key=xxx&token=yyy&actions=commentCard&checklists=all&filter=open&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos" :response #1#) #<killed buffer> "HTTP/1.1 408 Request Time-out
Cache-Control: max-age=0, must-revalidate, no-cache, no-store
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=15768000
X-XSS-Protection: 1; mode=block
X-FRAME-OPTIONS: DENY
X-Trello-Version: 1.985.0
X-Trello-Environment: Production
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Headers: Authorization, Accept, Content-Type
Expires: Thu, 01 Jan 1970 00:00:00
Content-Type: text/plain; charset=utf-8
Content-Length: 15
ETag: W/\"f-996d83fb\"
Vary: Accept-Encoding
Date: Fri, 23 Jun 2017 09:08:57 GMT
Connection: keep-alive
" nil curl nil]
```

**Comment by ardumont** [comment]
Nice! Thanks.

So the api for user information is ok.
But the api to access board informations seems to be the one at fault here.

What does querying the following query in your browser or with curl gives you?

```
https://api.trello.com/1/boards/xxx/cards?key=yyy&token=xxx&actions=commentCard&checklists=all&filter=open&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos
```
Note: You need to put back the rights information (xxx as board id, yyy as key, xxx as token in that order) though :)

On a related note, what's the approximate size of that board? Is it a huge one?

Cheers,

**Comment by stardiviner** [comment]
I have all same errors, as the poster. And got return `[]` from `https://api.trello.com/1/boards/xxx/cards?key=yyy&token=xxx&actions=commentCard&checklists=all&filter=open&fields=closed%2Cdesc%2Cdue%2CidBoard%2CidList%2CidMembers%2Clabels%2Cname%2Cpos
` (I replace them with my keys).

**Comment by ardumont** [comment]
@stardiviner your pb is different than the initial one.

> I found even I set the consumer-key and access-token up:
>
> #+begin_src emacs-lisp
> (load-file (locate-user-emacs-file ".trello/numbchild@gmail.com.el"))
> #+end_src
>

Latest analysis [1] and documentation [2] now explained better that the email as
login in org-trello does not work [1]

[1] https://github.com/org-trello/org-trello/issues?q=label%3Asetup-problem+is%3Aclosed

[2] https://org-trello.github.io/trello-setup.html#credentials

> I check them, they are correct value. Then I do =[C-c o s]= to sync.
>
> The variable org-trello-consumer-key value is nil again. the access token is
> fine. I guess some function erased this variable value.

So for example, assuming your trello user is stardiviner (change to really your trello login), the token and
everything should be set at:
```
~/.emacs.d/.trello/stardiviner.el
```

**Comment by ardumont** [comment]
As for the initial task, i don't have a better clue.

The initial problem says, request timeout server side so the server closed the
connection on the user client query ¯\_(ツ)_/¯.

I'd need refreshed information on the issue.

So closing for now.

Feel free to re-open with updated information if issue arise again.

Cheers,
