### ISSUE TITLE
Cyrillic encoding problem, again

### ISSUE THREAD

**Issue by akater** [org-trello/org-trello#367]
Cyrillic characters in the card name (at the very least) get mangled for me, much like in the issue https://github.com/org-trello/org-trello/issues/318. Point by point, the only difference is, I'm not on Windows. `org-trello` installed from melpa (unstable).

System information:
- system-type: gnu/linux
- locale-coding-system: utf-8-unix
- emacs-version: GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.31)
 of 2017-05-21
- org version: 9.0.10
- org-trello version: 0.8.0
- org-trello path: /home/akater/.emacs.d/elpa/org-trello-20170225.1247/org-trello.el
- request-backend: curl (7.55.1)
- kill-whole-line: nil
- LANG: en_US.utf8
- LC_CTYPE: en_US.utf8

I just started using both org-trello and trello, have had issues with Cyrillic chars in card titles since the beginning.

If I got it right, the trouble starts while in `orgtrello-query--post-or-put`, namely in its `deferred:$` block.

Mangled symbols `:0@B>E0` first appear in the `* deferred:nextc` stack frame of the backtrace. The previous frame starts with `(setq it (deferred:nextc it (lambda (&rest --cl-rest--) (apply (quote #[(G54088 G54089 G54090 G54091 G54092 response) ...`

Parts of the `*deferred:nextc` frame:

```
* deferred:nextc([cl-struct-deferred identity deferred:default-errorback
deferred:default-cancel nil ok [cl-struct-request-response 200 nil
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8
data (:id "59afascrambledscrambledae" :closed nil :desc "" :due nil
:board-id "59afascrambledscrambled28" :checklists nil
:list-id "59afascrambledscrambled" :member-ids nil :labels nil
:name "ai :0@B>E0" :position 675 :url "https://trello.com/

 ...

 :headers (("Content-type" . "application/json"))
 :data "{\"pos\":675,\"labels\":\"\",\"desc\":\"\",\"due\":\"\",
 \"idMembers\":\"\",\"name\":\"ai картоха\",
 \"idList\":\"59afascrambledscrambled\"}"
 :parser orgtrello-query--http-parse :complete
```

This frame contains both the proper chars `картоха` and the mangled ones `:0@B>E0`. (Don't mind the “ai” prior to it, I kept changing the card name randomly to keep the sync process going trying to find the offending part).

In the end, `картоха` turns into `:0@B>E0` in trello. Just in case, “картоха” ≈ “a lovely potato”.

**Comment by ardumont** [comment]
Hello,

According to #340, [this patch](https://github.com/org-trello/org-trello/issues/340#issuecomment-311741652) should help.

To check, [eval the function ](https://github.com/gariepyalex/emacs-request/blob/abeb9de6e1bd2d260a52a1204ada3b7ba8e7c8c9/request.el#L893-L930) (for example, <kbd>M-: paste-the-function-here RET</kbd>) and try again.

Does it help?

Cheers,

**Comment by akater** [comment]
It did indeed help. I should have studied Issues more thoroughly.

Your package and your attitude are quite awesome. Thanks.

**Comment by ardumont** [comment]
> It did indeed help. I should have studied Issues more thoroughly.

Well, it's not that easy to study those issues... So thanks anyways :)
Also, thanks for the initial detailed report, it's quite appreciated.

In any case, that shows that's a real problem since it's referenced in at least 3 issues including yours (#318, #340).
I hope the PR referenced in #318 for emacs-request (which adds the patch i proposed you) will eventually be merged...

> Your package and your attitude are quite awesome. Thanks.

Thanks

Cheers,
