### ISSUE TITLE
can't dynamic-bind browse-url-browser-function?

### ISSUE THREAD

**Issue by unhammer** [org-trello/org-trello#370]
## bug?

probably

### M-x org-trello-bug-report
```
System information:
- system-type: gnu/linux
- locale-coding-system: utf-8
- emacs-version: GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
 of 2017-09-19, modified by Debian
- org version: 9.1.1
- org-trello version: 0.8.0
- org-trello path: /home/unhammer/.emacs.d/elpa/org-trello-0.8.0/org-trello.el
- request-backend: curl
- kill-whole-line: nil
```

### Expected behavior

dynamically overriding browse-url-browser-function should apply to org-trello-jump-to-trello-card

### Actual behavior

opened in eww instead of firefox

### Steps to reproduce the behavior
```
(let ((browse-url-browser-function #'browse-url-firefox))
            (org-trello-jump-to-trello-card))
```

### What do you want?

it should open in the browse-url-browser-function instead of eww

### Why is it better?

trello needs js

Looking at the source, at `org-trello-apply` it's got the right value, but within `orgtrello-controller-jump-to-card` it's wrong. Presumably `deferred` loses the environment; perhaps it can be kept with something like https://github.com/kiwanami/emacs-deferred#using-lexical-scope

**Comment by ardumont** [comment]
Hello,

> it should open in the browse-url-browser-function instead of eww

I agree with that.
I am unable to reproduce that behavior though.

I am using firefox as my default browser.
So i slightly change your recipe to use another browser (chromium).
And now i do have chromium opening tab for the card.

Steps:

- <kbd>M-: RET browse-url-browser-function RET</kbd>
This returns as expected: browse-url-firefox

- Changing that setup to use chromium:
<kbd>M-: RET (setq browse-url-browser-function 'browse-url-chromium)</kbd>

- Checking the setup is indeed changed:
<kbd>M-: RET browse-url-browser-function RET</kbd>
Returns now the new value browse-url-chromium.

- `C-c o j` in an org-trello buffer activated on a card and i do have chromium opened

Cheers,

**Comment by K0HAX** [comment]
The following in my init.el resolves this.
```
(defun my-trello-mode-setup ()
    (setq browse-url-browser-function 'browse-url-chromium))
  (add-hook 'org-trello-mode-hook 'my-trello-mode-setup)
```

**Comment by ardumont** [comment]
Hey, @K0HAX, thanks for the help!

@unhammer did any of those hint help at all?

**Comment by unhammer** [comment]
It probably does, sorry I haven't had a use for org-trello for a while, so if no one else is affected I guess it can be closed
