### ISSUE TITLE
Does not retrieve a list of trello boards when using org-trello-install-board-metadata

### ISSUE THREAD

**Issue by sabexx** [org-trello/org-trello#376]
When running org-trello-install-board-metadata, it does not bring up a list of boards that I have joined.

org-trello-install-key-and-token appears to have worked and has saved the keys in ~/.emacs.d/.trello/my-username.el

I created a blank org file and added it to my list of agenda files and ran:

org-trello-install-board-metadata

and got:

"There are no possible completions of what you have typed" when I hit <tab>. Typing the name of the board (cut 'n pasting it from Trello) does nothing when pressing <enter> to submit.

I installed org-trello from MELPA and it reports version 0.8.0.

**Comment by ardumont** [comment]
Hello,

Can you please report `M-x org-trello-bug-report` output here?

Also, what does `M-x org-trello-check-setup` report?

Cheers,

**Comment by sabexx** [comment]
Thanks to your advice, I tracked it down to my dumbass company proxy.

Thanks for your help, let's close this issue.

**Comment by ardumont** [comment]
> org-trello-bug-report:
> 
> ```
> System information:
> - system-type: windows-nt
> - locale-coding-system: cp1252
> - emacs-version: GNU Emacs 25.3.1 (x86_64-w64-mingw32)
> of 2017-09-13
> - org version: 9.1.3
> - org-trello version: 0.8.0
> - org-trello path: c:/Users/me/.emacs.d/elpa/org-trello-20170225.1247/org-trello.el
> - request-backend: url-retrieve
> - kill-whole-line: nil
> ```

Thanks.

> org-trello-check-setup:
> 
> ```
> - Setup problem.
> Either you did not connect your org-mode buffer with a trello board, to correct this:
> * attach to a board through C-c o I or M-x org-trello-install-board-metadata
> * or create a board from scratch with C-c o b or M-x org-trello-create-board-and-install-metadata).
> Either your org-mode's todo keyword list and your trello board lists are not named the same way (which they must).
> For this, connect to trello and rename your board's list according to your org-mode's todo list.
> Also, you can specify on your org-mode buffer the todo list you want to work with, for example: #+TODO: TODO DOING | DONE FAIL (hit C-c C-c to refresh the setup)
> ```
> 
> Which is not surprising considering I can't set up a board!!

Indeed.
But some part of org-trello can notice, that's nice to know some stuff are not useless ;)

> using create board and lists produces this error:
> 
> ```
> org-trello - Create board and lists...
> Loading c:/Users/me/.emacs.d/.trello/me.el (source)...done
> org-trello - Create board and install metadata...
> org-trello - Creating board ’flump’ with description ’Test board for org-trello’
> Contacting host: proxy-my-company.com:3128
> REQUEST [error] Error from parser orgtrello-query--http-parse: (json-readtable-error)
> org-trello - client - Problem during request - error-thrown: (json-readtable-error)
> Contacting host: proxy-my-company.com:3128
> REQUEST [error] Error from parser orgtrello-query--http-parse: (json-readtable-error)
> org-trello - client - Problem during request - error-thrown: (json-readtable-error)
> REQUEST [error] Error from parser orgtrello-query--http-parse: (json-readtable-error)
> org-trello - client - Problem during request - error-thrown: (json-readtable-error)
> Contacting host: proxy-my-company.com:3128
> REQUEST [error] Error from parser orgtrello-query--http-parse: (json-readtable-error)
> org-trello - client - Problem during request - error-thrown: (json-readtable-error)
> org-trello - Create board and install metadata... FAILED. Error: (buffer-read-only #<buffer *Messages*>)
> ```
> 
> Could it be a proxy issue?

Quite.
It already happened and same as you, windows + proxy!

> Thanks to your advice, I tracked it down to my dumbass company proxy.

Awesome!

> Thanks for your help, let's close this issue.

No problem, thanks for raising this anyway.
In a way, that archives issues and enriches anyone who dares looking for it ;)

Cheers,

**Comment by ardumont** [comment]
> It already happened and same as you, windows + proxy!

There finally found it back #287
