### ISSUE TITLE
Formatting errors on Usage page

### ISSUE THREAD

**Issue by ashton314** [org-trello/org-trello#388]
It looks like there's an unfinished comment block on the [Usage](http://org-trello.github.io/usage.html) page:

<img width="970" alt="screen shot 2018-08-27 at 10 55 04 pm" src="https://user-images.githubusercontent.com/2874507/44701554-7dd2bf00-aa4c-11e8-9726-9c16cdd0ae22.png">

**Comment by ardumont** [comment]
Nice catch!
