### ISSUE TITLE
Wekan integration advice

### ISSUE THREAD

**Issue by Wheest** [org-trello/org-trello#390]
Hello there,

I was recently discussing with someone about org-mode based project management techniques, workflows, and tools.

This project was brought up, which seems pretty interesting.

Another enquiry asked if the system [wekan](https://github.com/wekan/wekan) was supported by org-trello, since wekan and trello seem to have similar goals, though the former is self-hostable.

I didn't think so, but since the projects have similar goals, I wonder if the APIs are similar enough for a fork of org-trello to be non-non-trivial (though not quite trivial).

Alas, I am unfamiliar with both Trello/Wekan APIs, and the org-trello codebase.  A quick overview of the Wekan API is available [here](https://github.com/wekan/wekan/wiki/IRC-FAQ#q-integrating-wekan).  

For folk more familiar in this domain, would the file [org-trello-api.el](https://github.com/org-trello/org-trello/blob/master/org-trello-api.el) be the only file which would need changing to get the system working?  Or is it a bigger undertaking?  I think that the two things that would be needed would be:

- Credential management
- API wrangling

Anything else, or general comments?

Thank you

**Comment by gerroon** [comment]
Wekan mode would be ssooooooooo nice :+1:

**Comment by ardumont** [comment]
Closing because unrelated per-say to org-trello
