### ISSUE TITLE
Opening TLS connection FAILED

### ISSUE THREAD

**Issue by kbourg** [org-trello/org-trello#396]
Dear Developer,

I am very interested by your package org-trello but unfortunalty, I encounter the following problem during the set up of my configuration.

Can you please help me resolve this problem?

Thanks in advance.

### M-x org-trello-bug-report
```
System information:
- system-type: windows-nt
- locale-coding-system: cp1252
- emacs-version: GNU Emacs 25.1.1 (x86_64-w64-mingw32)
 of 2016-09-17
- org version: 8.2.10
- org-trello version: 0.8.1
- org-trello path: c:/Users/languip/AppData/Roaming/.emacs.d/elpa/org-trello-20190304.900/org-trello.el
- request-backend: url-retrieve
- kill-whole-line: nil
```

### Expected behavior

What command did you use and what were you expecting?

### Actual behavior

```
org-trello - Create board and lists...
Loading c:/Users/languip/AppData/Roaming/.emacs.d/.trello/kbourg.el (source)...done
org-trello - Create board and install metadata...
org-trello - Creating board ’test1’ with description ’first test using org-trello’
Contacting host: api.trello.com:443
Opening TLS connection to ‘api.trello.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 api.trello.com’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 api.trello.com --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect api.trello.com:443 -no_ssl2 -ign_eof’...failed
Opening TLS connection to ‘api.trello.com’...failed
org-trello - Create board and install metadata... FAILED. Error: (error "Could not create connection to api.trello.com:443")
```

### Steps to reproduce the behavior

How can we try and reproduce?

Don't hesitate to show some scrambled sample of your org-mode file.
(or *Compile-Log* buffer when it's some packaging problem)...

### More information on

http://org-trello.github.io/contributions.html#issues

### Why is it better?

Thanks for sharing!

Cheers,

**Comment by ardumont** [comment]
Hello,

I remember issues with gnutls being out-dated before.
Have you searched for closed issues in the repository [1]?

Maybe this could help a bit.

[1] https://github.com/org-trello/org-trello/search?q=gnutls&type=Issues

Cheers,
