### ISSUE TITLE
What is the purpose of the PROPERTYs set for each label?

### ISSUE THREAD

**Issue by UndeadKernel** [org-trello/org-trello#401]
This is a question rather than a bug report.

In the main properties drawer of a synced file, for each trello label, there is a property like this:
```org
#+PROPERTY: :label_color label_name
```

What is the purpose of these properties? How can I use them with org-trello?
Is there a way to use the label names instead of the label colors for the tags?

**Comment by ardumont** [comment]
I don't remember the details...
It's related to trello's labels.
For a trello card, you can associate trello labels (those have associated colors).
So those are org-trello's way of setup-ing your trello board's setup within the org-mode file.
