### ISSUE TITLE
Deactivate org-indent minor mode in org-trello-mode buffer

### ISSUE THREAD

**Issue by ardumont** [org-trello/org-trello#406]
I don't know if it's a bug or not.
I finally came across a possible reason of why sometimes the buffer's indented and sometimes, it's not.

There is a minor mode org-indent-mode which is actually running alongside org-mode (at least sometimes).

That might pose issues on the reasoning behing org-trello mode.
At least, i never coded anything with such mode in mind...
So there is that...

**Comment by dmitrym0** [comment]
I have a space added to the beginning of every line under headings. Is this related to what you're talking about?

**Comment by ardumont** [comment]
Yes, something like that.

**Comment by dmitrym0** [comment]
I'll start googling, but is there a way to disable ident-mode for a certain set of files?

**Comment by ardumont** [comment]
> I'll start googling, but is there a way to disable ident-mode for a certain set of files?

Well, i guess you can setup either a org-modehook which checks for a filename pattern.
If the pattern is recognised, that'd call `(org-indent -1)` to deactivate such mode.

Or even simpler, define a org-trello-mode-hook that does that (no need to check for a filename pattern then).

Something like:

```
(add-hook 'org-trello-mode-hook (lambda () (org-indent-mode -1)))
;; (remove-hook 'org-trello-mode-hook (lambda () (org-indent-mode -1))) ;; to remove
```

**Comment by ardumont** [comment]
> (add-hook 'org-trello-mode-hook (lambda () (org-indent-mode -1)))

Also, might be worth to have this as a default hook in org-trello directly...
I mean currently, there is not much point of having that minor mode org-indent-mode there...
As far as i could tell, it's to make multiple levels of `*` nice to the eyes... (which i'd need to check to ensure i'm not saying poppycocks ;)

But in org-trello, we are using checklists instead of `*` (except for the first level card)...

**Comment by ardumont** [comment]
Here is the link to the doc [1]

[1] https://orgmode.org/manual/Org-Indent-Mode.html

According to this doc, there are also other possibilities than my previous
proposal hook:

- define a hook which sets the `org-indent-indentation-per-level` to 0
- add a global header in org-trello mode buffer to `#+STARTUP: noindent`

Quoting that doc:

> To display the buffer in the indented view, activate Org Indent minor mode,
> using M-x org-indent-mode. Text lines that are not headlines are prefixed
> with virtual spaces to vertically align with the headline text147.

So i guess i was not saying too much of poppycocks ;)

Thus my initial hook proposal approach, either user defined or org-trello
defined is thus not that unreasonable \m/

Cheers,

**Comment by consoleaf** [comment]
I've just been investigating it, cause on up-sync it kept replacing first 2-3 characters on each line with spaces. Is it only happening for me?

**Comment by ardumont** [comment]
> I've just been investigating it, cause on up-sync it kept replacing first 2-3
> characters on each line with spaces. Is it only happening for me?

I'm not sure i follow. Where does the spaces replacement occur, in trello or in
your org buffer?

Can you please share a sample of your tryouts?

Thanks in advance.

Cheers,

**Comment by consoleaf** [comment]
Yes, so this:
`* TODO Sample
12345`
Would arrive to Trello, but its description changed to just `345` if I had a line break after it, or just `34` if `5` was the last character in the .org file.

Upon syncing back down it becomes 
`* TODO Sample
  345`

**Comment by ardumont** [comment]
> Would arrive to Trello, but its description changed to just 345 if I had a line break after it, or just 34 if 5 was the last character in the .org file.

Ah yeah, ok. Thanks.

As a good news, I think it's solely card description related. I will see what I
can do to improve on the current commit done already. That must be a matter of
adding some more tests and make them go green again ;)

Cheers,

**Comment by ardumont** [comment]
> As a good news, I think it's solely card description related.

Yes.

But also, that's actually not related to this task though.

----

But yeah, that happens since always (you can activate org-indent-mode and you
should have the same behavior). Please, open a new issue about this so we can
discuss further there.

To avoid this for now, please save your buffer prior to sync the card. And then
that will not happen any longer. Because there is a pre-save-hook which aligns
the description appropriately (with an indent of 2). This indentation helps the
card parsing.

Maybe that could be improved by making that indentation happens when triggering
sync actions instead of a buffer global hook actions. Then again, that's a
discussion in another issue.

Cheers,
