### ISSUE TITLE
Synching from and to Trello does not work

### ISSUE THREAD

**Issue by tkreuder** [org-trello/org-trello#409]
Hello,
i cannot get synching working in both directions, i followed the getting started guide and watched the videos (**Creating boards works fine and selecting ones also**), but synching in both directions does not work.
(I found similar issues like: https://github.com/org-trello/org-trello/issues/358, but none of this seems to help).

I am on GNU Emacs 26.3 and have doom emacs installed.

![image](https://user-images.githubusercontent.com/385110/82419939-5a9d3e00-9a7f-11ea-8530-ff7e14525a18.png)

I also tried with a higher log level, but there is no further info:
![image](https://user-images.githubusercontent.com/385110/82420510-178f9a80-9a80-11ea-8813-42388a2edcb8.png)

Any idea what might be wrong, or how i can get better debug output?

**Comment by ardumont** [comment]
Please `M-x org-trello-bug-report` and report here the output.

Where does the first error message comes from (what `org-trello-*` action)? 

Have you checked: M-x org-trello-check-config? (that looks like its output).

A scrambled sample of your org-mode message will definitely help as well.

Note: I don't know what doom emacs is.

Cheers,

**Comment by tkreuder** [comment]
Thanks a lot for the fast reply :)

> `M-x org-trello-bug-report`


![image](https://user-images.githubusercontent.com/385110/82434552-48c59600-9a93-11ea-9141-3d1182078188.png)

> Where does the first error message comes from (what org-trello-* action)?

![](https://user-images.githubusercontent.com/385110/82419939-5a9d3e00-9a7f-11ea-8530-ff7e14525a18.png) This comes from `org-trello-sync-buffer`

> Have you checked: M-x org-trello-check-config? (that looks like its output).

I just have: `org-trello-check-setup`
`org-trello - Checking setup. DONE.`

So listing boards and getting :PROPERTIES works fine, also creating new boards, but synching is not possible.

`org-trello-sync-buffer` is the only way to synch, right? If my file just contains the :PROPERTIES it would fetch the trello board, right?

**Comment by tkreuder** [comment]
In the meantime i tried the following: 
`curl --request GET \ --url 'https://api.trello.com/1/boards/{board_id}/cards?` and returns the list of cards from one of my boards. Something else i should / could try?

**Comment by ardumont** [comment]
Can you provide a sample scrambled of your main :PROPERTIES: drawer?

Thanks.

**Comment by tkreuder** [comment]
```
:PROPERTIES:
#+PROPERTY: board-name Test-Org
#+PROPERTY: board-id 123
#+PROPERTY: [X] 123
#+PROPERTY: [?] 123
#+PROPERTY: [-] 123
#+PROPERTY: [-] 123
#+PROPERTY: KILL 123
#+PROPERTY: DONE 123
#+PROPERTY: HOLD 123
#+PROPERTY: WAIT 123
#+PROPERTY: STRT 123
#+PROPERTY: PROJ 123
#+PROPERTY: TODO 123
#+TODO: TODO PROJ STRT WAIT HOLD | DONE KILL [-] [-] [?] [X]
#+PROPERTY: orgtrello_user_tkreuder 123
#+PROPERTY: :purple
#+PROPERTY: :blue
#+PROPERTY: :red
#+PROPERTY: :orange
#+PROPERTY: :yellow
#+PROPERTY: :green
#+PROPERTY: orgtrello_user_me tkreuder
:END:


```
Beside that it looks like `org-trello-sync-buffer` does not make a request, so it looks like something fails before the actual request is made. For `org-trello-create-board-and-install-metadata` i can see requests / traffic.

**Comment by ardumont** [comment]
> #+PROPERTY: [X] 123

I have no idea if those properties are actually something that could actually work in org-mode or trello for that matters.

Can you please try without as a first shot in the dark?

>  Something else i should / could try?

About debugging org-trello a bit more with a repl (ielm) from your emacs [1]

[1] https://ardumont.github.io/debug

That might help.

Cheers,

**Comment by tkreuder** [comment]
These properties `#+PROPERTY: [X] 123` have been autogenerated by using the `org-trello-create-board-and-install-metadata` exept that i changed the ids to 123 in the post.

**Comment by ardumont** [comment]
> These properties #+PROPERTY: [X] 123 have been autogenerated by using the org-trello-create-
> board-and-install-metadata exept that i changed the ids to 123 in the post.

Then that's one potential source of the issue.
What are the column titles of your trello board?

That should map one-to-one with trello's status keywords.

So `[-] [-] [?] [X]` references in your main properties should go away.

**Comment by tkreuder** [comment]
Ah... i thought those items come from the package, but they are from `~/emacs.d/modules/lang/org/config.el:158:          ("STRT" . +org-todo-active)` and it automatically creates the setup from above

> :PROPERTIES:
> #+PROPERTY: board-name Test-Org
> #+PROPERTY: board-id 123
> #+PROPERTY: [X] 123
> #+PROPERTY: [?] 123
> #+PROPERTY: [-] 123
> #+PROPERTY: [-] 123
> #+PROPERTY: KILL 123
> #+PROPERTY: DONE 123
> #+PROPERTY: HOLD 123
> #+PROPERTY: WAIT 123
> #+PROPERTY: STRT 123
> #+PROPERTY: PROJ 123
> #+PROPERTY: TODO 123
> #+TODO: TODO PROJ STRT WAIT HOLD | DONE KILL [-] [-] [?] [X]
> #+PROPERTY: orgtrello_user_tkreuder 123
> #+PROPERTY: :purple
> #+PROPERTY: :blue
> #+PROPERTY: :red
> #+PROPERTY: :orange
> #+PROPERTY: :yellow
> #+PROPERTY: :green
> #+PROPERTY: orgtrello_user_me tkreuder
> :END:

**Comment by tkreuder** [comment]
Synching to Trello now works :) For some reason from is always nil: https://github.com/org-trello/org-trello/blob/4ddc257fe24e97c01e12b247568581ff255f0e8d/org-trello.el#L296 so nothing is ever synced from Trello.

**Comment by tkreuder** [comment]
Its working now, when i type an Ex command `(org-trello-sync-buffer t)`. I found already an issue with that topic, but i did not know, where to put it. Is there an easier way, except for this Ex command?

**Comment by ardumont** [comment]
Hello,

Nice that your setup work finally.

`org-todo-keywords` is indeed a org-mode setup which is reused in org-trello to
setup the keywords avoiding the user to repeat its setup in another org-trello
custom variables.

> For some reason from is always nil:

For `from` to be something, you need to use the emacs `C-u` modifier.

> ... an Ex command (org-trello-sync-buffer t) ...

I don't know what you meant by an Ex command. The command is an interactive one
and it's triggered by `M-x` (Meta which is most of the time the Alt key). Or by
a binding (<kdb>M-x org-trello-help-describing-bindings</kdb> or `C-c o h`).

For the optional parameter `from` to be something (so not nil), you need to use
emacs' universal modifier `C-u` (Control-u). So <kdb>C-u M-x
org-trello-sync-buffer</kbd> (or `C-u C-c o s`).

It's explained in the documentation [1]

[1] http://org-trello.github.io/bindings.html

> Its working now, when i type an Ex command (org-trello-sync-buffer t). Is
> there an easier way, except for this Ex command?

So to be fair, it always worked ;)

You are not supposed to use the call to function yourself. Except if you want
to define your own interactive commands and/or functions like the other users
who wanted to (to define `org-trello-buffer-(pull|push)` iirc ;)

> Thanks a lot for your awesome help so far and fast replies :)

Thanks

Cheers,

**Comment by tkreuder** [comment]
Ah... it interfers... C-u is used to scroll up half a page, when evil mode is activated, that is why I did not work. Which brings us to the Ex command, which is a vim way of executing commands and here I just :(org-trello-sync-buffer t)

**Comment by tkreuder** [comment]
**Solution for Doom Emacs users**: Leader-u C-c o s , where Leader-u is SPC-u per default.

For further info: https://github.com/hlissner/doom-emacs/issues/747

**Comment by ardumont** [comment]
You can also define your own command so then you don't need to use the `C-u`
modifier:

``` emacs-lisp
(defun org-trello-sync-from-trello ()  ;; <- name it like you want heh ;)
  (interactive)
  (org-trello-sync-buffer t))
```
should work

But then, there is more than one function which needs it, e.g org-trello-sync-card, ...
You can filter out on "&optional from" in the org-trello.el file to find them.

That feels strange that a major(minor?)-mode chose to override the C-u
modifier... But ¯\_(ツ)_/¯

**Comment by ardumont** [comment]
Closing now as I think everything is fine.
